# Code Generated by Sidekick is for learning and experimentation purposes only.
# services/write_service/app.py

from flask import Flask, request, jsonify
import psycopg2
import redis
from datetime import datetime, timedelta
from url_encoder import Base62Encoder
from rate_limiter import RateLimiter
import sys

sys.path.append('../..')
from config import Config

app = Flask(__name__)
encoder = Base62Encoder()


# Code Generated by Sidekick is for learning and experimentation purposes only.
# Add to services/write_service/app.py

@app.route('/health', methods=['GET'])
def health_check():
    """Health check endpoint for Docker"""
    try:
        # Check database connection
        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute("SELECT 1")
        cursor.close()
        conn.close()

        # Check Redis connection
        redis_client.ping()

        return jsonify({
            'status': 'healthy',
            'services': 'write-services',
            'database': 'connected',
            'redis': 'connected'
        }), 200
    except Exception as e:
        return jsonify({
            'status': 'unhealthy',
            'error': str(e)
        }), 503


# Connect to PostgreSQL Primary (for writes)
def get_db_connection():
    return psycopg2.connect(
        host=Config.DB_PRIMARY_HOST,
        port=Config.DB_PRIMARY_PORT,
        database=Config.DB_NAME,
        user=Config.DB_USER,
        password=Config.DB_PASSWORD
    )


# Redis for rate limiting
redis_client = redis.Redis(
    host=Config.REDIS_HOST,
    port=Config.REDIS_PORT,
    decode_responses=True
)

rate_limiter = RateLimiter(redis_client)


@app.route('/shorten', methods=['POST'])
def shorten_url():
    """
    Create a shortened URL.

    Request Body:
    {
        "url": "https://example.com/very/long/url",
        "created_by": "user@example.com",
        "expires_in_days": 30  (optional)
    }

    Response:
    {
        "short_url": "http://short.url/a3Xk2",
        "original_url": "https://example.com/very/long/url",
        "expires_at": "2025-02-15T10:30:00"
    }
    """

    # Rate limiting check
    client_ip = request.remote_addr
    if not rate_limiter.allow_request(client_ip):
        return jsonify({'error': 'Rate limit exceeded'}), 429

    data = request.json
    original_url = data.get('url')
    created_by = data.get('created_by', 'anonymous')
    expires_in_days = data.get('expires_in_days')

    if not original_url:
        return jsonify({'error': 'URL is required'}), 400

    # Calculate expiration
    expiration_time = None
    if expires_in_days:
        expiration_time = datetime.now() + timedelta(days=expires_in_days)

    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        # Insert URL and get auto-generated ID
        cursor.execute("""
            INSERT INTO urls (url, short_url, created_by, expiration_time, status)
            VALUES (%s, %s, %s, %s, 'active')
            RETURNING id
        """, (original_url, 'temp', created_by, expiration_time))

        url_id = cursor.fetchone()[0]

        # Generate short URL from ID using Base62
        short_code = encoder.encode(url_id)

        # Update with actual short code
        cursor.execute("""
            UPDATE urls SET short_url = %s WHERE id = %s
        """, (short_code, url_id))

        conn.commit()

        # Seed Redis cache immediately (write-through caching)
        redis_client.setex(
            f"url:{short_code}",
            Config.REDIS_TTL,
            original_url
        )

        full_short_url = f"{Config.BASE_URL}{short_code}"

        return jsonify({
            'short_url': full_short_url,
            'original_url': original_url,
            'expires_at': expiration_time.isoformat() if expiration_time else None
        }), 201

    except Exception as e:
        return jsonify({'error': str(e)}), 500
    finally:
        cursor.close()
        conn.close()


@app.route('/url/<short_code>', methods=['GET'])
def get_url_stats(short_code):
    """
    Get statistics for a short URL.

    Response:
    {
        "short_code": "a3Xk2",
        "original_url": "https://example.com",
        "clicks": 42,
        "created_at": "2025-01-15T10:30:00",
        "expires_at": "2025-02-15T10:30:00",
        "status": "active"
    }
    """
    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        cursor.execute("""
            SELECT short_url, url, clicks, created_at, expiration_time, status
            FROM urls
            WHERE short_url = %s
        """, (short_code,))

        result = cursor.fetchone()
        cursor.close()
        conn.close()

        if not result:
            return jsonify({'error': 'URL not found'}), 404

        return jsonify({
            'short_code': result[0],
            'original_url': result[1],
            'clicks': result[2],
            'created_at': result[3].isoformat() if result[3] else None,
            'expires_at': result[4].isoformat() if result[4] else None,
            'status': result[5]
        }), 200

    except Exception as e:
        print(f"Error getting URL stats: {e}")
        return jsonify({'error': str(e)}), 500
if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5001)
