# Code Generated by Sidekick is for learning and experimentation purposes only.
# services/write_service/models.py

from sqlalchemy import create_engine, Column, BigInteger, String, Text, Integer, DateTime, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, relationship
from datetime import datetime
import sys

sys.path.append('../..')
from config import Config

Base = declarative_base()


class URL(Base):
    """
    Main URL model representing shortened URLs.

    Attributes:
        id: Auto-incrementing primary key (used to generate short codes)
        url: Original long URL
        short_url: Generated short code (e.g., "a3Xk2")
        created_at: When URL was created
        expiration_time: When URL expires (NULL = never)
        created_by: User/API identifier who created it
        status: active, expired, disabled
        clicks: Total number of clicks (incremented by analytics worker)
        last_accessed: Last time URL was accessed
    """

    __tablename__ = 'urls'

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    url = Column(Text, nullable=False)
    short_url = Column(String(10), unique=True, nullable=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    expiration_time = Column(DateTime, nullable=True)
    created_by = Column(String(100), nullable=True)
    status = Column(String(20), default='active', index=True)
    clicks = Column(BigInteger, default=0)
    last_accessed = Column(DateTime, nullable=True)

    # Relationship to click events
    click_events = relationship('ClickEvent', back_populates='url', cascade='all, delete-orphan')

    def __repr__(self):
        return f"<URL(id={self.id}, short_url='{self.short_url}', clicks={self.clicks})>"

    def to_dict(self):
        """Convert model to dictionary for JSON responses"""
        return {
            'id': self.id,
            'url': self.url,
            'short_url': self.short_url,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'expiration_time': self.expiration_time.isoformat() if self.expiration_time else None,
            'created_by': self.created_by,
            'status': self.status,
            'clicks': self.clicks,
            'last_accessed': self.last_accessed.isoformat() if self.last_accessed else None
        }

    def is_expired(self):
        """Check if URL has expired"""
        if self.expiration_time is None:
            return False
        return datetime.utcnow() > self.expiration_time

    def is_active(self):
        """Check if URL is active and not expired"""
        return self.status == 'active' and not self.is_expired()


class ClickEvent(Base):
    """
    Detailed click tracking for analytics.

    Each time a short URL is accessed, a record is created here.
    This allows for detailed analytics like:
    - Traffic patterns over time
    - Geographic distribution
    - Device/browser usage
    - Referrer sources
    """

    __tablename__ = 'click_events'

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    short_url = Column(String(10), ForeignKey('urls.short_url'), nullable=False, index=True)
    clicked_at = Column(DateTime, default=datetime.utcnow, index=True)
    user_agent = Column(Text, nullable=True)
    ip_address = Column(String(45), nullable=True)  # IPv6 max length
    referrer = Column(Text, nullable=True)
    country = Column(String(100), nullable=True)

    # Relationship back to URL
    url = relationship('URL', back_populates='click_events')

    def __repr__(self):
        return f"<ClickEvent(id={self.id}, short_url='{self.short_url}', clicked_at={self.clicked_at})>"

    def to_dict(self):
        """Convert model to dictionary for JSON responses"""
        return {
            'id': self.id,
            'short_url': self.short_url,
            'clicked_at': self.clicked_at.isoformat() if self.clicked_at else None,
            'user_agent': self.user_agent,
            'ip_address': self.ip_address,
            'referrer': self.referrer,
            'country': self.country
        }


# Database session factory
def get_primary_engine():
    """Get database engine for PRIMARY (write operations)"""
    connection_string = (
        f"postgresql://{Config.DB_USER}:{Config.DB_PASSWORD}"
        f"@{Config.DB_PRIMARY_HOST}:{Config.DB_PRIMARY_PORT}/{Config.DB_NAME}"
    )
    return create_engine(connection_string, pool_size=10, max_overflow=20)


def get_replica_engine():
    """Get database engine for REPLICA (read operations)"""
    connection_string = (
        f"postgresql://{Config.DB_USER}:{Config.DB_PASSWORD}"
        f"@{Config.DB_REPLICA_HOST}:{Config.DB_REPLICA_PORT}/{Config.DB_NAME}"
    )
    return create_engine(connection_string, pool_size=20, max_overflow=40)


# Session makers
PrimarySession = sessionmaker(bind=get_primary_engine())
ReplicaSession = sessionmaker(bind=get_replica_engine())


def init_database():
    """
    Initialize database schema.
    Run this once to create all tables.
    """
    engine = get_primary_engine()
    Base.metadata.create_all(engine)
    print("✓ Database tables created successfully")


if __name__ == '__main__':
    # Create tables if running this file directly
    init_database()
