# Code Generated by Sidekick is for learning and experimentation purposes only.
# services/write_service/rate_limiter.py

import redis
from config import Config


class RateLimiter:
    """
    Token bucket rate limiter using Redis.
    Prevents abuse of the URL creation endpoint.
    """

    def __init__(self, redis_client: redis.Redis):
        self.redis = redis_client

    def allow_request(self, identifier: str) -> bool:
        """
        Check if request is allowed based on rate limit.
        Uses sliding window counter.

        Args:
            identifier: Client IP or user ID

        Returns:
            True if request allowed, False if rate limited
        """
        key = f"rate_limit:{identifier}"

        # Increment counter
        current = self.redis.incr(key)

        # Set expiration on first request
        if current == 1:
            self.redis.expire(key, Config.RATE_LIMIT_WINDOW)

        # Check if under limit
        return current <= Config.RATE_LIMIT_REQUESTS
