# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: app/middleware/request_context.py
import logging
from uuid import uuid4

from fastapi import Request

from app.observability.context import bind_log_context, clear_log_context

logger = logging.getLogger("booking-api")


async def request_context_middleware(request: Request, call_next):
    clear_log_context()

    request_id = request.headers.get("x-request-id") or str(uuid4())

    user = getattr(request.state, "user", None)
    user_id = getattr(user, "id", None) or request.headers.get("x-user-id")

    bind_log_context(request_id=request_id, user_id=user_id)
    logger.info("request_started")

    try:
        response = await call_next(request)
        response.headers["x-request-id"] = request_id
        logger.info("request_completed")
        return response
    except Exception:
        logger.exception("request_failed")
        raise
    finally:
        clear_log_context()
