# Code Generated by Sidekick is for learning and experimentation purposes only.

from datetime import datetime

from sqlalchemy import (
    JSON,
    Boolean,
    Column,
    DateTime,
    Index,
    Numeric,
    String,
    UniqueConstraint,
)

from ledger_service.app.db import Base


class Account(Base):
    """
    Every entity that holds money has an account.

    Account types:
    - merchant       : money owed to merchant
    - platform       : platform revenue (fees)
    - escrow         : money held between capture and payout
    - customer       : tracks customer payments (liability)
    - fee            : platform fee collection
    - refund_reserve : money reserved for refunds
    """
    __tablename__ = "accounts"

    id                = Column(String(100), primary_key=True)
    owner_id          = Column(String(100), nullable=False, index=True)
    owner_type        = Column(String(30),  nullable=False)               # merchant|platform|escrow|customer
    account_type      = Column(String(30),  nullable=False)               # asset|liability|revenue|expense
    currency          = Column(String(10),  nullable=False, default="usd")
    balance           = Column(Numeric(20, 6), nullable=False, default=0)
    available_balance = Column(Numeric(20, 6), nullable=False, default=0)
    pending_balance   = Column(Numeric(20, 6), nullable=False, default=0)
    is_active         = Column(Boolean, default=True)
    description       = Column(String(255), nullable=True)
    created_at        = Column(DateTime, default=datetime.utcnow)
    updated_at        = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    __table_args__ = (
        Index("idx_account_owner", "owner_id", "currency"),
    )


class LedgerEntry(Base):
    """
    IMMUTABLE double-entry bookkeeping record.

    Rules:
    - NEVER update or delete
    - Every transaction creates PAIRED entries (debit + credit)
    - Sum of all entries for a transaction = 0
    - Append-only audit trail

    Real example - Customer pays $100:
    DEBIT  escrow_account    +100.00  (money arrives in escrow)
    CREDIT customer_account  -100.00  (customer owes less)

    After capture + fee:
    DEBIT  escrow_account    -100.00  (money leaves escrow)
    CREDIT merchant_account   +97.50  (merchant gets money minus fee)
    CREDIT platform_fee        +2.50  (platform keeps fee)
    """
    __tablename__ = "ledger_entries"

    id             = Column(String(100), primary_key=True)
    transaction_id = Column(String(100), nullable=False, index=True)  # groups paired entries
    account_id     = Column(String(100), nullable=False, index=True)
    payment_id     = Column(String(100), nullable=False, index=True)
    merchant_id    = Column(String(100), nullable=False, index=True)

    # Entry type
    entry_type = Column(String(10), nullable=False)   # debit | credit
    event_type = Column(String(30), nullable=False)   # payment.authorized|payment.captured|payment.refunded|payment.voided

    # Amount (always positive - direction determined by entry_type)
    amount   = Column(Numeric(20, 6), nullable=False)
    currency = Column(String(10),     nullable=False)

    # Running balance after this entry
    balance_after = Column(Numeric(20, 6), nullable=False)

    # Reference info
    description    = Column(String(500), nullable=True)
    extra_metadata = Column("metadata", JSON, default=dict)  # ✅ "metadata" is reserved by SQLAlchemy Declarative API

    # Timestamps (immutable)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)

    __table_args__ = (
        Index("idx_entry_payment",     "payment_id",     "event_type"),
        Index("idx_entry_merchant",    "merchant_id",    "created_at"),
        Index("idx_entry_transaction", "transaction_id"),
    )


class LedgerTransaction(Base):
    """
    Groups multiple LedgerEntries into one atomic transaction.
    Think of it as the "header" for a set of entries.
    """
    __tablename__ = "ledger_transactions"

    id          = Column(String(100), primary_key=True)
    payment_id  = Column(String(100), nullable=False, index=True)
    merchant_id = Column(String(100), nullable=False, index=True)
    event_type  = Column(String(30),  nullable=False)
    amount      = Column(Numeric(20, 6), nullable=False)
    currency    = Column(String(10),  nullable=False)
    status      = Column(String(20),  nullable=False, default="posted")  # posted|reversed
    description = Column(String(500), nullable=True)
    extra_metadata = Column("metadata", JSON, default=dict)  # ✅ "metadata" is reserved by SQLAlchemy Declarative API

    created_at = Column(DateTime, default=datetime.utcnow, index=True)

    __table_args__ = (
        UniqueConstraint("payment_id", "event_type", name="uq_payment_event"),
    )
