# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: Payment/utils/cards.py

import hashlib


def get_card_brand(card_number: str) -> str:
    first = card_number[0]
    first_two = card_number[:2]

    if first == "4":
        return "visa"
    if first_two in ["51", "52", "53", "54", "55"]:
        return "mastercard"
    if first_two in ["34", "37"]:
        return "amex"
    if first_two in ["60", "64", "65"]:
        return "discover"
    return "unknown"


def generate_card_fingerprint(card_number: str) -> str:
    return hashlib.sha256(card_number.encode()).hexdigest()
