# filename: app/models/booking.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

from sqlalchemy import Column, String, DateTime, Numeric, ForeignKey, Index
from sqlalchemy.dialects.postgresql import UUID, ENUM
from sqlalchemy.orm import relationship
from datetime import datetime
import uuid
import enum

from app.database import Base


class BookingStatus(str, enum.Enum):
    PENDING = "pending"
    CONFIRMED = "confirmed"
    CANCELLED = "cancelled"
    FAILED = "failed"


class PaymentStatus(str, enum.Enum):
    PENDING = "pending"
    COMPLETED = "completed"
    FAILED = "failed"
    REFUNDED = "refunded"


class Booking(Base):
    __tablename__ = "bookings"

    booking_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    event_id = Column(UUID(as_uuid=True), ForeignKey("events.event_id"), nullable=False)
    seat_id = Column(UUID(as_uuid=True), ForeignKey("seats.seat_id"), nullable=False)
    booking_status = Column(
        ENUM(BookingStatus, name="booking_status_enum", create_type=True),
        default=BookingStatus.PENDING,
        nullable=False
    )
    payment_status = Column(
        ENUM(PaymentStatus, name="payment_status_enum", create_type=True),
        default=PaymentStatus.PENDING,
        nullable=False
    )
    total_amount = Column(Numeric(10, 2), nullable=False)
    idempotency_key = Column(String(255), unique=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    event = relationship("Event", back_populates="bookings")
    seat = relationship("Seat", back_populates="booking")

    __table_args__ = (
        Index('idx_user_created', 'user_id', 'created_at'),
        Index('idx_seat_event', 'seat_id', 'event_id', unique=True),
    )

    def __repr__(self):
        return f"<Booking {self.booking_id} - {self.booking_status}>"
