# filename: app/models/booking_attempt.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

from sqlalchemy import Column, String, DateTime, Integer, Text, Index
from sqlalchemy.dialects.postgresql import UUID
from datetime import datetime
import uuid

from app.database import Base


class BookingAttempt(Base):
    __tablename__ = "booking_attempts"

    attempt_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    event_id = Column(UUID(as_uuid=True), nullable=False)
    seat_id = Column(UUID(as_uuid=True), nullable=True)
    attempt_status = Column(String(50), nullable=False, index=True)
    error_message = Column(Text, nullable=True)
    response_time_ms = Column(Integer, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)

    __table_args__ = (
        Index('idx_attempts_status_time', 'attempt_status', 'created_at'),
    )

    def __repr__(self):
        return f"<BookingAttempt {self.attempt_id} - {self.attempt_status}>"
