# filename: app/models/event.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

from sqlalchemy import Column, String, DateTime, Integer, Index
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from datetime import datetime
import uuid

from app.database import Base


class Event(Base):
    __tablename__ = "events"

    event_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    event_name = Column(String(255), nullable=False, index=True)
    event_date = Column(DateTime, nullable=False, index=True)
    venue = Column(String(255), nullable=False)
    total_seats = Column(Integer, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    seats = relationship("Seat", back_populates="event", cascade="all, delete-orphan")
    bookings = relationship("Booking", back_populates="event")

    __table_args__ = (
        Index('idx_event_date_name', 'event_date', 'event_name'),
    )

    def __repr__(self):
        return f"<Event {self.event_name} on {self.event_date}>"
