# filename: app/models/seat.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

from sqlalchemy import Column, String, DateTime, Integer, Numeric, ForeignKey, Index, CheckConstraint
from sqlalchemy.dialects.postgresql import UUID, ENUM
from sqlalchemy.orm import relationship
from datetime import datetime
import uuid
import enum

from app.database import Base


class SeatStatus(str, enum.Enum):
    AVAILABLE = "available"
    RESERVED = "reserved"
    BOOKED = "booked"
    LOCKED = "locked"


class Seat(Base):
    __tablename__ = "seats"

    seat_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    event_id = Column(UUID(as_uuid=True), ForeignKey("events.event_id", ondelete="CASCADE"), nullable=False)
    seat_number = Column(String(50), nullable=False)
    seat_section = Column(String(50))
    seat_row = Column(String(10))
    price = Column(Numeric(10, 2), nullable=False)
    status = Column(
        ENUM(SeatStatus, name="seat_status_enum", create_type=True),
        default=SeatStatus.AVAILABLE,
        nullable=False,
        index=True
    )
    version = Column(Integer, default=0, nullable=False)
    reserved_until = Column(DateTime, nullable=True, index=True)
    booked_by = Column(UUID(as_uuid=True), nullable=True)
    booked_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    event = relationship("Event", back_populates="seats")
    booking = relationship("Booking", back_populates="seat", uselist=False)

    __table_args__ = (
        Index('idx_event_status', 'event_id', 'status'),
        Index('idx_event_seat', 'event_id', 'seat_number', unique=True),
        CheckConstraint(
            "status IN ('available', 'reserved', 'booked', 'locked')",
            name='check_seat_status'
        ),
    )

    def __repr__(self):
        return f"<Seat {self.seat_number} - {self.status}>"
