# Code Generated by Sidekick is for learning and experimentation purposes only.
# ========================================
# URL Shortener System - Full Test Suite
# ========================================

Write-Host "`n╔════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║   URL Shortener - System Test Suite   ║" -ForegroundColor Cyan
Write-Host "╚════════════════════════════════════════╝`n" -ForegroundColor Cyan

# Test 1: Health Checks
Write-Host "═══ Test 1: Health Checks ═══" -ForegroundColor Yellow
try {
    $writeHealth = Invoke-RestMethod -Uri "http://localhost:5001/health"
    Write-Host "✅ Write Service: $($writeHealth.status)" -ForegroundColor Green
} catch {
    Write-Host "❌ Write Service: Failed" -ForegroundColor Red
}

try {
    $redirectHealth = Invoke-RestMethod -Uri "http://localhost:5002/health"
    Write-Host "✅ Redirect Service: $($redirectHealth.status)" -ForegroundColor Green
} catch {
    Write-Host "❌ Redirect Service: Failed" -ForegroundColor Red
}

# Test 2: Create Short URLs
Write-Host "`n═══ Test 2: Create Short URLs ═══" -ForegroundColor Yellow
$testUrls = @(
    @{url="https://www.google.com"; created_by="user1"},
    @{url="https://www.github.com"; created_by="user2"},
    @{url="https://www.stackoverflow.com"; created_by="user3"}
)

$createdUrls = @()
foreach ($testUrl in $testUrls) {
    try {
        $response = Invoke-RestMethod -Uri "http://localhost:5001/shorten" `
            -Method POST `
            -ContentType "application/json" `
            -Body ($testUrl | ConvertTo-Json)

        $shortCode = $response.short_url.Split('/')[-1]
        $createdUrls += $shortCode
        Write-Host "✅ Created: $shortCode → $($testUrl.url)" -ForegroundColor Green
    } catch {
        Write-Host "❌ Failed to create URL for $($testUrl.url)" -ForegroundColor Red
    }
}

Start-Sleep -Seconds 2

# Test 3: Test Redirects
Write-Host "`n═══ Test 3: Test Redirects ═══" -ForegroundColor Yellow
foreach ($shortCode in $createdUrls) {
    try {
        $result = Invoke-WebRequest -Uri "http://localhost:5002/$shortCode" `
            -MaximumRedirection 0 `
            -ErrorAction Stop
    } catch {
        if ($_.Exception.Response.StatusCode.value__ -eq 301) {
            $location = $_.Exception.Response.Headers['Location']
            Write-Host "✅ Redirect $shortCode → $location" -ForegroundColor Green
        } else {
            Write-Host "❌ Redirect failed for $shortCode" -ForegroundColor Red
        }
    }
}

Start-Sleep -Seconds 3

# Test 4: Get URL Info
Write-Host "`n═══ Test 4: Get URL Information ═══" -ForegroundColor Yellow
foreach ($shortCode in $createdUrls) {
    try {
        $info = Invoke-RestMethod -Uri "http://localhost:5001/url/$shortCode"
        Write-Host "✅ $shortCode - Clicks: $($info.clicks) | Status: $($info.status)" -ForegroundColor Green
    } catch {
        Write-Host "❌ Failed to get info for $shortCode" -ForegroundColor Red
    }
}

# Test 5: List All URLs
Write-Host "`n═══ Test 5: List All URLs ═══" -ForegroundColor Yellow
try {
    $allUrls = Invoke-RestMethod -Uri "http://localhost:5001/urls"
    Write-Host "✅ Total URLs: $($allUrls.urls.Count)" -ForegroundColor Green
    $allUrls.urls | Select-Object -First 5 | Format-Table -Property short_url, url, clicks, status
} catch {
    Write-Host "❌ Failed to list URLs" -ForegroundColor Red
}

# Test 6: Analytics - Click Heatmap
Write-Host "`n═══ Test 6: Analytics - Click Heatmap ═══" -ForegroundColor Yellow
try {
    $heatmap = Invoke-RestMethod -Uri "http://localhost:5002/analytics/heatmap?days=7"
    Write-Host "✅ Heatmap data retrieved for $($heatmap.dates.Count) dates" -ForegroundColor Green
} catch {
    Write-Host "❌ Failed to get heatmap data" -ForegroundColor Red
}

# Test 7: Analytics - Top URLs
Write-Host "`n═══ Test 7: Analytics - Top URLs ═══" -ForegroundColor Yellow
try {
    $topUrls = Invoke-RestMethod -Uri "http://localhost:5002/analytics/top-urls?limit=5"
    Write-Host "✅ Top $($topUrls.urls.Count) URLs:" -ForegroundColor Green
    $topUrls.urls | Format-Table -Property short_url, original_url, total_clicks
} catch {
    Write-Host "❌ Failed to get top URLs" -ForegroundColor Red
}

# Test 8: Test URL Update
Write-Host "`n═══ Test 8: Test URL Update ═══" -ForegroundColor Yellow
if ($createdUrls.Count -gt 0) {
    $testCode = $createdUrls[0]
    try {
        $updateBody = @{
            expiration_time = (Get-Date).AddDays(30).ToString("yyyy-MM-ddTHH:mm:ss")
        } | ConvertTo-Json

        $updated = Invoke-RestMethod -Uri "http://localhost:5001/url/$testCode" `
            -Method PUT `
            -ContentType "application/json" `
            -Body $updateBody
        Write-Host "✅ Updated $testCode - Expiration set" -ForegroundColor Green
    } catch {
        Write-Host "❌ Failed to update $testCode" -ForegroundColor Red
    }
}

# Test 9: Test URL Disable/Enable
Write-Host "`n═══ Test 9: Test Disable/Enable ═══" -ForegroundColor Yellow
if ($createdUrls.Count -gt 1) {
    $testCode = $createdUrls[1]
    try {
        # Disable
        $disabled = Invoke-RestMethod -Uri "http://localhost:5001/url/$testCode/disable" -Method POST
        Write-Host "✅ Disabled $testCode" -ForegroundColor Green

        # Try to access (should fail)
        try {
            $result = Invoke-WebRequest -Uri "http://localhost:5002/$testCode" -MaximumRedirection 0 -ErrorAction Stop
        } catch {
            if ($_.Exception.Response.StatusCode.value__ -eq 404) {
                Write-Host "✅ Correctly blocked access to disabled URL" -ForegroundColor Green
            }
        }

        # Re-enable
        $enabled = Invoke-RestMethod -Uri "http://localhost:5001/url/$testCode/enable" -Method POST
        Write-Host "✅ Re-enabled $testCode" -ForegroundColor Green
    } catch {
        Write-Host "❌ Failed disable/enable test" -ForegroundColor Red
    }
}

# Test 10: Analytics Workers Check
Write-Host "`n═══ Test 10: Analytics Workers Status ═══" -ForegroundColor Yellow
Write-Host "Checking analytics worker logs..." -ForegroundColor Cyan
docker compose logs --tail=5 analytics-worker-1 analytics-worker-2

# Final Summary
Write-Host "`n╔════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║          Test Suite Complete!          ║" -ForegroundColor Cyan
Write-Host "╚════════════════════════════════════════╝`n" -ForegroundColor Cyan

Write-Host "Access Points:" -ForegroundColor Yellow
Write-Host "  • Write API:     http://localhost:5001" -ForegroundColor White
Write-Host "  • Redirect API:  http://localhost:5002" -ForegroundColor White
Write-Host "  • RabbitMQ UI:   http://localhost:15672 (guest/guest)" -ForegroundColor White
