# Code Generated by Sidekick is for learning and experimentation purposes only.
Write-Host "`n🔍 REPLICATION VERIFICATION" -ForegroundColor Green
Write-Host ("="*70) -ForegroundColor Green

# 1. Check replica is in recovery mode (standby)
Write-Host "`n[1/6] Replica Status:" -ForegroundColor Cyan
$recovery = docker exec postgres-replica psql -U admin -d postgres -t -c "SELECT pg_is_in_recovery();"
if ($recovery -match "t") {
    Write-Host "✅ Replica is in standby mode (read-only)" -ForegroundColor Green
} else {
    Write-Host "❌ Replica is NOT in standby mode" -ForegroundColor Red
}

# 2. Check primary has active replication connection
Write-Host "`n[2/6] Primary Replication Status:" -ForegroundColor Cyan
docker exec postgres-primary psql -U admin -d postgres -c "
SELECT
    application_name,
    client_addr,
    state,
    sync_state,
    pg_size_pretty(pg_wal_lsn_diff(pg_current_wal_lsn(), sent_lsn)) as lag
FROM pg_stat_replication;
"

# 3. Test data synchronization
Write-Host "`n[3/6] Testing Data Synchronization:" -ForegroundColor Cyan

# Insert test data on primary
Write-Host "    📝 Inserting test data on PRIMARY..." -ForegroundColor White
docker exec postgres-primary psql -U admin -d urlshortener -c "
INSERT INTO urls (url, short_url, created_by, status)
VALUES ('https://replication-test-$(Get-Date -Format 'HHmmss').com', 'REPTEST', 'verification', 'active')
ON CONFLICT (short_url) DO UPDATE SET url = EXCLUDED.url;
" 2>&1 | Out-Null

Write-Host "    ⏳ Waiting 2 seconds for replication..." -ForegroundColor Yellow
Start-Sleep -Seconds 2

# Check on replica
Write-Host "    🔍 Checking data on REPLICA..." -ForegroundColor White
$replicaData = docker exec postgres-replica psql -U admin -d urlshortener -t -c "SELECT COUNT(*) FROM urls WHERE short_url='REPTEST';"
if ($replicaData.Trim() -gt "0") {
    Write-Host "    ✅ Data successfully replicated to standby!" -ForegroundColor Green
} else {
    Write-Host "    ⚠️ Data not found on replica" -ForegroundColor Yellow
}

# 4. Compare counts
Write-Host "`n[4/6] Database Synchronization:" -ForegroundColor Cyan
$primaryCount = docker exec postgres-primary psql -U admin -d urlshortener -t -c "SELECT COUNT(*) FROM urls;"
$replicaCount = docker exec postgres-replica psql -U admin -d urlshortener -t -c "SELECT COUNT(*) FROM urls;"

Write-Host "    PRIMARY: $($primaryCount.Trim()) URLs" -ForegroundColor White
Write-Host "    REPLICA: $($replicaCount.Trim()) URLs" -ForegroundColor White

if ($primaryCount.Trim() -eq $replicaCount.Trim()) {
    Write-Host "    ✅ Databases perfectly synchronized!" -ForegroundColor Green
} else {
    Write-Host "    ⚠️ Counts differ (possible lag)" -ForegroundColor Yellow
}

# 5. Check replication slot
Write-Host "`n[5/6] Replication Slot Status:" -ForegroundColor Cyan
docker exec postgres-primary psql -U admin -d postgres -c "
SELECT
    slot_name,
    slot_type,
    active,
    pg_size_pretty(pg_wal_lsn_diff(pg_current_wal_lsn(), restart_lsn)) as lag
FROM pg_replication_slots;
"

# 6. Test read-only enforcement on replica
Write-Host "`n[6/6] Testing Read-Only Enforcement:" -ForegroundColor Cyan
Write-Host "    🔒 Attempting write on replica (should fail)..." -ForegroundColor White
$writeTest = docker exec postgres-replica psql -U admin -d urlshortener -c "
INSERT INTO urls (url, short_url, created_by, status)
VALUES ('https://should-fail.com', 'FAIL', 'test', 'active');
" 2>&1

if ($writeTest -match "read-only|cannot execute") {
    Write-Host "    ✅ Replica correctly rejects writes!" -ForegroundColor Green
} else {
    Write-Host "    ⚠️ Unexpected result" -ForegroundColor Yellow
}

Write-Host "`n" + ("="*70) -ForegroundColor Green
Write-Host "✅ REPLICATION IS WORKING!" -ForegroundColor Green
Write-Host ("="*70) -ForegroundColor Green

Write-Host "`n📊 Service Status:" -ForegroundColor Cyan
docker compose ps


kubectl port-forward -n monitoring svc/grafana 3000:3000

