# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: ledger_service/app/schemas/ledger.py

from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Optional
from pydantic import BaseModel


class EventType(str, Enum):
    PAYMENT_AUTHORIZED   = "payment.authorized"
    PAYMENT_CAPTURED     = "payment.captured"
    PAYMENT_REFUNDED     = "payment.refunded"
    PAYMENT_VOIDED       = "payment.voided"
    FEE_COLLECTED        = "fee.collected"
    PAYOUT_INITIATED     = "payout.initiated"


class EntryType(str, Enum):
    DEBIT  = "debit"
    CREDIT = "credit"


# ── Request Schemas ──────────────────────────────────────────────────────────

class RecordAuthorizationRequest(BaseModel):
    payment_id:  str
    merchant_id: str
    amount:      int       # cents
    currency:    str = "usd"
    description: Optional[str] = None
    metadata:    Optional[dict] = None


class RecordCaptureRequest(BaseModel):
    payment_id:      str
    merchant_id:     str
    amount:          int
    currency:        str = "usd"
    platform_fee:    Optional[int] = None   # None = auto-calculate
    description:     Optional[str] = None
    metadata:        Optional[dict] = None


class RecordRefundRequest(BaseModel):
    payment_id:  str
    merchant_id: str
    amount:      int
    currency:    str = "usd"
    reason:      Optional[str] = None
    metadata:    Optional[dict] = None


class RecordVoidRequest(BaseModel):
    payment_id:  str
    merchant_id: str
    amount:      int
    currency:    str = "usd"
    metadata:    Optional[dict] = None


# ── Response Schemas ─────────────────────────────────────────────────────────

class AccountResponse(BaseModel):
    id:                str
    owner_id:          str
    owner_type:        str
    account_type:      str
    currency:          str
    balance:           Decimal
    available_balance: Decimal
    pending_balance:   Decimal
    description:       Optional[str]
    created_at:        datetime
    updated_at:        datetime

    class Config:
        from_attributes = True


class LedgerEntryResponse(BaseModel):
    id:             str
    transaction_id: str
    account_id:     str
    payment_id:     str
    merchant_id:    str
    entry_type:     str
    event_type:     str
    amount:         Decimal
    currency:       str
    balance_after:  Decimal
    description:    Optional[str]
    created_at:     datetime

    class Config:
        from_attributes = True


class LedgerTransactionResponse(BaseModel):
    id:          str
    payment_id:  str
    merchant_id: str
    event_type:  str
    amount:      Decimal
    currency:    str
    status:      str
    description: Optional[str]
    entries:     list[LedgerEntryResponse] = []
    created_at:  datetime

    class Config:
        from_attributes = True


class BalanceSummary(BaseModel):
    merchant_id:       str
    currency:          str
    available_balance: Decimal
    pending_balance:   Decimal
    total_balance:     Decimal
    total_earned:      Decimal
    total_fees_paid:   Decimal
    total_refunded:    Decimal


class PlatformSummary(BaseModel):
    currency:          str
    total_volume:      Decimal
    total_fees:        Decimal
    escrow_balance:    Decimal
    total_refunds:     Decimal
    net_revenue:       Decimal
