# Code Generated by Sidekick is for learning and experimentation purposes only.

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import httpx
from config import get_settings
from templates.email_templates import get_template

logger = logging.getLogger(__name__)
settings = get_settings()


class EmailChannel:
    """
    Production:  sends via SendGrid Web API
    Mock (dev):  logs the email to stdout — no external calls
    """

    async def send(
        self,
        recipient:   str,
        event:       str,
        context:     dict,
    ) -> tuple[bool, str | None]:
        """
        Returns (success: bool, error: str | None)
        """
        template = get_template(event, context)

        if settings.MOCK_EMAIL:
            return await self._mock_send(recipient, template)

        if settings.SENDGRID_API_KEY:
            return await self._sendgrid_send(recipient, template)

        return await self._smtp_send(recipient, template)

    # ── Mock ──────────────────────────────────────────────────────────────────
    async def _mock_send(self, recipient: str, template) -> tuple[bool, str | None]:
        logger.info(
            "[EMAIL MOCK] to=%s subject='%s' body_len=%d",
            recipient, template.subject, len(template.text),
        )
        return True, None

    # ── SendGrid ──────────────────────────────────────────────────────────────
    async def _sendgrid_send(self, recipient: str, template) -> tuple[bool, str | None]:
        payload = {
            "personalizations": [{"to": [{"email": recipient}]}],
            "from": {
                "email": settings.SENDGRID_FROM_EMAIL,
                "name":  settings.SENDGRID_FROM_NAME,
            },
            "subject": template.subject,
            "content": [
                {"type": "text/plain", "value": template.text},
                {"type": "text/html",  "value": template.html},
            ],
        }
        try:
            async with httpx.AsyncClient(timeout=10) as client:
                resp = await client.post(
                    "https://api.sendgrid.com/v3/mail/send",
                    json=payload,
                    headers={"Authorization": f"Bearer {settings.SENDGRID_API_KEY}"},
                )
                if resp.status_code in (200, 202):
                    return True, None
                return False, f"SendGrid HTTP {resp.status_code}: {resp.text}"
        except Exception as exc: # noqa: BLE001
            return False, str(exc)

    # ── SMTP fallback ─────────────────────────────────────────────────────────
    async def _smtp_send(self, recipient: str, template) -> tuple[bool, str | None]:
        try:
            msg = MIMEMultipart("alternative")
            msg["Subject"] = template.subject
            msg["From"]    = settings.SENDGRID_FROM_EMAIL
            msg["To"]      = recipient
            msg.attach(MIMEText(template.text, "plain"))
            msg.attach(MIMEText(template.html, "html"))

            with smtplib.SMTP("localhost", 25, timeout=10) as server:
                server.sendmail(settings.SENDGRID_FROM_EMAIL, [recipient], msg.as_string())
            return True, None
        except Exception as exc: # noqa: BLE001
            return False, str(exc)
