# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: notification-service/channels/sms_channel.py

import logging

import httpx
from config import get_settings

logger = logging.getLogger(__name__)
settings = get_settings()

SMS_TEMPLATES: dict[str, str] = {
    "payment.authorized": "Your payment of ${amount} {currency} has been authorized. Ref: {payment_id}",
    "payment.captured":   "Payment confirmed: ${amount} {currency} processed. Ref: {payment_id}",
    "payment.failed":     "Payment of ${amount} {currency} failed: {failure_reason}. Ref: {payment_id}",
    "payment.refunded":   "Refund of ${refund_amount} {currency} processed. Ref: {payment_id}",
    "payment.voided":     "Payment {payment_id} voided. No charge made.",
    "fraud.detected":     "SECURITY ALERT: Suspicious activity on payment {payment_id} blocked. Contact support if unexpected.",
}


class SMSChannel:
    """
    Production:  sends via Twilio REST API
    Mock (dev):  logs message to stdout
    """

    def _render(self, event: str, context: dict) -> str:
        template = SMS_TEMPLATES.get(event, "Payment update on {payment_id}: " + event)
        ctx = {
            "amount":         f"{context.get('amount', 0):.2f}",
            "refund_amount":  f"{context.get('refund_amount', context.get('amount', 0)):.2f}",
            "currency":       context.get("currency", "USD").upper(),
            "payment_id":     context.get("payment_id", ""),
            "failure_reason": context.get("failure_reason", "unknown error"),
        }
        return template.format(**ctx)

    async def send(
        self,
        phone:   str,
        event:   str,
        context: dict,
    ) -> tuple[bool, str | None]:
        body = self._render(event, context)

        if settings.MOCK_SMS:
            return await self._mock_send(phone, body)

        return await self._twilio_send(phone, body)

    async def _mock_send(self, phone: str, body: str) -> tuple[bool, str | None]:
        logger.info("[SMS MOCK] to=%s body='%s'", phone, body)
        return True, None

    async def _twilio_send(self, phone: str, body: str) -> tuple[bool, str | None]:
        if not all([settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN, settings.TWILIO_FROM_NUMBER]):
            return False, "Twilio credentials not configured"
        try:
            url = f"https://api.twilio.com/2010-04-01/Accounts/{settings.TWILIO_ACCOUNT_SID}/Messages.json"
            async with httpx.AsyncClient(timeout=10) as client:
                resp = await client.post(
                    url,
                    data={"From": settings.TWILIO_FROM_NUMBER, "To": phone, "Body": body},
                    auth=(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN),
                )
                data = resp.json()
                if resp.status_code == 201:
                    return True, None
                return False, f"Twilio error: {data.get('message', resp.text)}"
        except Exception as exc: # noqa: BLE001
            return False, str(exc)
