# Code Generated by Sidekick is for learning and experimentation purposes only.

import asyncio
import hashlib
import hmac
import json
import logging
import time
from datetime import UTC, datetime, timedelta

import httpx
from config import get_settings
from models import DeliveryStatus, MerchantWebhook, WebhookDelivery
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

logger = logging.getLogger(__name__)
settings = get_settings()


def _sign_payload(secret: str, payload_bytes: bytes, timestamp: int) -> str:
    """HMAC-SHA256 signature — same pattern as Stripe webhook signing."""
    signed_content = f"{timestamp}.".encode() + payload_bytes
    return hmac.new(secret.encode(), signed_content, hashlib.sha256).hexdigest()


class WebhookChannel:

    async def dispatch(
        self,
        db:         AsyncSession,
        merchant_id: str,
        event:       str,
        payment_id:  str,
        payload:     dict,
    ) -> list[WebhookDelivery]:
        """Find active webhooks for merchant+event, fire all, return delivery records."""
        result = await db.execute(
            select(MerchantWebhook).where(
                MerchantWebhook.merchant_id == merchant_id,
                MerchantWebhook.is_active.is_(True),
            ),
        )
        webhooks = result.scalars().all()

        deliveries = []
        for wh in webhooks:
            subscribed = wh.events.split(",") if wh.events != "*" else ["*"]
            if "*" not in subscribed and event not in subscribed:
                continue

            delivery = WebhookDelivery(
                webhook_id  = wh.id,
                payment_id  = payment_id,
                event       = event,
                status      = DeliveryStatus.PENDING,
                payload     = payload,
            )
            db.add(delivery)
            await db.flush()   # get delivery.id before background task

            deliveries.append(delivery)
            asyncio.create_task(
                self._deliver_with_retry(db, wh, delivery, payload),
            )

        await db.commit()
        return deliveries

    async def _deliver_with_retry(
        self,
        db:       AsyncSession,
        webhook:  MerchantWebhook,
        delivery: WebhookDelivery,
        payload:  dict,
    ):
        for attempt in range(settings.WEBHOOK_MAX_RETRIES):
            success, http_status, response_body, error = await self._post(
                webhook.url, webhook.secret, payload,
            )
            now = datetime.now(UTC)

            delivery.attempts   = attempt + 1
            delivery.http_status = http_status
            delivery.response_body = response_body[:500] if response_body else None
            delivery.error      = error

            if success:
                delivery.status       = DeliveryStatus.SENT
                delivery.delivered_at = now
                webhook.total_deliveries += 1
                logger.info("[WEBHOOK] ✓ delivered event=%s wh=%s attempt=%d", delivery.event, webhook.id, attempt + 1)
                break
            webhook.failed_deliveries += 1
            if attempt < settings.WEBHOOK_MAX_RETRIES - 1:
                delay = settings.WEBHOOK_RETRY_DELAYS[attempt]
                delivery.status       = DeliveryStatus.RETRYING
                delivery.next_retry_at = now + timedelta(seconds=delay)
                logger.warning("[WEBHOOK] ✗ attempt %d failed, retrying in %ds event=%s wh=%s",
                               attempt + 1, delay, delivery.event, webhook.id)
                try:
                    await db.commit()
                except Exception:
                    logger.warning("DB commit failed during webhook retry, continuing", exc_info=True)
                    await asyncio.sleep(delay)
            else:
                delivery.status = DeliveryStatus.FAILED
                logger.error("[WEBHOOK] ✗ all attempts exhausted event=%s wh=%s", delivery.event, webhook.id)

        try:
            await db.commit()
        except Exception as exc:
            logger.exception("Webhook delivery DB commit failed: %s", exc)

    async def _post(
        self, url: str, secret: str, payload: dict,
    ) -> tuple[bool, int | None, str | None, str | None]:
        ts = int(time.time())
        body_bytes = json.dumps(payload, default=str).encode()
        signature = _sign_payload(secret, body_bytes, ts)

        headers = {
            "Content-Type":              "application/json",
            "X-Payment-Signature":       f"t={ts},v1={signature}",
            "X-Payment-Event":           payload.get("event", ""),
            "X-Payment-Delivery-Id":     payload.get("delivery_id", ""),
            "User-Agent":                "PaymentGateway-Webhooks/1.0",
        }
        try:
            async with httpx.AsyncClient(timeout=settings.WEBHOOK_TIMEOUT_SECONDS) as client:
                resp = await client.post(url, content=body_bytes, headers=headers)
                success = 200 <= resp.status_code < 300
                return success, resp.status_code, resp.text, None if success else f"HTTP {resp.status_code}"
        except httpx.TimeoutException:
            return False, None, None, "Request timed out"
        except Exception as exc: # noqa: BLE001
            return False, None, None, str(exc)
