# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: ledger_service/app/services/entry_service.py

import logging
import uuid
from decimal import Decimal, ROUND_HALF_UP

from sqlalchemy.orm import Session
from fastapi import HTTPException

from ledger_service.app.config import settings
from ledger_service.app.models.ledger import Account, LedgerEntry, LedgerTransaction
from ledger_service.app.services.account_service import (
    get_or_create_account,
    get_merchant_account_id,
)

logger = logging.getLogger(__name__)


def cents_to_decimal(cents: int) -> Decimal:
    return Decimal(str(cents)) / Decimal("100")


def calculate_platform_fee(amount_cents: int) -> int:
    """Calculate platform fee in cents"""
    fee = Decimal(str(amount_cents)) * Decimal(str(settings.platform_fee_percent)) / Decimal("100")
    return int(fee.quantize(Decimal("1"), rounding=ROUND_HALF_UP))


def _create_entry(
    db: Session,
    transaction_id: str,
    account: Account,
    payment_id: str,
    merchant_id: str,
    entry_type: str,
    event_type: str,
    amount: Decimal,
    currency: str,
    description: str = None,
    metadata: dict = None,
) -> LedgerEntry:
    """
    Create one ledger entry and update account balance.
    NEVER call this directly - always use record_* functions.
    """
    if entry_type == "debit":
        account.balance += amount
        account.available_balance += amount
    else:
        account.balance -= amount
        account.available_balance -= amount

    entry = LedgerEntry(
        id=f"le_{uuid.uuid4().hex}",
        transaction_id=transaction_id,
        account_id=account.id,
        payment_id=payment_id,
        merchant_id=merchant_id,
        entry_type=entry_type,
        event_type=event_type,
        amount=amount,
        currency=currency,
        balance_after=account.balance,
        description=description,
        metadata=metadata or {},
    )
    db.add(entry)
    return entry


def record_authorization(
    db: Session,
    payment_id: str,
    merchant_id: str,
    amount_cents: int,
    currency: str = "usd",
    metadata: dict = None,
) -> LedgerTransaction:
    """
    Record payment authorization.
    
    Funds are held (in escrow / pending) but not yet settled.
    
    Entries:
      DEBIT  escrow_account     +amount  (money arriving)
      CREDIT merchant_pending   -amount  (merchant has pending income)
    
    Real world:
      Customer authorizes $100 on card
      $100 held on card (not charged yet)
      Escrow shows $100 pending
    """
    amount = cents_to_decimal(amount_cents)
    tx_id = f"ltx_{uuid.uuid4().hex[:18]}"

    # Check no duplicate
    existing = db.query(LedgerTransaction).filter(
        LedgerTransaction.payment_id == payment_id,
        LedgerTransaction.event_type == "payment.authorized",
    ).first()
    if existing:
        logger.info(f"Authorization already recorded: {payment_id}")
        return existing

    merchant_acct_id = get_merchant_account_id(merchant_id, currency)

    escrow_account = get_or_create_account(
        db, settings.escrow_account_id, "platform", "platform", "liability", currency
    )
    merchant_account = get_or_create_account(
        db, merchant_acct_id, merchant_id, "merchant", "asset", currency,
        description=f"Merchant account for {merchant_id}"
    )

    # DEBIT escrow (money coming in to platform holding)
    _create_entry(
        db, tx_id, escrow_account, payment_id, merchant_id,
        "debit", "payment.authorized", amount, currency,
        description=f"Authorization hold: payment {payment_id}",
        metadata=metadata,
    )

    # CREDIT merchant pending (merchant has money coming)
    merchant_account.pending_balance += amount

    tx = LedgerTransaction(
        id=tx_id,
        payment_id=payment_id,
        merchant_id=merchant_id,
        event_type="payment.authorized",
        amount=amount,
        currency=currency,
        status="posted",
        description=f"Payment authorization: {payment_id}",
        metadata=metadata or {},
    )
    db.add(tx)
    db.commit()

    logger.info(f"Authorization recorded: payment={payment_id} amount={amount} {currency}")
    return tx


def record_capture(
    db: Session,
    payment_id: str,
    merchant_id: str,
    amount_cents: int,
    currency: str = "usd",
    platform_fee_cents: int = None,
    metadata: dict = None,
) -> LedgerTransaction:
    """
    Record payment capture.
    
    Money moves from escrow to merchant (minus platform fee).
    
    Entries:
      CREDIT escrow_account     -amount          (money leaving escrow)
      DEBIT  merchant_account   +(amount-fee)    (merchant gets paid)
      DEBIT  fee_account        +fee             (platform keeps fee)
    
    Real world:
      $100 captured
      Stripe takes $3 (their fee)
      You take $2.50 (your platform fee)
      Merchant gets $94.50
    """
    amount = cents_to_decimal(amount_cents)

    if platform_fee_cents is None:
        platform_fee_cents = calculate_platform_fee(amount_cents)

    platform_fee = cents_to_decimal(platform_fee_cents)
    merchant_net = amount - platform_fee

    tx_id = f"ltx_{uuid.uuid4().hex[:18]}"

    existing = db.query(LedgerTransaction).filter(
        LedgerTransaction.payment_id == payment_id,
        LedgerTransaction.event_type == "payment.captured",
    ).first()
    if existing:
        logger.info(f"Capture already recorded: {payment_id}")
        return existing

    merchant_acct_id = get_merchant_account_id(merchant_id, currency)

    escrow_account = get_or_create_account(
        db, settings.escrow_account_id, "platform", "platform", "liability", currency
    )
    merchant_account = get_or_create_account(
        db, merchant_acct_id, merchant_id, "merchant", "asset", currency,
        description=f"Merchant account for {merchant_id}"
    )
    fee_account = get_or_create_account(
        db, settings.fee_account_id, "platform", "platform", "revenue", currency
    )

    # CREDIT escrow (money leaving escrow)
    _create_entry(
        db, tx_id, escrow_account, payment_id, merchant_id,
        "credit", "payment.captured", amount, currency,
        description=f"Capture settlement: payment {payment_id}",
    )

    # DEBIT merchant account (merchant receives net amount)
    _create_entry(
        db, tx_id, merchant_account, payment_id, merchant_id,
        "debit", "payment.captured", merchant_net, currency,
        description=f"Net payment to merchant: {payment_id}",
        metadata={"gross": str(amount), "fee": str(platform_fee)},
    )

    # DEBIT fee account (platform collects fee)
    _create_entry(
        db, tx_id, fee_account, payment_id, merchant_id,
        "debit", "fee.collected", platform_fee, currency,
        description=f"Platform fee {settings.platform_fee_percent}%: payment {payment_id}",
    )

    # Clear merchant pending balance
    merchant_account.pending_balance = max(
        Decimal("0"),
        merchant_account.pending_balance - amount
    )

    tx = LedgerTransaction(
        id=tx_id,
        payment_id=payment_id,
        merchant_id=merchant_id,
        event_type="payment.captured",
        amount=amount,
        currency=currency,
        status="posted",
        description=f"Payment captured: {payment_id}",
        metadata={
            "gross_amount": str(amount),
            "platform_fee": str(platform_fee),
            "merchant_net": str(merchant_net),
            **(metadata or {}),
        },
    )
    db.add(tx)
    db.commit()

    logger.info(
        f"Capture recorded: payment={payment_id} "
        f"amount={amount} fee={platform_fee} net={merchant_net} {currency}"
    )
    return tx


def record_refund(
    db: Session,
    payment_id: str,
    merchant_id: str,
    amount_cents: int,
    currency: str = "usd",
    reason: str = None,
    metadata: dict = None,
) -> LedgerTransaction:
    """
    Record a refund.
    
    Money moves from merchant back to customer (via escrow).
    Platform fee is partially returned (fair refund practice).
    
    Entries:
      CREDIT merchant_account  -refund_amount    (deducted from merchant)
      DEBIT  escrow_account    +refund_amount    (back in escrow for return)
    
    Real world:
      Customer refunded $50
      Merchant balance reduced by $50
      Escrow holds $50 to return to customer
    """
    amount = cents_to_decimal(amount_cents)
    tx_id = f"ltx_{uuid.uuid4().hex[:18]}"

    merchant_acct_id = get_merchant_account_id(merchant_id, currency)

    escrow_account = get_or_create_account(
        db, settings.escrow_account_id, "platform", "platform", "liability", currency
    )
    merchant_account = get_or_create_account(
        db, merchant_acct_id, merchant_id, "merchant", "asset", currency,
    )

    # CREDIT merchant account (money taken back from merchant)
    _create_entry(
        db, tx_id, merchant_account, payment_id, merchant_id,
        "credit", "payment.refunded", amount, currency,
        description=f"Refund deduction: payment {payment_id} reason={reason or 'N/A'}",
        metadata=metadata,
    )

    # DEBIT escrow (money goes back to escrow for return to customer)
    _create_entry(
        db, tx_id, escrow_account, payment_id, merchant_id,
        "debit", "payment.refunded", amount, currency,
        description=f"Refund to customer: payment {payment_id}",
    )

    tx = LedgerTransaction(
        id=tx_id,
        payment_id=payment_id,
        merchant_id=merchant_id,
        event_type="payment.refunded",
        amount=amount,
        currency=currency,
        status="posted",
        description=f"Refund: {payment_id} reason={reason or 'N/A'}",
        metadata=metadata or {},
    )
    db.add(tx)
    db.commit()

    logger.info(f"Refund recorded: payment={payment_id} amount={amount} {currency}")
    return tx


def record_void(
    db: Session,
    payment_id: str,
    merchant_id: str,
    amount_cents: int,
    currency: str = "usd",
    metadata: dict = None,
) -> LedgerTransaction:
    """
    Record a void (reversal of authorization before capture).
    
    Money was never captured so just reverse the escrow hold.
    
    Entries:
      CREDIT escrow_account     -amount  (release the hold)
    
    Real world:
      $100 was authorized but never captured
      Void releases the $100 hold on customer card
      Escrow reduced by $100
    """
    amount = cents_to_decimal(amount_cents)
    tx_id = f"ltx_{uuid.uuid4().hex[:18]}"

    existing = db.query(LedgerTransaction).filter(
        LedgerTransaction.payment_id == payment_id,
        LedgerTransaction.event_type == "payment.voided",
    ).first()
    if existing:
        logger.info(f"Void already recorded: {payment_id}")
        return existing

    merchant_acct_id = get_merchant_account_id(merchant_id, currency)

    escrow_account = get_or_create_account(
        db, settings.escrow_account_id, "platform", "platform", "liability", currency
    )
    merchant_account = get_or_create_account(
        db, merchant_acct_id, merchant_id, "merchant", "asset", currency,
    )

    # CREDIT escrow (release the hold - authorization cancelled)
    _create_entry(
        db, tx_id, escrow_account, payment_id, merchant_id,
        "credit", "payment.voided", amount, currency,
        description=f"Void: release authorization hold {payment_id}",
        metadata=metadata,
    )

    # Clear merchant pending balance
    merchant_account.pending_balance = max(
        Decimal("0"),
        merchant_account.pending_balance - amount
    )

    tx = LedgerTransaction(
        id=tx_id,
        payment_id=payment_id,
        merchant_id=merchant_id,
        event_type="payment.voided",
        amount=amount,
        currency=currency,
        status="posted",
        description=f"Payment voided: {payment_id}",
        metadata=metadata or {},
    )
    db.add(tx)
    db.commit()

    logger.info(f"Void recorded: payment={payment_id} amount={amount} {currency}")
    return tx
