# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: RECON-04-UpdateSchedule.ps1

$url = "http://localhost:8009/reconcile/schedule"

# ✏ Change hour/minute/timezone to whatever your team needs
$body = @{
    enabled  = $true
    hour     = 23           # 11 PM
    minute   = 0
    timezone = "America/New_York"
    limit    = 500
} | ConvertTo-Json

Write-Host "`n► PUT $url" -ForegroundColor Yellow
try {
    $r = Invoke-RestMethod -Uri $url -Method PUT -Body $body -ContentType "application/json"
    Write-Host "✓ Schedule updated" -ForegroundColor Green
    Write-Host "  Next Run : $($r.schedule.next_run)"   -ForegroundColor White
    Write-Host "  Enabled  : $($r.schedule.enabled)"    -ForegroundColor White
    $r | ConvertTo-Json -Depth 4

    # ── Also test pause / resume ──────────────────────────────────────────────
    Write-Host "`n► POST /reconcile/schedule/pause" -ForegroundColor Yellow
    $p = Invoke-RestMethod -Uri "http://localhost:8009/reconcile/schedule/pause" -Method POST
    Write-Host "  Paused: $($p.schedule.enabled)" -ForegroundColor Yellow

    Start-Sleep -Seconds 2

    Write-Host "`n► POST /reconcile/schedule/resume" -ForegroundColor Yellow
    $res = Invoke-RestMethod -Uri "http://localhost:8009/reconcile/schedule/resume" -Method POST
    Write-Host "  Resumed: $($res.schedule.enabled)" -ForegroundColor Green
    Write-Host "  Next Run: $($res.schedule.next_run)" -ForegroundColor White
} catch {
    Write-Host "✗ Failed: $($_.ErrorDetails.Message)" -ForegroundColor Red
}
