# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: RECON-06-GetByRunId.ps1

$RUN_ID = Get-Content "$PSScriptRoot/recon_run_id.txt" -ErrorAction Stop
$url    = "http://localhost:8009/reconcile/results/$RUN_ID"

Write-Host "`n► GET $url" -ForegroundColor Yellow
try {
    $r = Invoke-RestMethod -Uri $url -Method GET
    Write-Host "✓ Run retrieved" -ForegroundColor Green
    Write-Host "  Run ID        : $($r.run_id)"              -ForegroundColor Cyan
    Write-Host "  Trigger       : $($r.trigger)"             -ForegroundColor White
    Write-Host "  Status        : $($r.status)"              -ForegroundColor White
    Write-Host "  Total         : $($r.total_payments)"      -ForegroundColor White
    Write-Host "  Reconciled    : $($r.reconciled)"          -ForegroundColor Green
    Write-Host "  Discrepancies : $($r.discrepancies_found)" -ForegroundColor Red

    Write-Host "`n── PAYMENT BREAKDOWN ───────────────────────────" -ForegroundColor Cyan
    foreach ($p in $r.payments) {
        $icon = if ($p.is_reconciled) { "✓" } else { "✗" }
        $col  = if ($p.is_reconciled) { "Green" } else { "Red" }
        Write-Host "  $icon [$($p.gateway_status)] $($p.payment_id)" -ForegroundColor $col
        foreach ($d in $p.discrepancies) {
            Write-Host "      [$($d.layer)][$($d.severity)] $($d.type)" -ForegroundColor DarkRed
            Write-Host "      $($d.message)"                            -ForegroundColor DarkRed
        }
    }

    Write-Host "`n── SUMMARY ─────────────────────────────────────" -ForegroundColor Cyan
    $r.summary | ConvertTo-Json
} catch {
    Write-Host "✗ Failed: $_" -ForegroundColor Red
}
