# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: RECON-07-SinglePayment.ps1

$PAYMENT_ID = if (Test-Path "$PSScriptRoot/auth_payment_id.txt") {
    Get-Content "$PSScriptRoot/auth_payment_id.txt"
} else {
    Read-Host "Enter Payment ID"
}

$url = "http://localhost:8009/reconcile/payment/$PAYMENT_ID"

Write-Host "`n► GET $url" -ForegroundColor Yellow
Write-Host "  Payment: $PAYMENT_ID" -ForegroundColor Cyan
try {
    $r    = Invoke-RestMethod -Uri $url -Method GET
    $icon = if ($r.is_reconciled) { "✓" } else { "✗" }
    $col  = if ($r.is_reconciled) { "Green" } else { "Red" }

    Write-Host "`n$icon $PAYMENT_ID" -ForegroundColor $col
    Write-Host "── LAYER COMPARISON ──────────────────────────────" -ForegroundColor Cyan
    Write-Host "  Gateway  : amount=$($r.gateway_amount)  status=$($r.gateway_status)"  -ForegroundColor White
    Write-Host "  Ledger   : amount=$($r.ledger_amount)   entries=$($r.ledger_entries)" -ForegroundColor White
    Write-Host "  Bank     : amount=$($r.bank_amount)     status=$($r.bank_status)"     -ForegroundColor White
    Write-Host "  Merchant : amount=$($r.merchant_amount) status=$($r.merchant_status)" -ForegroundColor White

    if ($r.discrepancies.Count -gt 0) {
        Write-Host "`n── DISCREPANCIES ($($r.discrepancies.Count)) ──────────────────" -ForegroundColor Red
        foreach ($d in $r.discrepancies) {
            Write-Host "  [$($d.layer)][$($d.severity)] $($d.type)" -ForegroundColor Red
            Write-Host "    Expected : $($d.expected)"              -ForegroundColor DarkRed
            Write-Host "    Actual   : $($d.actual)"                -ForegroundColor DarkRed
            Write-Host "    $($d.message)"                          -ForegroundColor DarkRed
        }
    } else {
        Write-Host "`n  ✓ Fully reconciled across all 4 layers" -ForegroundColor Green
    }
} catch {
    Write-Host "✗ Failed: $($_.ErrorDetails.Message)" -ForegroundColor Red
}
