# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: RECON-09-Stats.ps1

$url = "http://localhost:8009/reconcile/stats"

Write-Host "`n► GET $url" -ForegroundColor Yellow
try {
    $r = Invoke-RestMethod -Uri $url -Method GET
    Write-Host "✓ Stats retrieved" -ForegroundColor Green
    Write-Host "`n── RUNS ─────────────────────────────────────────" -ForegroundColor Cyan
    Write-Host "  Total Runs     : $($r.total_runs)"          -ForegroundColor White
    Write-Host "  Completed Runs : $($r.completed_runs)"      -ForegroundColor White
    Write-Host "  Discrepancies  : $($r.total_discrepancies)"  -ForegroundColor Red

    Write-Host "`n── DISCREPANCIES BY LAYER ───────────────────────" -ForegroundColor Cyan
    $r.discrepancies_by_layer | ConvertTo-Json

    Write-Host "`n── DISCREPANCIES BY TYPE ────────────────────────" -ForegroundColor Cyan
    $r.discrepancies_by_type | ConvertTo-Json

    Write-Host "`n── DISCREPANCIES BY SEVERITY ────────────────────" -ForegroundColor Cyan
    $r.discrepancies_by_severity | ConvertTo-Json

    Write-Host "`n── SCHEDULER ────────────────────────────────────" -ForegroundColor Cyan
    Write-Host "  Enabled          : $($r.scheduler.enabled)"              -ForegroundColor White
    Write-Host "  Next Run         : $($r.scheduler.next_run)"             -ForegroundColor White
    Write-Host "  Total Scheduled  : $($r.scheduler.total_scheduled_runs)" -ForegroundColor White
} catch {
    Write-Host "✗ Failed: $_" -ForegroundColor Red
}
