# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: app/observability/dependency_probes.py
import asyncio
import logging

from sqlalchemy import text
from sqlalchemy.orm import Session

from app.database import engine
from app.lock_service import redis_client
from app.observability.slo_metrics import record_dependency_probe

logger = logging.getLogger("booking-api")


async def dependency_probe_loop(interval_seconds: int = 30) -> None:
    while True:
        redis_ok = True
        postgres_ok = True

        try:
            redis_client.ping()
        except Exception as exc:
            redis_ok = False
            logger.warning("redis_probe_failed error=%s", exc)

        try:
            with Session(bind=engine) as db:
                db.execute(text("SELECT 1"))
        except Exception as exc:
            postgres_ok = False
            logger.warning("postgres_probe_failed error=%s", exc)

        record_dependency_probe("redis", redis_ok)
        record_dependency_probe("postgres", postgres_ok)

        await asyncio.sleep(interval_seconds)
