# filename: app/observability/metrics_middleware.py
# Code Generated by Sidekick is for learning and experimentation purposes only.
import time

from fastapi import Request

from app.observability.metrics import (
    HTTP_REQUESTS_TOTAL,
    HTTP_REQUEST_LATENCY_SECONDS,
)


async def prometheus_http_middleware(request: Request, call_next):
    if request.url.path == "/metrics":
        return await call_next(request)

    started = time.perf_counter()
    response = await call_next(request)

    route = request.scope.get("route")
    endpoint = getattr(route, "path", request.url.path)

    HTTP_REQUESTS_TOTAL.labels(
        method=request.method,
        endpoint=endpoint,
        status_code=str(response.status_code),
    ).inc()

    HTTP_REQUEST_LATENCY_SECONDS.labels(
        method=request.method,
        endpoint=endpoint,
    ).observe(time.perf_counter() - started)

    return response
