# Code Generated by Sidekick is for learning and experimentation purposes only.

"""
HTTP client for the bank_connector microservice.
Replaces the old bank_gateway.py mock entirely.

bank_connector handles:
  - Stripe API calls
  - Retry logic with tenacity
  - Circuit breaker
  - Idempotency (prevents double charges)
  - Audit log (processor_transactions table)
"""

import logging
import os

import httpx

logger = logging.getLogger(__name__)

BANK_CONNECTOR_URL = os.getenv("BANK_CONNECTOR_URL", "http://bank-connector:8005")
TIMEOUT = 35  # slightly above Stripe's 30s timeout


async def call_bank_authorize(
    payment_id: str,
    amount: int,
    card,                           # Payment.schemas.payment.CardInfo
    merchant_id: str | None = None,
    idempotency_key: str | None = None,
    currency: str = "usd",
    description: str | None = None,
    metadata: dict | None = None,
) -> dict:
    """
    POST /authorize → bank_connector → Stripe PaymentIntent (capture_method=manual)
    Returns a dict compatible with existing endpoints.py access patterns.
    """
    payload = {
        "payment_id":      payment_id,
        "merchant_id":     merchant_id or "unknown",
        "amount":          amount,
        "currency":        currency,
        "card": {
            "number":    card.number,
            "exp_month": card.exp_month,
            "exp_year":  card.exp_year,
            "cvc":       card.cvc,
        },
        "idempotency_key": idempotency_key,
        "description":     description,
        "metadata":        metadata or {},
    }

    try:
        async with httpx.AsyncClient(timeout=TIMEOUT) as client:
            resp = await client.post(f"{BANK_CONNECTOR_URL}/authorize", json=payload)

        data = resp.json()

        # bank_connector raises 402 on card decline — parse detail
        if resp.status_code == 402:
            detail = data.get("detail", {})
            return {
                "success":      False,
                "decline_code": detail.get("decline_code"),
                "message":      detail.get("message", "Card declined"),
            }

        resp.raise_for_status()

        return {
            "success":            data.get("success", False),
            "authorization_code": data.get("authorization_code"),
            "processor_id":       data.get("processor_id"),    # Stripe PaymentIntent ID
            "card_last4":         data.get("card_last4"),
            "card_brand":         data.get("card_brand"),
            "decline_code":       data.get("decline_code"),
            "message":            data.get("failure_message"),
        }

    except httpx.TimeoutException:
        logger.exception(f"Bank connector timeout: authorize payment={payment_id}")
        return {"success": False, "decline_code": "timeout", "message": "Bank connector timed out"}
    except httpx.HTTPStatusError as e:
        logger.exception(f"Bank connector HTTP error: {e.response.status_code} payment={payment_id}")
        return {"success": False, "decline_code": "processor_error", "message": str(e)}
    except Exception as e:
        logger.exception(f"Bank connector error: authorize payment={payment_id} error={e}")
        return {"success": False, "decline_code": "processor_error", "message": str(e)}


async def call_bank_capture(
    payment_id: str,
    authorization_code: str,        # Stripe PaymentIntent ID stored as authorization_code
    amount: int,
    merchant_id: str | None = None,
    idempotency_key: str | None = None,
) -> dict:
    """
    POST /capture → bank_connector → stripe.PaymentIntent.capture()
    """
    payload = {
        "payment_id":         payment_id,
        "merchant_id":        merchant_id or "unknown",
        "processor_id":       authorization_code,   # Stripe PaymentIntent ID
        "authorization_code": authorization_code,
        "amount":             amount,
        "idempotency_key":    idempotency_key,
    }

    try:
        async with httpx.AsyncClient(timeout=TIMEOUT) as client:
            resp = await client.post(f"{BANK_CONNECTOR_URL}/capture", json=payload)
        resp.raise_for_status()
        data = resp.json()

        return {
            "success":           data.get("success", False),
            "capture_reference": data.get("capture_reference"),
            "message":           data.get("failure_message"),
        }

    except Exception as e:
        logger.exception(f"Bank connector error: capture payment={payment_id} error={e}")
        return {"success": False, "message": str(e)}


async def call_bank_void(
    payment_id: str,
    authorization_code: str,
    merchant_id: str | None = None,
    idempotency_key: str | None = None,
) -> dict:
    """
    POST /void → bank_connector → stripe.PaymentIntent.cancel()
    """
    payload = {
        "payment_id":         payment_id,
        "merchant_id":        merchant_id or "unknown",
        "processor_id":       authorization_code,
        "authorization_code": authorization_code,
        "idempotency_key":    idempotency_key,
    }

    try:
        async with httpx.AsyncClient(timeout=TIMEOUT) as client:
            resp = await client.post(f"{BANK_CONNECTOR_URL}/void", json=payload)
        resp.raise_for_status()
        data = resp.json()

        return {
            "success":        data.get("success", False),
            "void_reference": data.get("void_reference"),
            "message":        data.get("failure_message"),
        }

    except Exception as e:
        logger.exception(f"Bank connector error: void payment={payment_id} error={e}")
        return {"success": False, "message": str(e)}


async def call_bank_refund(
    payment_id: str,
    amount: int,
    processor_id: str | None = None,       # Stripe PaymentIntent ID
    merchant_id: str | None = None,
    reason: str | None = None,
    idempotency_key: str | None = None,
) -> dict:
    """
    POST /refund → bank_connector → stripe.Refund.create()
    """
    payload = {
        "payment_id":      payment_id,
        "merchant_id":     merchant_id or "unknown",
        "processor_id":    processor_id,
        "amount":          amount,
        "reason":          reason,
        "idempotency_key": idempotency_key,
    }

    try:
        async with httpx.AsyncClient(timeout=TIMEOUT) as client:
            resp = await client.post(f"{BANK_CONNECTOR_URL}/refund", json=payload)
        resp.raise_for_status()
        data = resp.json()

        return {
            "success":          data.get("success", False),
            "refund_reference": data.get("refund_reference"),
            "message":          data.get("failure_message"),
        }

    except Exception as e:
        logger.exception(f"Bank connector error: refund payment={payment_id} error={e}")
        return {"success": False, "message": str(e)}
