# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: Payment/services/bank_gateway.py

import asyncio
import random
import uuid

from Payment.schemas.payment import CardInfo


async def call_bank_authorize(payment_id: str, amount: int, card: CardInfo) -> dict:
    await asyncio.sleep(0.5)

    if random.random() < 0.9:
        return {
            "success": True,
            "authorization_code": f"AUTH_{uuid.uuid4().hex[:8].upper()}",
            "message": "Authorized",
        }

    return {
        "success": False,
        "decline_code": "insufficient_funds",
        "message": "Insufficient funds",
    }


async def call_bank_capture(payment_id: str, authorization_code: str, amount: int) -> dict:
    await asyncio.sleep(0.3)
    return {
        "success": True,
        "capture_reference": f"CAP_{uuid.uuid4().hex[:8].upper()}",
        "message": "Captured",
    }


async def call_bank_void(payment_id: str, authorization_code: str) -> dict:
    await asyncio.sleep(0.3)
    return {
        "success": True,
        "void_reference": f"VOID_{uuid.uuid4().hex[:8].upper()}",
        "message": "Voided",
    }


async def call_bank_refund(payment_id: str, amount: int) -> dict:
    await asyncio.sleep(0.3)
    return {
        "success": True,
        "refund_reference": f"REF_{uuid.uuid4().hex[:8].upper()}",
        "message": "Refunded",
    }
