# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: Payment/services/ledger_client.py

import logging
import os

import httpx

logger = logging.getLogger(__name__)

LEDGER_SERVICE_URL = os.getenv(
    "LEDGER_SERVICE_URL",
    "http://ledger-service:8007"
).rstrip("/")


async def notify_authorization(
    payment_id: str,
    merchant_id: str,
    amount: int,
    currency: str = "usd",
) -> bool:
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            response = await client.post(
                f"{LEDGER_SERVICE_URL}/record/authorization",
                json={
                    "payment_id": payment_id,
                    "merchant_id": merchant_id,
                    "amount": amount,
                    "currency": currency,
                },
            )
            return response.status_code == 200
    except Exception as e: # noqa: BLE001
        logger.warning(f"Ledger authorization notification failed: {e}")
        return False


async def notify_capture(
    payment_id: str,
    merchant_id: str,
    amount: int,
    currency: str = "usd",
) -> bool:
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            response = await client.post(
                f"{LEDGER_SERVICE_URL}/record/capture",
                json={
                    "payment_id": payment_id,
                    "merchant_id": merchant_id,
                    "amount": amount,
                    "currency": currency,
                },
            )
            return response.status_code == 200
    except Exception as e: # noqa: BLE001
        logger.warning(f"Ledger capture notification failed: {e}")
        return False


async def notify_refund(
    payment_id: str,
    merchant_id: str,
    amount: int,
    currency: str = "usd",
    reason: str | None = None,
) -> bool:
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            response = await client.post(
                f"{LEDGER_SERVICE_URL}/record/refund",
                json={
                    "payment_id": payment_id,
                    "merchant_id": merchant_id,
                    "amount": amount,
                    "currency": currency,
                    "reason": reason,
                },
            )
            return response.status_code == 200
    except Exception as e: # noqa: BLE001
        logger.warning(f"Ledger refund notification failed: {e}")
        return False


async def notify_void(
    payment_id: str,
    merchant_id: str,
    amount: int,
    currency: str = "usd",
) -> bool:
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            response = await client.post(
                f"{LEDGER_SERVICE_URL}/record/void",
                json={
                    "payment_id": payment_id,
                    "merchant_id": merchant_id,
                    "amount": amount,
                    "currency": currency,
                },
            )
            return response.status_code == 200
    except Exception as e: # noqa: BLE001
        logger.warning(f"Ledger void notification failed: {e}")
        return False