# Code Generated by Sidekick is for learning and experimentation purposes only.

import logging
from datetime import UTC, datetime

from fastapi import HTTPException, status
from sqlalchemy.orm import Session

from Payment.config.database import SessionLocal
from Payment.models.enums import PaymentStatus, TransactionType
from Payment.models.payment import Payment
from Payment.services.bank_gateway import call_bank_capture
from Payment.services.transaction_service import log_transaction

logger = logging.getLogger(__name__)


async def capture_payment_internal(db: Session, payment: Payment, capture_amount: int):
    capture_response = await call_bank_capture(
        payment.id,
        payment.authorization_code,
        capture_amount,
    )

    if not capture_response["success"]:
        log_transaction(
            db,
            payment.id,
            TransactionType.CAPTURE,
            capture_amount,
            payment.currency,
            "failed",
            None,
            "capture_failed",
            capture_response.get("message"),
        )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={"error": "capture_failed", "message": capture_response.get("message")},
        )

    payment.amount_captured = (payment.amount_captured or 0) + capture_amount
    payment.captured_at = datetime.now(tz=UTC)
    payment.updated_at = datetime.now(tz=UTC)

    if payment.amount_captured >= (payment.authorized_amount or payment.amount):
        payment.status = PaymentStatus.CAPTURED.value
    else:
        payment.status = PaymentStatus.PARTIALLY_CAPTURED.value

    log_transaction(
        db,
        payment.id,
        TransactionType.CAPTURE,
        capture_amount,
        payment.currency,
        "success",
        capture_response["capture_reference"],
    )

    db.commit()
    db.refresh(payment)

    logger.info(f"Captured: {payment.id} - {capture_amount}")

    return capture_response


async def auto_capture(payment_id: str, amount: int, merchant_id: str):
    db = SessionLocal()
    try:
        payment = db.query(Payment)
        .filter_by(id=payment_id, merchant_id=merchant_id)
        .first()
        if payment and payment.status == PaymentStatus.AUTHORIZED.value:
            await capture_payment_internal(db, payment, amount)
    except Exception as e:
        logger.exception(f"Auto-capture failed: {e!s}")
        db.rollback()
    finally:
        db.close()
