# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: Payment/services/transaction_service.py

import uuid
from datetime import datetime, timezone
from typing import Any

from Payment.models.enums import TransactionType
from Payment.models.payment import Transaction
from sqlalchemy.orm import Session


def log_transaction(
    db: Session,
    payment_id: str,
    transaction_type: TransactionType,
    amount: int,
    currency: str,
    status: str,
    bank_reference: str | None = None,
    failure_code: str | None = None,
    failure_message: str | None = None,
    metadata: dict[str, Any] | None = None,
) -> Transaction:
    transaction = Transaction(
        id=f"txn_{uuid.uuid4().hex}",
        payment_id=payment_id,
        transaction_type=transaction_type.value,
        amount=amount,
        currency=currency,
        status=status,
        bank_reference=bank_reference,
        failure_code=failure_code,
        failure_message=failure_message,
        metadata_json=metadata or {},
        created_at=datetime.now(tz=timezone.utc),
    )
    db.add(transaction)
    return transaction
