# filename: app/services/booking_service.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

from sqlalchemy.orm import Session
from sqlalchemy import and_, select
from typing import Optional, Dict, Any
from datetime import datetime, timedelta
import uuid
import time

from app.models.seat import Seat, SeatStatus
from app.models.booking import Booking, BookingStatus, PaymentStatus
from app.models.booking_attempt import BookingAttempt
from app.services.lock_service import DistributedLock, LockAcquisitionError
from app.services.event_publisher import EventPublisher
from app.core.logging import get_logger
from app.core.metrics import (
    booking_counter,
    booking_duration_histogram,
    booking_errors_counter
)
from app.core.exceptions import (
    SeatNotFoundError,
    SeatAlreadyBookedError,
    SeatReservedError,
    BookingConflictError,
    SeatLockedError
)

logger = get_logger(__name__)


class BookingService:
    def __init__(
            self,
            db: Session,
            lock_service: DistributedLock,
            event_publisher: EventPublisher
    ):
        self.db = db
        self.lock_service = lock_service
        self.event_publisher = event_publisher

    async def book_seat(
            self,
            user_id: uuid.UUID,
            event_id: uuid.UUID,
            seat_id: uuid.UUID,
            idempotency_key: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Book a seat with distributed locking and optimistic concurrency control
        """
        start_time = time.time()

        try:
            # Check idempotency
            if idempotency_key:
                existing_booking = await self._check_idempotency(idempotency_key)
                if existing_booking:
                    logger.info(
                        "Duplicate request detected",
                        extra={"idempotency_key": idempotency_key}
                    )
                    return self._format_success_response(existing_booking, is_duplicate=True)

            # Acquire distributed lock
            lock_resource = f"seat:{event_id}:{seat_id}"

            try:
                async with self.lock_service.acquire(lock_resource, str(user_id)):
                    result = await self._execute_booking(
                        user_id, event_id, seat_id, idempotency_key
                    )
            except LockAcquisitionError:
                raise SeatLockedError("Seat is currently being processed by another user")

            # Record metrics
            duration = (time.time() - start_time) * 1000
            booking_duration_histogram.observe(duration / 1000)
            booking_counter.labels(status="success").inc()

            # Log attempt
            await self._log_attempt(
                user_id, event_id, seat_id, "success", None, int(duration)
            )

            return result

        except Exception as e:
            duration = (time.time() - start_time) * 1000
            error_type = type(e).__name__

            booking_counter.labels(status="failure").inc()
            booking_errors_counter.labels(error_type=error_type).inc()

            await self._log_attempt(
                user_id, event_id, seat_id, "failed", str(e), int(duration)
            )

            logger.error(
                "Booking failed",
                extra={
                    "user_id": str(user_id),
                    "seat_id": str(seat_id),
                    "error": str(e),
                    "error_type": error_type
                },
                exc_info=True
            )

            raise

    async def _execute_booking(
            self,
            user_id: uuid.UUID,
            event_id: uuid.UUID,
            seat_id: uuid.UUID,
            idempotency_key: Optional[str]
    ) -> Dict[str, Any]:
        """
        Execute the actual booking with optimistic locking
        """
        try:
            self.db.begin()

            # Get seat with row lock
            seat = self.db.query(Seat).filter(
                and_(
                    Seat.seat_id == seat_id,
                    Seat.event_id == event_id
                )
            ).with_for_update().first()

            if not seat:
                raise SeatNotFoundError("The selected seat does not exist")

            # Validate seat status
            self._validate_seat_availability(seat)

            # Store current version for optimistic locking
            current_version = seat.version

            # Update seat with version check
            update_result = self.db.query(Seat).filter(
                and_(
                    Seat.seat_id == seat_id,
                    Seat.event_id == event_id,
                    Seat.version == current_version
                )
            ).update(
                {
                    "status": SeatStatus.BOOKED,
                    "booked_by": user_id,
                    "booked_at": datetime.utcnow(),
                    "reserved_until": None,
                    "version": Seat.version + 1
                },
                synchronize_session=False
            )

            if update_result == 0:
                raise BookingConflictError(
                    "Booking conflict occurred. Please select another seat"
                )

            # Create booking record
            booking = Booking(
                booking_id=uuid.uuid4(),
                user_id=user_id,
                event_id=event_id,
                seat_id=seat_id,
                total_amount=seat.price,
                booking_status=BookingStatus.CONFIRMED,
                payment_status=PaymentStatus.PENDING,
                idempotency_key=idempotency_key
            )

            self.db.add(booking)
            self.db.commit()
            self.db.refresh(booking)

            # Publish event asynchronously
            await self.event_publisher.publish_booking_created(booking)

            logger.info(
                "Booking successful",
                extra={
                    "booking_id": str(booking.booking_id),
                    "user_id": str(user_id),
                    "seat_id": str(seat_id)
                }
            )

            return self._format_success_response(booking)

        except Exception as e:
            self.db.rollback()
            raise

    def _validate_seat_availability(self, seat: Seat):
        """Validate if seat can be booked"""
        if seat.status == SeatStatus.BOOKED:
            raise SeatAlreadyBookedError("This seat has already been booked")

        if seat.status == SeatStatus.RESERVED:
            if seat.reserved_until and seat.reserved_until > datetime.utcnow():
                raise SeatReservedError(
                    "This seat is currently reserved by another user"
                )

    async def _check_idempotency(self, idempotency_key: str) -> Optional[Booking]:
        """Check if booking already exists with this idempotency key"""
        booking = self.db.query(Booking).filter(
            Booking.idempotency_key == idempotency_key
        ).first()
        return booking

    async def _log_attempt(
            self,
            user_id: uuid.UUID,
            event_id: uuid.UUID,
            seat_id: uuid.UUID,
            status: str,
            error_message: Optional[str],
            response_time: int
    ):
        """Log booking attempt for monitoring"""
        attempt = BookingAttempt(
            user_id=user_id,
            event_id=event_id,
            seat_id=seat_id,
            attempt_status=status,
            error_message=error_message,
            response_time_ms=response_time
        )
        self.db.add(attempt)
        try:
            self.db.commit()
        except Exception as e:
            logger.error(f"Failed to log booking attempt: {e}")
            self.db.rollback()

    def _format_success_response(
            self,
            booking: Booking,
            is_duplicate: bool = False
    ) -> Dict[str, Any]:
        """Format successful booking response"""
        return {
            "success": True,
            "booking_id": str(booking.booking_id),
            "seat_id": str(booking.seat_id),
            "amount": float(booking.total_amount),
            "status": booking.booking_status.value,
            "is_duplicate": is_duplicate
        }
