# filename: app/services/reservation_service.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

from sqlalchemy.orm import Session
from sqlalchemy import and_
from datetime import datetime, timedelta
import uuid

from app.models.seat import Seat, SeatStatus
from app.services.lock_service import DistributedLock, LockAcquisitionError
from app.core.logging import get_logger
from app.core.exceptions import SeatNotAvailableError, SeatLockedError
from app.config import settings
from redis.asyncio import Redis

logger = get_logger(__name__)


class ReservationService:
    def __init__(
            self,
            db: Session,
            lock_service: DistributedLock,
            redis_client: Redis
    ):
        self.db = db
        self.lock_service = lock_service
        self.redis = redis_client
        self.reservation_timeout = settings.RESERVATION_TIMEOUT_SECONDS

    async def reserve_seat(
            self,
            user_id: uuid.UUID,
            event_id: uuid.UUID,
            seat_id: uuid.UUID
    ) -> dict:
        """
        Temporarily reserve a seat
        """
        lock_resource = f"seat:{event_id}:{seat_id}"

        try:
            async with self.lock_service.acquire(lock_resource, str(user_id)):
                reserved_until = datetime.utcnow() + timedelta(
                    seconds=self.reservation_timeout
                )

                # Update seat to reserved
                update_result = self.db.query(Seat).filter(
                    and_(
                        Seat.seat_id == seat_id,
                        Seat.event_id == event_id,
                        Seat.status == SeatStatus.AVAILABLE
                    )
                ).update(
                    {
                        "status": SeatStatus.RESERVED,
                        "booked_by": user_id,
                        "reserved_until": reserved_until,
                        "version": Seat.version + 1
                    },
                    synchronize_session=False
                )

                if update_result == 0:
                    raise SeatNotAvailableError("Seat is not available for reservation")

                self.db.commit()

                # Set Redis expiration for auto-cleanup
                await self.redis.setex(
                    f"reservation:{seat_id}",
                    self.reservation_timeout,
                    str(user_id)
                )

                logger.info(
                    "Seat reserved",
                    extra={
                        "user_id": str(user_id),
                        "seat_id": str(seat_id),
                        "reserved_until": reserved_until.isoformat()
                    }
                )

                return {
                    "success": True,
                    "seat_id": str(seat_id),
                    "reserved_until": reserved_until.isoformat()
                }

        except LockAcquisitionError:
            raise SeatLockedError("Unable to reserve seat at this time")
        except Exception as e:
            self.db.rollback()
            logger.error(f"Reservation failed: {e}", exc_info=True)
            raise

    async def release_expired_reservations(self):
        """
        Background task to release expired reservations
        """
        try:
            self.db.query(Seat).filter(
                and_(
                    Seat.status == SeatStatus.RESERVED,
                    Seat.reserved_until < datetime.utcnow()
                )
            ).update(
                {
                    "status": SeatStatus.AVAILABLE,
                    "reserved_until": None,
                    "booked_by": None,
                    "version": Seat.version + 1
                },
                synchronize_session=False
            )

            self.db.commit()
            logger.info("Expired reservations released")

        except Exception as e:
            self.db.rollback()
            logger.error(f"Failed to release expired reservations: {e}")
