-- Code Generated by Sidekick is for learning and experimentation purposes only.
-- database/init.sql

CREATE TABLE IF NOT EXISTS urls (
    id BIGSERIAL PRIMARY KEY,
    url TEXT NOT NULL,
    short_url VARCHAR(10) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    expiration_time TIMESTAMP,
    created_by VARCHAR(100),
    status VARCHAR(20) DEFAULT 'active',
    clicks BIGINT DEFAULT 0,
    last_accessed TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_short_url ON urls(short_url);
CREATE INDEX IF NOT EXISTS idx_status ON urls(status);
CREATE INDEX IF NOT EXISTS idx_created_by ON urls(created_by);
CREATE INDEX IF NOT EXISTS idx_expiration ON urls(expiration_time);

CREATE TABLE IF NOT EXISTS click_events (
    id BIGSERIAL PRIMARY KEY,
    short_url VARCHAR(10) NOT NULL,
    clicked_at TIMESTAMP DEFAULT NOW(),
    user_agent TEXT,
    ip_address VARCHAR(45),
    referrer TEXT,
    country VARCHAR(100)
);

CREATE INDEX IF NOT EXISTS idx_click_short_url ON click_events(short_url);
CREATE INDEX IF NOT EXISTS idx_clicked_at ON click_events(clicked_at);

-- Drop and recreate replication role to avoid errors
DROP ROLE IF EXISTS replicator;
CREATE ROLE replicator WITH REPLICATION PASSWORD 'replicator_password' LOGIN;
GRANT CONNECT ON DATABASE urlshortener TO replicator;
