# filename: api-customer.ps1
# Code Generated by Sidekick is for learning and experimentation purposes only.

# ============================================================================
# CONFIGURATION
# ============================================================================
$API_GATEWAY     = "http://localhost:8080"
$AUTH_SERVICE    = "http://localhost:9000"
$FRAUD_SERVICE   = "http://localhost:8004"
$PUBLISHABLE_KEY = "pk_test_123"

$pass       = 0
$fail       = 0
$results    = @()
$SESSION_ID = $null
$MC_TOKEN   = $null
$PAYMENT_ID = $null
$JWT        = $null
$abort      = $false

function Write-Header {
    param([string]$t)
    Write-Host ""
    Write-Host ("="*70) -ForegroundColor Cyan
    Write-Host "  $t" -ForegroundColor Cyan
    Write-Host ("="*70) -ForegroundColor Cyan
}

function Pass {
    param([string]$t)
    Write-Host "  [PASS] $t" -ForegroundColor Green
    $script:pass++
    $script:results += [PSCustomObject]@{ Test=$t; Result="PASS" }
}

function Fail {
    param([string]$t, [string]$e="")
    Write-Host "  [FAIL] $t" -ForegroundColor Red
    if ($e -ne "") { Write-Host "         $e" -ForegroundColor DarkRed }
    $script:fail++
    $script:results += [PSCustomObject]@{ Test=$t; Result="FAIL: $e" }
}

# ── Banner ──────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  CUSTOMER FLOW - COMPLETE TEST SUITE" -ForegroundColor Cyan
Write-Host ("="*70) -ForegroundColor Cyan

# ============================================================================
# TEST 1: HEALTH CHECKS
# ============================================================================
Write-Header "TEST 1: HEALTH CHECKS"

Write-Host "`n  Checking API Gateway..." -ForegroundColor Yellow
try {
    $h = Invoke-RestMethod -Uri "$API_GATEWAY/health" -Method GET -TimeoutSec 5
    if ($h.status -eq "ok" -or $h.status -eq "up") { Pass "API Gateway healthy" }
    if ($h.status -ne "ok" -and $h.status -ne "up") { Fail "API Gateway unhealthy" }
} catch {
    Fail "API Gateway unreachable" "$_"
    $abort = $true
}

Write-Host "`n  Checking Auth Service..." -ForegroundColor Yellow
try {
    $h = Invoke-RestMethod -Uri "$AUTH_SERVICE/health" -Method GET -TimeoutSec 5
    if ($h.status -eq "ok" -or $h.status -eq "up") { Pass "Auth Service healthy" }
    if ($h.status -ne "ok" -and $h.status -ne "up") { Fail "Auth Service unhealthy" }
} catch {
    Fail "Auth Service unreachable" "$_"
    $abort = $true
}

Write-Host "`n  Checking Fraud Service..." -ForegroundColor Yellow
try {
    $h = Invoke-RestMethod -Uri "$FRAUD_SERVICE/health" -Method GET -TimeoutSec 5
    if ($h.status -eq "ok" -or $h.status -eq "up") { Pass "Fraud Service healthy" }
    if ($h.status -ne "ok" -and $h.status -ne "up") { Fail "Fraud Service unhealthy" }
} catch {
    Fail "Fraud Service unreachable" "$_"
}

if ($abort) {
    Write-Host "`n  [ABORTED] Gateway or Auth unreachable. Fix connectivity and re-run." -ForegroundColor Red
    Write-Host ""
    exit 0
}

# ============================================================================
# TEST 2: AUTHENTICATION
# ============================================================================
Write-Header "TEST 2: AUTHENTICATION"

Write-Host "`n  Requesting JWT..." -ForegroundColor Yellow
try {
    $body = @{
        sub    = "cust_$(Get-Date -Format 'yyyyMMddHHmmss')"
        email  = "customer@gmail.com"
        roles  = @("customer")
        scopes = @(
            "payment_session:create"
            "payment_session:read_own"
            "payment_method:tokenize"
            "payment_intent:confirm_own"
            "public_config:read"
        )
    } | ConvertTo-Json

    $tokenResp = Invoke-RestMethod -Uri "$AUTH_SERVICE/token" -Method POST `
        -ContentType "application/json" -Body $body -TimeoutSec 10

    $JWT = $tokenResp.access_token
    if ($JWT) {
        Pass "JWT token obtained"
        Write-Host "    Token  : $($JWT.Substring(0, [Math]::Min(50,$JWT.Length)))..." -ForegroundColor White
    }
    if (-not $JWT) {
        Fail "JWT token empty or missing"
        $abort = $true
    }
} catch {
    Fail "JWT request failed" "$_"
    $abort = $true
}

if ($abort) {
    Write-Host "`n  [ABORTED] Cannot continue without JWT." -ForegroundColor Red
    Write-Host ""
    exit 0
}

$custHeaders = @{
    "Content-Type"      = "application/json"
    "X-Publishable-Key" = $PUBLISHABLE_KEY
    "Authorization"     = "Bearer $JWT"
}

# ============================================================================
# TEST 3: PUBLIC CONFIGURATION
# ============================================================================
Write-Header "TEST 3: PUBLIC CONFIGURATION"

Write-Host "`n  Fetching config..." -ForegroundColor Yellow
try {
    $config = Invoke-RestMethod -Uri "$API_GATEWAY/v1/customer/config" `
        -Method GET -Headers $custHeaders -TimeoutSec 10
    if ($config.merchant_id) {
        Pass "Config retrieved"
        Write-Host "    Merchant ID : $($config.merchant_id)" -ForegroundColor White
        Write-Host "    Methods     : $($config.supported_methods -join ', ')" -ForegroundColor White
    }
    if (-not $config.merchant_id) { Fail "Config missing merchant_id" }
} catch { Fail "Config request failed" "$_" }

# ============================================================================
# TEST 4: PAYMENT SESSION
# ============================================================================
Write-Header "TEST 4: PAYMENT SESSION"

Write-Host "`n  Creating session (capture=true)..." -ForegroundColor Yellow
try {
    $body = @{
        cart_id     = "cart_$(Get-Date -Format 'yyyyMMddHHmmss')"
        order_id    = "order_$(Get-Date -Format 'yyyyMMddHHmmss')"
        amount      = 7500
        currency    = "usd"
        description = "Customer test order"
        metadata    = @{ test="customer_flow"; env="powershell" }
        capture     = $true
    } | ConvertTo-Json

    $session    = Invoke-RestMethod -Uri "$API_GATEWAY/v1/customer/payment_sessions" `
        -Method POST -Headers $custHeaders -Body $body -TimeoutSec 10
    $SESSION_ID = $session.session_id

    if ($SESSION_ID) {
        Pass "Session created"
        Write-Host "    Session ID : $SESSION_ID" -ForegroundColor White
        Write-Host "    Amount     : `$$($session.amount/100) $($session.currency.ToUpper())" -ForegroundColor White
        Write-Host "    Status     : $($session.status)" -ForegroundColor White
        Write-Host "    Expires    : $($session.expires_at)" -ForegroundColor White
    }
    if (-not $SESSION_ID) {
        Fail "Session ID missing from response"
        $abort = $true
    }
} catch {
    Fail "Session creation failed" "$_"
    $abort = $true
}

Write-Host "`n  Retrieving session..." -ForegroundColor Yellow
if ($SESSION_ID) {
    try {
        $s = Invoke-RestMethod -Uri "$API_GATEWAY/v1/customer/payment_sessions/$SESSION_ID" `
            -Method GET -Headers $custHeaders -TimeoutSec 10
        if ($s.status -eq "created") {
            Pass "Session retrieved - status: $($s.status)"
        }
        if ($s.status -ne "created") { Fail "Unexpected status: $($s.status)" }
    } catch { Fail "Session retrieval failed" "$_" }
}
if (-not $SESSION_ID) { Fail "Session retrieval skipped - no session ID" }

Write-Host "`n  Creating auth-only session (capture=false)..." -ForegroundColor Yellow
try {
    $body = @{
        cart_id  = "cart_auth_$(Get-Date -Format 'yyyyMMddHHmmss')"
        amount   = 5000
        currency = "usd"
        capture  = $false
    } | ConvertTo-Json
    $authSess = Invoke-RestMethod -Uri "$API_GATEWAY/v1/customer/payment_sessions" `
        -Method POST -Headers $custHeaders -Body $body -TimeoutSec 10
    if ($authSess.session_id) {
        Pass "Auth-only session created - capture: $($authSess.capture)"
    }
    if (-not $authSess.session_id) { Fail "Auth-only session missing ID" }
} catch { Fail "Auth-only session failed" "$_" }

# ============================================================================
# TEST 5: CARD TOKENIZATION
# ============================================================================
Write-Header "TEST 5: CARD TOKENIZATION"

Write-Host "`n  Tokenizing Visa..." -ForegroundColor Yellow
try {
    $body = @{ card_number="4242424242424242"; exp_month=12; exp_year=2026; cvc="123" } | ConvertTo-Json
    $t = Invoke-RestMethod -Uri "$API_GATEWAY/v1/customer/payment_methods/tokenize" `
        -Method POST -Headers $custHeaders -Body $body -TimeoutSec 10
    if ($t.payment_method_token) {
        Pass "Visa tokenized - brand:$($t.brand) last4:$($t.last4)"
    }
    if (-not $t.payment_method_token) { Fail "Visa token missing" }
} catch { Fail "Visa tokenization failed" "$_" }

Write-Host "`n  Tokenizing Mastercard..." -ForegroundColor Yellow
try {
    $body = @{ card_number="5555555555554444"; exp_month=12; exp_year=2026; cvc="123" } | ConvertTo-Json
    $t = Invoke-RestMethod -Uri "$API_GATEWAY/v1/customer/payment_methods/tokenize" `
        -Method POST -Headers $custHeaders -Body $body -TimeoutSec 10
    if ($t.payment_method_token) {
        Pass "Mastercard tokenized - brand:$($t.brand) last4:$($t.last4)"
        $MC_TOKEN = $t.payment_method_token
    }
    if (-not $t.payment_method_token) { Fail "Mastercard token missing" }
} catch { Fail "Mastercard tokenization failed" "$_" }

Write-Host "`n  Tokenizing Amex..." -ForegroundColor Yellow
try {
    $body = @{ card_number="378282246310005"; exp_month=12; exp_year=2026; cvc="1234" } | ConvertTo-Json
    $t = Invoke-RestMethod -Uri "$API_GATEWAY/v1/customer/payment_methods/tokenize" `
        -Method POST -Headers $custHeaders -Body $body -TimeoutSec 10
    if ($t.payment_method_token) {
        Pass "Amex tokenized - brand:$($t.brand) last4:$($t.last4)"
    }
    if (-not $t.payment_method_token) { Fail "Amex token missing" }
} catch { Fail "Amex tokenization failed" "$_" }

# ============================================================================
# TEST 6: PAYMENT CONFIRMATION
# ============================================================================
Write-Header "TEST 6: PAYMENT CONFIRMATION"

Write-Host "`n  Confirming payment (Mastercard)..." -ForegroundColor Yellow
if ($SESSION_ID -and $MC_TOKEN) {
    try {
        $body = @{ session_id=$SESSION_ID; payment_method_token=$MC_TOKEN } | ConvertTo-Json
        $confirm = Invoke-RestMethod `
            -Uri "$API_GATEWAY/v1/customer/payment_intents/confirm" `
            -Method POST -Headers $custHeaders -Body $body -TimeoutSec 30

        $PAYMENT_ID = $confirm.session.payment_id
        if ($PAYMENT_ID) {
            Pass "Payment confirmed"
            Write-Host "    Payment ID     : $PAYMENT_ID" -ForegroundColor White
            Write-Host "    Payment Status : $($confirm.session.status)" -ForegroundColor White
            Write-Host "    Order ID       : $($confirm.session.order_id)" -ForegroundColor White
            Write-Host "    Amount         : `$$($confirm.session.amount / 100)" -ForegroundColor White
        }
        if (-not $PAYMENT_ID) { Fail "Payment confirmed but payment_id missing" }
    } catch { Fail "Payment confirmation failed" "$($_.ErrorDetails.Message)" }
}
if (-not $SESSION_ID) { Fail "Confirm skipped - no session ID available" }
if (-not $MC_TOKEN)   { Fail "Confirm skipped - no Mastercard token available" }

# ============================================================================
# TEST 7: ERROR HANDLING
# ============================================================================
Write-Header "TEST 7: ERROR HANDLING"

Write-Host "`n  Testing invalid publishable key..." -ForegroundColor Yellow
try {
    $bh = @{ "Content-Type"="application/json"; "X-Publishable-Key"="pk_invalid_999"; "Authorization"="Bearer $JWT" }
    Invoke-RestMethod -Uri "$API_GATEWAY/v1/customer/config" -Method GET -Headers $bh -TimeoutSec 10
    Fail "Invalid key should have been rejected"
} catch {
    $code = 0
    if ($_.Exception.Response) { $code = [int]$_.Exception.Response.StatusCode }
    if ($code -gt 0) { Pass "Invalid key rejected - HTTP $code" }
    if ($code -eq 0) { Pass "Invalid key rejected - no response" }
}

Write-Host "`n  Testing missing publishable key..." -ForegroundColor Yellow
try {
    Invoke-RestMethod -Uri "$API_GATEWAY/v1/customer/config" -Method GET `
        -Headers @{ "Authorization"="Bearer $JWT"; "Content-Type"="application/json" } -TimeoutSec 10
    Fail "Missing key should have been rejected"
} catch { Pass "Missing key rejected" }

Write-Host "`n  Testing invalid session ID..." -ForegroundColor Yellow
try {
    $body = @{ session_id="ps_invalid_000"; payment_method_token=$MC_TOKEN } | ConvertTo-Json
    Invoke-RestMethod -Uri "$API_GATEWAY/v1/customer/payment_intents/confirm" `
        -Method POST -Headers $custHeaders -Body $body -TimeoutSec 10
    Fail "Invalid session should have been rejected"
} catch { Pass "Invalid session rejected" }

Write-Host "`n  Testing invalid payment method token..." -ForegroundColor Yellow
try {
    $body = @{
        cart_id  = "cart_err_$(Get-Date -Format 'yyyyMMddHHmmss')"
        order_id = "order_err_$(Get-Date -Format 'yyyyMMddHHmmss')"
        amount   = 1000; currency="usd"; capture=$true
    } | ConvertTo-Json
    $fresh = Invoke-RestMethod -Uri "$API_GATEWAY/v1/customer/payment_sessions" `
        -Method POST -Headers $custHeaders -Body $body -TimeoutSec 10
    $body2 = @{ session_id=$fresh.session_id; payment_method_token="pm_invalid_token" } | ConvertTo-Json
    Invoke-RestMethod -Uri "$API_GATEWAY/v1/customer/payment_intents/confirm" `
        -Method POST -Headers $custHeaders -Body $body2 -TimeoutSec 10
    Fail "Invalid token should have been rejected"
} catch { Pass "Invalid token rejected" }

Write-Host "`n  Testing expired JWT..." -ForegroundColor Yellow
try {
    $eh = @{
        "Content-Type"      = "application/json"
        "X-Publishable-Key" = $PUBLISHABLE_KEY
        "Authorization"     = "Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxfQ.invalid"
    }
    Invoke-RestMethod -Uri "$API_GATEWAY/v1/customer/config" -Method GET -Headers $eh -TimeoutSec 10
    Fail "Expired JWT should have been rejected"
} catch { Pass "Expired JWT rejected" }

# ============================================================================
# FINAL SUMMARY
# ============================================================================
Write-Host ""
Write-Host ("="*70) -ForegroundColor Cyan
Write-Host "  FINAL RESULTS" -ForegroundColor Cyan
Write-Host ("="*70) -ForegroundColor Cyan
Write-Host ""
Write-Host "  Total : $($pass + $fail)" -ForegroundColor White
Write-Host "  PASS  : $pass"             -ForegroundColor Green
Write-Host "  FAIL  : $fail"             -ForegroundColor Red

if ($PAYMENT_ID) {
    Write-Host ""
    Write-Host "  Payment ID : $PAYMENT_ID" -ForegroundColor Cyan
    Write-Host "  Session ID : $SESSION_ID" -ForegroundColor Cyan
}

Write-Host ""
if ($fail -eq 0) { Write-Host "  ALL TESTS PASSED" -ForegroundColor Green }
if ($fail -gt 0) { Write-Host "  SOME TESTS FAILED - review output above" -ForegroundColor Yellow }

Write-Host ""
Write-Host "Detailed Results:" -ForegroundColor Cyan
$results | Format-Table -AutoSize
