# Code Generated by Sidekick is for learning and experimentation purposes only. | filename: payment-search-smoke-test.ps1

param(
    [string]$PaymentBaseUrl = "http://localhost:8003",
    [string]$ElasticsearchUrl = "http://localhost:9200",
    [string]$ElasticsearchIndex = "payment-gt-payments-v1",
    [string]$PaymentId = "",
    [string]$MerchantId = "",
    [string]$Status = "",
    [string]$CreatePaymentJsonPath = "",
    [string]$CreateEndpoint = "/api/v1/payments",
    [string]$PaymentBearerToken = "",
    [string]$ElasticsearchApiKey = "",
    [string]$ElasticsearchUser = "",
    [string]$ElasticsearchPassword = "",
    [switch]$SkipNegativeTests,
    [switch]$Strict
)

$ErrorActionPreference = "Continue"
$PaymentBaseUrl = $PaymentBaseUrl.TrimEnd("/")
$ElasticsearchUrl = $ElasticsearchUrl.TrimEnd("/")
$script:Total = 0
$script:Failures = 0

$paymentHeaders = @{
    Accept = "application/json"
}

$elasticsearchHeaders = @{
    Accept = "application/json"
}

if (-not [string]::IsNullOrWhiteSpace($PaymentBearerToken)) {
    $paymentHeaders.Authorization = "Bearer $PaymentBearerToken"
}

if (-not [string]::IsNullOrWhiteSpace($ElasticsearchApiKey)) {
    $elasticsearchHeaders.Authorization = "ApiKey $ElasticsearchApiKey"
}
elseif (
    -not [string]::IsNullOrWhiteSpace($ElasticsearchUser) -and
    -not [string]::IsNullOrWhiteSpace($ElasticsearchPassword)
) {
    $credentialText = "$ElasticsearchUser`:$ElasticsearchPassword"
    $credentialBytes = [Text.Encoding]::ASCII.GetBytes($credentialText)
    $encodedCredentials = [Convert]::ToBase64String($credentialBytes)
    $elasticsearchHeaders.Authorization = "Basic $encodedCredentials"
}

function Get-PropertyValue {
    param(
        [object]$Object,
        [string[]]$Names
    )

    if ($null -eq $Object) {
        return $null
    }

    foreach ($name in $Names) {
        if ($Object -is [System.Collections.IDictionary]) {
            if ($Object.Contains($name)) {
                return $Object[$name]
            }
        }

        $property = $Object.PSObject.Properties[$name]

        if ($null -ne $property) {
            return $property.Value
        }
    }

    return $null
}

function Get-Items {
    param([object]$Body)

    $items = Get-PropertyValue -Object $Body -Names @("items")

    if ($null -eq $items) {
        return @()
    }

    return @($items)
}

function Invoke-ApiRequest {
    param(
        [ValidateSet("GET", "POST", "PUT", "PATCH", "DELETE")]
        [string]$Method,
        [string]$Uri,
        [hashtable]$Headers,
        [object]$Body = $null
    )

    $request = @{
        Uri         = $Uri
        Method      = $Method
        Headers     = $Headers
        ErrorAction = "Stop"
    }

    if ($null -ne $Body) {
        $request.ContentType = "application/json"

        if ($Body -is [string]) {
            $request.Body = $Body
        }
        else {
            $request.Body = $Body | ConvertTo-Json -Depth 20 -Compress
        }
    }

    try {
        $response = Invoke-WebRequest @request
        $raw = [string]$response.Content
        $parsed = $null

        if (-not [string]::IsNullOrWhiteSpace($raw)) {
            try {
                $parsed = $raw | ConvertFrom-Json
            }
            catch {
                $parsed = $null
            }
        }

        return [pscustomobject]@{
            StatusCode = [int]$response.StatusCode
            Body       = $parsed
            Raw        = $raw
            Error      = $null
        }
    }
    catch {
        $exception = $_.Exception
        $errorResponse = $exception.Response
        $statusCode = 0
        $raw = $exception.Message

        if ($null -ne $errorResponse) {
            try {
                $statusCode = [int]$errorResponse.StatusCode
            }
            catch {
                $statusCode = 0
            }

            try {
                $raw = $errorResponse.Content.ReadAsStringAsync().Result
            }
            catch {
                try {
                    $raw = $errorResponse.StatusDescription
                }
                catch {
                    $raw = $exception.Message
                }
            }
        }

        $parsed = $null

        if (-not [string]::IsNullOrWhiteSpace($raw)) {
            try {
                $parsed = $raw | ConvertFrom-Json
            }
            catch {
                $parsed = $null
            }
        }

        return [pscustomobject]@{
            StatusCode = $statusCode
            Body       = $parsed
            Raw        = $raw
            Error      = $exception.Message
        }
    }
}

function Assert-TestResult {
    param(
        [string]$Name,
        [object]$Response,
        [int[]]$ExpectedStatus = @(200),
        [scriptblock]$Condition = $null
    )

    $script:Total++
    $passed = $false
    $reason = "No response"

    if ($null -ne $Response) {
        $passed = $ExpectedStatus -contains [int]$Response.StatusCode
        $reason = "HTTP $($Response.StatusCode)"

        if ($passed -and $null -ne $Condition) {
            try {
                $passed = [bool](& $Condition $Response.Body)

                if (-not $passed) {
                    $reason = "$reason; response validation failed"
                }
            }
            catch {
                $passed = $false
                $reason = "$reason; validation error: $($_.Exception.Message)"
            }
        }

        if (-not $passed -and -not [string]::IsNullOrWhiteSpace($Response.Raw)) {
            $shortBody = $Response.Raw.Replace("`r", " ").Replace("`n", " ")

            if ($shortBody.Length -gt 300) {
                $shortBody = $shortBody.Substring(0, 300)
            }

            $reason = "$reason; $shortBody"
        }
    }

    if ($passed) {
        Write-Host "[PASS] $Name - $reason" -ForegroundColor Green
    }
    else {
        Write-Host "[FAIL] $Name - $reason" -ForegroundColor Red
        $script:Failures++

        if ($Strict) {
            throw "Strict mode stopped after failure: $Name"
        }
    }

    return $passed
}

function Write-SkippedTest {
    param([string]$Name)

    Write-Host "[SKIP] $Name" -ForegroundColor Yellow
}

function Wait-ForElasticsearchDocument {
    param(
        [string]$DocumentId,
        [int]$TimeoutSeconds = 20
    )

    $encodedId = [uri]::EscapeDataString($DocumentId)
    $uri = "$ElasticsearchUrl/$ElasticsearchIndex/$encodedId"
    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    $lastResponse = $null

    do {
        $lastResponse = Invoke-ApiRequest `
            -Method GET `
            -Uri $uri `
            -Headers $elasticsearchHeaders

        if ($lastResponse.StatusCode -eq 200) {
            return $lastResponse
        }

        Start-Sleep -Seconds 1
    }
    while ((Get-Date) -lt $deadline)

    return $lastResponse
}

Write-Host ""
Write-Host "Payment Search Smoke Test" -ForegroundColor Cyan
Write-Host "Payment service: $PaymentBaseUrl"
Write-Host "Elasticsearch:   $ElasticsearchUrl"
Write-Host "Index:            $ElasticsearchIndex"
Write-Host ""

$health = Invoke-ApiRequest `
    -Method GET `
    -Uri "$PaymentBaseUrl/health" `
    -Headers $paymentHeaders

Assert-TestResult `
    -Name "Payment service health endpoint" `
    -Response $health `
    -ExpectedStatus @(200)

$esRoot = Invoke-ApiRequest `
    -Method GET `
    -Uri "$ElasticsearchUrl/" `
    -Headers $elasticsearchHeaders

Assert-TestResult `
    -Name "Elasticsearch root endpoint" `
    -Response $esRoot `
    -ExpectedStatus @(200)

$clusterHealth = Invoke-ApiRequest `
    -Method GET `
    -Uri "$ElasticsearchUrl/_cluster/health?wait_for_status=yellow&timeout=10s" `
    -Headers $elasticsearchHeaders

Assert-TestResult `
    -Name "Elasticsearch cluster health" `
    -Response $clusterHealth `
    -ExpectedStatus @(200) `
    -Condition {
        param($body)
        $status = Get-PropertyValue $body @("status")
        $status -in @("green", "yellow")
    }

$indexInfo = Invoke-ApiRequest `
    -Method GET `
    -Uri "$ElasticsearchUrl/$ElasticsearchIndex" `
    -Headers $elasticsearchHeaders

Assert-TestResult `
    -Name "Payment Elasticsearch index exists" `
    -Response $indexInfo `
    -ExpectedStatus @(200)

$mapping = Invoke-ApiRequest `
    -Method GET `
    -Uri "$ElasticsearchUrl/$ElasticsearchIndex/_mapping" `
    -Headers $elasticsearchHeaders

$mappingEntry = Get-PropertyValue `
    -Object $mapping.Body `
    -Names @($ElasticsearchIndex)

$mappingsObject = Get-PropertyValue `
    -Object $mappingEntry `
    -Names @("mappings")

$mappingProperties = Get-PropertyValue `
    -Object $mappingsObject `
    -Names @("properties")

$requiredFields = @(
    "payment_id",
    "merchant_id",
    "customer_id",
    "order_id",
    "status",
    "amount_minor",
    "updated_at"
)

$missingFields = @()

foreach ($field in $requiredFields) {
    if ($null -eq (Get-PropertyValue $mappingProperties @($field))) {
        $missingFields += $field
    }
}

$mappingIsValid = $missingFields.Count -eq 0

Assert-TestResult `
    -Name "Payment index contains required mappings" `
    -Response $mapping `
    -ExpectedStatus @(200) `
    -Condition {
        param($body)
        $mappingIsValid
    }

$countResponse = Invoke-ApiRequest `
    -Method GET `
    -Uri "$ElasticsearchUrl/$ElasticsearchIndex/_count" `
    -Headers $elasticsearchHeaders

$beforeCount = Get-PropertyValue `
    -Object $countResponse.Body `
    -Names @("count")

Assert-TestResult `
    -Name "Payment index count endpoint" `
    -Response $countResponse `
    -ExpectedStatus @(200) `
    -Condition {
        param($body)
        $null -ne (Get-PropertyValue $body @("count"))
    }

if (-not [string]::IsNullOrWhiteSpace($CreatePaymentJsonPath)) {
    if (-not (Test-Path -LiteralPath $CreatePaymentJsonPath)) {
        Write-Host "[FAIL] Create payment JSON file was not found: $CreatePaymentJsonPath" `
            -ForegroundColor Red
        $script:Failures++
    }
    else {
        try {
            $createPayload = Get-Content `
                -LiteralPath $CreatePaymentJsonPath `
                -Raw `
                | ConvertFrom-Json

            $createResponse = Invoke-ApiRequest `
                -Method POST `
                -Uri "$PaymentBaseUrl$CreateEndpoint" `
                -Headers $paymentHeaders `
                -Body $createPayload

            Assert-TestResult `
                -Name "Create payment API request" `
                -Response $createResponse `
                -ExpectedStatus @(200, 201, 202)

            $createdObject = Get-PropertyValue `
                -Object $createResponse.Body `
                -Names @("payment", "data")

            $createdId = Get-PropertyValue `
                -Object $createResponse.Body `
                -Names @("payment_id", "id")

            if ($null -eq $createdId -and $null -ne $createdObject) {
                $createdId = Get-PropertyValue `
                    -Object $createdObject `
                    -Names @("payment_id", "id")
            }

            if ($null -ne $createdId) {
                $PaymentId = [string]$createdId
                Write-Host "Created payment ID: $PaymentId" -ForegroundColor Cyan

                $indexedResponse = Wait-ForElasticsearchDocument `
                    -DocumentId $PaymentId

                Assert-TestResult `
                    -Name "Created payment appears in Elasticsearch" `
                    -Response $indexedResponse `
                    -ExpectedStatus @(200) `
                    -Condition {
                        param($body)
                        $source = Get-PropertyValue $body @("_source")
                        $indexedId = Get-PropertyValue $source @("payment_id")
                        [string]$indexedId -eq [string]$PaymentId
                    }
            }
            else {
                Write-Host "[WARN] Create response did not contain payment_id or id" `
                    -ForegroundColor Yellow
            }
        }
        catch {
            Write-Host "[FAIL] Create payment payload could not be loaded: $($_.Exception.Message)" `
                -ForegroundColor Red
            $script:Failures++
        }
    }
}

$directSearchBody = @{
    size  = 5
    query = @{
        match_all = @{}
    }
    sort  = @(
        @{
            updated_at = @{
                order   = "desc"
                missing = "_last"
            }
        }
    )
}

$directSearch = Invoke-ApiRequest `
    -Method POST `
    -Uri "$ElasticsearchUrl/$ElasticsearchIndex/_search" `
    -Headers $elasticsearchHeaders `
    -Body $directSearchBody

Assert-TestResult `
    -Name "Direct Elasticsearch payment search" `
    -Response $directSearch `
    -ExpectedStatus @(200) `
    -Condition {
        param($body)
        $hits = Get-PropertyValue $body @("hits")
        $null -ne (Get-PropertyValue $hits @("hits"))
    }

$directHitsObject = Get-PropertyValue `
    -Object $directSearch.Body `
    -Names @("hits")

$directHitsValue = Get-PropertyValue `
    -Object $directHitsObject `
    -Names @("hits")

$directHits = if ($null -eq $directHitsValue) {
    @()
}
else {
    @($directHitsValue)
}

$observedId = $PaymentId

if ([string]::IsNullOrWhiteSpace($observedId)) {
    foreach ($hit in $directHits) {
        $source = Get-PropertyValue $hit @("_source")
        $candidateId = Get-PropertyValue $source @("payment_id", "id")

        if ($null -ne $candidateId) {
            $observedId = [string]$candidateId
            break
        }
    }
}

$appSearch = Invoke-ApiRequest `
    -Method GET `
    -Uri "$PaymentBaseUrl/api/v1/payments/search?page=1&size=5" `
    -Headers $paymentHeaders

$appSearchItems = Get-Items $appSearch.Body

Assert-TestResult `
    -Name "Application payment search endpoint" `
    -Response $appSearch `
    -ExpectedStatus @(200) `
    -Condition {
        param($body)
        $hasItems = $null -ne (Get-PropertyValue $body @("items"))
        $hasTotal = $null -ne (Get-PropertyValue $body @("total"))
        $hasItems -and $hasTotal
    }

if ($null -eq $observedId -and $appSearchItems.Count -gt 0) {
    $firstItemId = Get-PropertyValue `
        -Object $appSearchItems[0] `
        -Names @("payment_id", "id")

    if ($null -ne $firstItemId) {
        $observedId = [string]$firstItemId
    }
}

$paginationSearch = Invoke-ApiRequest `
    -Method GET `
    -Uri "$PaymentBaseUrl/api/v1/payments/search?page=1&size=1" `
    -Headers $paymentHeaders

$paginationBody = $paginationSearch.Body
$paginationPage = Get-PropertyValue $paginationBody @("page")
$paginationSize = Get-PropertyValue $paginationBody @("size")
$paginationItems = Get-Items $paginationBody

$paginationIsValid = (
    [int]$paginationPage -eq 1 -and
    [int]$paginationSize -eq 1 -and
    $paginationItems.Count -le 1
)

Assert-TestResult `
    -Name "Application search pagination" `
    -Response $paginationSearch `
    -ExpectedStatus @(200) `
    -Condition {
        param($body)
        $paginationIsValid
    }

if (-not [string]::IsNullOrWhiteSpace($Status)) {
    $encodedStatus = [uri]::EscapeDataString($Status)
    $statusSearch = Invoke-ApiRequest `
        -Method GET `
        -Uri "$PaymentBaseUrl/api/v1/payments/search?status=$encodedStatus&page=1&size=20" `
        -Headers $paymentHeaders

    $statusItems = Get-Items $statusSearch.Body
    $statusFilterIsValid = $true

    foreach ($item in $statusItems) {
        $itemStatus = Get-PropertyValue $item @("status")

        if ([string]$itemStatus -ne $Status) {
            $statusFilterIsValid = $false
        }
    }

    Assert-TestResult `
        -Name "Status filter: $Status" `
        -Response $statusSearch `
        -ExpectedStatus @(200) `
        -Condition {
            param($body)
            $statusFilterIsValid
        }
}

if (-not [string]::IsNullOrWhiteSpace($MerchantId)) {
    $encodedMerchantId = [uri]::EscapeDataString($MerchantId)
    $merchantSearch = Invoke-ApiRequest `
        -Method GET `
        -Uri "$PaymentBaseUrl/api/v1/payments/search?merchant_id=$encodedMerchantId&page=1&size=20" `
        -Headers $paymentHeaders

    $merchantItems = Get-Items $merchantSearch.Body
    $merchantFilterIsValid = $true

    foreach ($item in $merchantItems) {
        $itemMerchantId = Get-PropertyValue $item @("merchant_id")

        if ([string]$itemMerchantId -ne $MerchantId) {
            $merchantFilterIsValid = $false
        }
    }

    Assert-TestResult `
        -Name "Merchant filter: $MerchantId" `
        -Response $merchantSearch `
        -ExpectedStatus @(200) `
        -Condition {
            param($body)
            $merchantFilterIsValid
        }
}

if (-not [string]::IsNullOrWhiteSpace($observedId)) {
    $encodedPaymentId = [uri]::EscapeDataString($observedId)

    $querySearch = Invoke-ApiRequest `
        -Method GET `
        -Uri "$PaymentBaseUrl/api/v1/payments/search?q=$encodedPaymentId&page=1&size=20" `
        -Headers $paymentHeaders

    $queryItems = Get-Items $querySearch.Body
    $queryFoundId = $false

    foreach ($item in $queryItems) {
        $itemId = Get-PropertyValue $item @("payment_id", "id")

        if ([string]$itemId -eq [string]$observedId) {
            $queryFoundId = $true
        }
    }

    Assert-TestResult `
        -Name "Search by payment ID: $observedId" `
        -Response $querySearch `
        -ExpectedStatus @(200) `
        -Condition {
            param($body)
            $queryFoundId
        }

    $singlePayment = Invoke-ApiRequest `
        -Method GET `
        -Uri "$PaymentBaseUrl/api/v1/payments/$encodedPaymentId" `
        -Headers $paymentHeaders

    Assert-TestResult `
        -Name "Fetch payment by ID: $observedId" `
        -Response $singlePayment `
        -ExpectedStatus @(200) `
        -Condition {
            param($body)
            $returnedId = Get-PropertyValue $body @("payment_id", "id")
            [string]$returnedId -eq [string]$observedId
        }

    $esDocument = Invoke-ApiRequest `
        -Method GET `
        -Uri "$ElasticsearchUrl/$ElasticsearchIndex/$encodedPaymentId" `
        -Headers $elasticsearchHeaders

    Assert-TestResult `
        -Name "Fetch payment document directly from Elasticsearch" `
        -Response $esDocument `
        -ExpectedStatus @(200) `
        -Condition {
            param($body)
            $source = Get-PropertyValue $body @("_source")
            $indexedId = Get-PropertyValue $source @("payment_id")
            [string]$indexedId -eq [string]$observedId
        }
}
else {
    Write-SkippedTest `
        -Name "Payment-specific tests; provide -PaymentId or -CreatePaymentJsonPath"
}

if (-not $SkipNegativeTests) {
    $missingQuery = "not-found-$([guid]::NewGuid().ToString("N"))"
    $encodedMissingQuery = [uri]::EscapeDataString($missingQuery)

    $missingSearch = Invoke-ApiRequest `
        -Method GET `
        -Uri "$PaymentBaseUrl/api/v1/payments/search?q=$encodedMissingQuery&page=1&size=20" `
        -Headers $paymentHeaders

    $missingTotal = Get-PropertyValue $missingSearch.Body @("total")
    $missingSearchIsValid = (
        $missingSearch.StatusCode -eq 200 -and
        [int]$missingTotal -eq 0
    )

    Assert-TestResult `
        -Name "Search returns no result for unknown payment" `
        -Response $missingSearch `
        -ExpectedStatus @(200) `
        -Condition {
            param($body)
            $missingSearchIsValid
        }

    $invalidPagination = Invoke-ApiRequest `
        -Method GET `
        -Uri "$PaymentBaseUrl/api/v1/payments/search?page=0&size=0" `
        -Headers $paymentHeaders

    Assert-TestResult `
        -Name "Invalid pagination is rejected" `
        -Response $invalidPagination `
        -ExpectedStatus @(400, 422)
}

if ($null -ne $beforeCount -and -not [string]::IsNullOrWhiteSpace($PaymentId)) {
    $afterCountResponse = Invoke-ApiRequest `
        -Method GET `
        -Uri "$ElasticsearchUrl/$ElasticsearchIndex/_count" `
        -Headers $elasticsearchHeaders

    $afterCount = Get-PropertyValue `
        -Object $afterCountResponse.Body `
        -Names @("count")

    if ($null -ne $afterCount) {
        Assert-TestResult `
            -Name "Elasticsearch count remains readable after tests" `
            -Response $afterCountResponse `
            -ExpectedStatus @(200) `
            -Condition {
                param($body)
                $null -ne (Get-PropertyValue $body @("count"))
            }
    }
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Tests run: $script:Total"
Write-Host "Failures:  $script:Failures"

if ($script:Failures -eq 0) {
    Write-Host "RESULT: PASS" -ForegroundColor Green
    exit 0
}

Write-Host "RESULT: FAIL" -ForegroundColor Red
exit 1
