# filename: mercha.ps1
# Code Generated by Sidekick is for learning and experimentation purposes only.

# ============================================================================
# CONFIGURATION
# ============================================================================
$API_GATEWAY   = "http://localhost:8080"
$FRAUD_SERVICE = "http://localhost:8004"
$SECRET_KEY    = "sk_test_123"

$pass            = 0
$fail            = 0
$results         = @()
$AUTH_PAYMENT_ID = $null
$VOID_ID         = $null
$abort           = $false

function Write-Header {
    param([string]$t)
    Write-Host ""
    Write-Host ("="*70) -ForegroundColor Cyan
    Write-Host "  $t" -ForegroundColor Cyan
    Write-Host ("="*70) -ForegroundColor Cyan
}

function Pass {
    param([string]$t)
    Write-Host "  [PASS] $t" -ForegroundColor Green
    $script:pass++
    $script:results += [PSCustomObject]@{ Test=$t; Result="PASS" }
}

function Fail {
    param([string]$t, [string]$e="")
    Write-Host "  [FAIL] $t" -ForegroundColor Red
    if ($e -ne "") { Write-Host "         $e" -ForegroundColor DarkRed }
    $script:fail++
    $script:results += [PSCustomObject]@{ Test=$t; Result="FAIL: $e" }
}

function New-IdempotencyKey {
    return "merch_$(Get-Date -Format 'yyyyMMddHHmmss')_$([System.Guid]::NewGuid().ToString('N').Substring(0,6))"
}

$merchantHeaders = @{
    "Content-Type"  = "application/json"
    "Authorization" = "Bearer $SECRET_KEY"
}

Write-Host ""
Write-Host ("="*70) -ForegroundColor Cyan
Write-Host "  MERCHANT FLOW - COMPLETE TEST SUITE" -ForegroundColor Cyan
Write-Host ("="*70) -ForegroundColor Cyan

# ============================================================================
# TEST 1: HEALTH CHECK
# ============================================================================
Write-Header "TEST 1: HEALTH CHECK"

Write-Host "`n  Checking API Gateway..." -ForegroundColor Yellow
try {
    $h = Invoke-RestMethod -Uri "$API_GATEWAY/health" -Method GET -TimeoutSec 5
    if ($h.status -eq "ok" -or $h.status -eq "up") { Pass "API Gateway healthy" }
    if ($h.status -ne "ok" -and $h.status -ne "up") { Fail "API Gateway unhealthy - status: $($h.status)" }
} catch {
    Fail "API Gateway unreachable" "$_"
    $abort = $true
}

if ($abort) {
    Write-Host "`n  [ABORTED] Gateway unreachable. Fix connectivity and re-run." -ForegroundColor Red
    exit 0
}

# ============================================================================
# TEST 2: AUTHORIZATION ONLY (capture=false)
# ============================================================================
Write-Header "TEST 2: CREATE PAYMENT - AUTHORIZATION ONLY (capture=false)"

Write-Host "`n  Authorizing 150 USD Visa..." -ForegroundColor Yellow
try {
    $h2 = $merchantHeaders.Clone()
    $h2["Idempotency-Key"] = New-IdempotencyKey

    $body = @{
        amount      = 15000
        currency    = "usd"
        customer    = @{ email="customer@example.com"; name="John Doe"; phone="+1234567890" }
        card        = @{ number="4242424242424242"; exp_month=12; exp_year=2026; cvc="123" }
        order_id    = "order_auth_$(Get-Date -Format 'yyyyMMddHHmmss')"
        description = "Authorization test - annual subscription"
        metadata    = @{ plan="enterprise"; seats=10; billing="annual" }
        capture     = $false
    } | ConvertTo-Json

    $authPayment     = Invoke-RestMethod -Uri "$API_GATEWAY/v1/merchant/payment_intents" `
        -Method POST -Headers $h2 -Body $body -TimeoutSec 15
    $AUTH_PAYMENT_ID = $authPayment.payment_id

    if ($AUTH_PAYMENT_ID) {
        Pass "Payment authorized"
        Write-Host "    Payment ID : $AUTH_PAYMENT_ID" -ForegroundColor White
        Write-Host "    Status     : $($authPayment.status)" -ForegroundColor White
        Write-Host "    Auth Code  : $($authPayment.authorization_code)" -ForegroundColor White
        Write-Host "    Amount     : `$$($authPayment.amount/100)" -ForegroundColor White
        Write-Host "    Card       : $($authPayment.card_brand) **** $($authPayment.card_last4)" -ForegroundColor White
    }
    if (-not $AUTH_PAYMENT_ID) {
        Fail "No payment ID returned"
        $abort = $true
    }
} catch {
    Fail "Authorization failed" "$($_.ErrorDetails.Message)"
    $abort = $true
}

if ($abort) {
    Write-Host "`n  [ABORTED] Cannot continue without a valid payment. Fix and re-run." -ForegroundColor Red
    exit 0
}

# ============================================================================
# TEST 3: RETRIEVE PAYMENT
# ============================================================================
Write-Header "TEST 3: RETRIEVE PAYMENT"

Write-Host "`n  Fetching payment details..." -ForegroundColor Yellow
try {
    $details = Invoke-RestMethod -Uri "$API_GATEWAY/v1/merchant/payments/$AUTH_PAYMENT_ID" `
        -Method GET -Headers $merchantHeaders -TimeoutSec 10

    if ($details.payment_id -eq $AUTH_PAYMENT_ID) {
        Pass "Payment retrieved"
        Write-Host "    Status   : $($details.status)" -ForegroundColor White
        Write-Host "    Amount   : `$$($details.amount/100)" -ForegroundColor White
        Write-Host "    Captured : `$$($details.amount_captured/100)" -ForegroundColor White
        Write-Host "    Refunded : `$$($details.amount_refunded/100)" -ForegroundColor White
        Write-Host "    Order ID : $($details.order_id)" -ForegroundColor White
    }
    if ($details.payment_id -ne $AUTH_PAYMENT_ID) { Fail "Wrong payment returned - ID mismatch" }
} catch { Fail "Retrieval failed" "$_" }

# ============================================================================
# TEST 4: FULL CAPTURE
# ============================================================================
Write-Header "TEST 4: FULL CAPTURE"

Write-Host "`n  Capturing full 150 USD..." -ForegroundColor Yellow
try {
    $body = @{ payment_id=$AUTH_PAYMENT_ID; amount=$null } | ConvertTo-Json
    $capture = Invoke-RestMethod -Uri "$API_GATEWAY/v1/merchant/captures" `
        -Method POST -Headers $merchantHeaders -Body $body -TimeoutSec 15

    if ($capture.status -eq "captured") {
        Pass "Full capture successful"
        Write-Host "    Status    : $($capture.status)" -ForegroundColor White
        Write-Host "    Captured  : `$$($capture.captured_amount/100)" -ForegroundColor White
        Write-Host "    Reference : $($capture.capture_reference)" -ForegroundColor White
    }
    if ($capture.status -ne "captured") { Fail "Unexpected capture status: $($capture.status)" }
} catch { Fail "Capture failed" "$_" }

# ============================================================================
# TEST 5: PARTIAL REFUND
# ============================================================================
Write-Header "TEST 5: PARTIAL REFUND"

Write-Host "`n  Refunding 50 USD of 150 USD..." -ForegroundColor Yellow
try {
    $body = @{
        payment_id = $AUTH_PAYMENT_ID
        amount     = 5000
        reason     = "Customer returned 1 item"
        metadata   = @{ type="partial"; items_returned=@("item_001") }
    } | ConvertTo-Json

    $refund = Invoke-RestMethod -Uri "$API_GATEWAY/v1/merchant/refunds" `
        -Method POST -Headers $merchantHeaders -Body $body -TimeoutSec 15

    if ($refund.status -eq "succeeded") {
        Pass "Partial refund processed"
        Write-Host "    Refund ID : $($refund.id)" -ForegroundColor White
        Write-Host "    Amount    : `$$($refund.amount/100)" -ForegroundColor White
        Write-Host "    Status    : $($refund.status)" -ForegroundColor White
    }
    if ($refund.status -ne "succeeded") { Fail "Unexpected refund status: $($refund.status)" }
} catch { Fail "Partial refund failed" "$_" }

# ============================================================================
# TEST 6: FULL REFUND (new payment)
# ============================================================================
Write-Header "TEST 6: FULL REFUND"

Write-Host "`n  Creating new payment for full refund test..." -ForegroundColor Yellow
try {
    $h6 = $merchantHeaders.Clone()
    $h6["Idempotency-Key"] = New-IdempotencyKey

    $body = @{
        amount   = 10000
        currency = "usd"
        customer = @{ email="refund@example.com"; name="Refund Test" }
        card     = @{ number="5555555555554444"; exp_month=12; exp_year=2026; cvc="123" }
        capture  = $true
    } | ConvertTo-Json

    $refundPayment     = Invoke-RestMethod -Uri "$API_GATEWAY/v1/merchant/payment_intents" `
        -Method POST -Headers $h6 -Body $body -TimeoutSec 15
    $REFUND_PAYMENT_ID = $refundPayment.payment_id

    if ($REFUND_PAYMENT_ID) { Pass "Payment created for refund: $REFUND_PAYMENT_ID" }
    if (-not $REFUND_PAYMENT_ID) { Fail "Full refund payment creation failed" }
} catch {
    Fail "Full refund payment creation failed" "$_"
    $REFUND_PAYMENT_ID = $null
}

if ($REFUND_PAYMENT_ID) {
    Start-Sleep -Seconds 2
    Write-Host "`n  Processing full refund..." -ForegroundColor Yellow
    try {
        $body = @{ payment_id=$REFUND_PAYMENT_ID; amount=$null; reason="Full cancellation - customer request" } | ConvertTo-Json
        $fullRefund = Invoke-RestMethod -Uri "$API_GATEWAY/v1/merchant/refunds" `
            -Method POST -Headers $merchantHeaders -Body $body -TimeoutSec 15

        if ($fullRefund.status -eq "succeeded") {
            Pass "Full refund processed"
            Write-Host "    Refund ID : $($fullRefund.id)" -ForegroundColor White
            Write-Host "    Amount    : `$$($fullRefund.amount/100)" -ForegroundColor White
        }
        if ($fullRefund.status -ne "succeeded") { Fail "Unexpected full refund status: $($fullRefund.status)" }
    } catch { Fail "Full refund failed" "$_" }
}
if (-not $REFUND_PAYMENT_ID) { Fail "Full refund skipped - no payment ID" }

# ============================================================================
# TEST 7: PARTIAL CAPTURE
# ============================================================================
Write-Header "TEST 7: PARTIAL CAPTURE"

Write-Host "`n  Authorizing 100 USD then capturing 60 USD..." -ForegroundColor Yellow
try {
    $h7 = $merchantHeaders.Clone()
    $h7["Idempotency-Key"] = New-IdempotencyKey

    $body = @{
        amount   = 10000
        currency = "usd"
        customer = @{ email="partial@example.com"; name="Partial Test" }
        card     = @{ number="4242424242424242"; exp_month=12; exp_year=2026; cvc="123" }
        capture  = $false
    } | ConvertTo-Json

    $partialAuth = Invoke-RestMethod -Uri "$API_GATEWAY/v1/merchant/payment_intents" `
        -Method POST -Headers $h7 -Body $body -TimeoutSec 15
    $PARTIAL_ID  = $partialAuth.payment_id

    if ($PARTIAL_ID) { Pass "Payment authorized for partial capture: $PARTIAL_ID" }
    if (-not $PARTIAL_ID) { Fail "Partial capture auth failed" }
} catch {
    Fail "Partial capture auth failed" "$_"
    $PARTIAL_ID = $null
}

if ($PARTIAL_ID) {
    Start-Sleep -Seconds 1
    try {
        $body = @{ payment_id=$PARTIAL_ID; amount=6000 } | ConvertTo-Json
        $partCapture = Invoke-RestMethod -Uri "$API_GATEWAY/v1/merchant/captures" `
            -Method POST -Headers $merchantHeaders -Body $body -TimeoutSec 15

        if ($partCapture.status -eq "partially_captured") {
            Pass "Partial capture successful"
            Write-Host "    Captured : `$$($partCapture.captured_amount/100) of `$100.00" -ForegroundColor White
        }
        if ($partCapture.status -ne "partially_captured") { Fail "Unexpected partial capture status: $($partCapture.status)" }
    } catch { Fail "Partial capture failed" "$_" }
}
if (-not $PARTIAL_ID) { Fail "Partial capture skipped - no auth payment" }

# ============================================================================
# TEST 8: VOID
# ============================================================================
Write-Header "TEST 8: VOID AUTHORIZED PAYMENT"

Write-Host "`n  Authorizing 80 USD then voiding..." -ForegroundColor Yellow
try {
    $h8 = $merchantHeaders.Clone()
    $h8["Idempotency-Key"] = New-IdempotencyKey

    $body = @{
        amount   = 8000
        currency = "usd"
        customer = @{ email="void@example.com"; name="Void Test" }
        card     = @{ number="5555555555554444"; exp_month=12; exp_year=2026; cvc="123" }
        capture  = $false
    } | ConvertTo-Json

    $voidAuth = Invoke-RestMethod -Uri "$API_GATEWAY/v1/merchant/payment_intents" `
        -Method POST -Headers $h8 -Body $body -TimeoutSec 15
    $VOID_ID  = $voidAuth.payment_id

    if ($VOID_ID) { Pass "Payment authorized for void: $VOID_ID" }
    if (-not $VOID_ID) { Fail "Void auth failed" }
} catch {
    Fail "Void auth failed" "$_"
    $VOID_ID = $null
}

if ($VOID_ID) {
    Start-Sleep -Seconds 1
    try {
        $body = @{ payment_id=$VOID_ID; reason="Customer cancelled order" } | ConvertTo-Json
        $void = Invoke-RestMethod -Uri "$API_GATEWAY/v1/merchant/voids" `
            -Method POST -Headers $merchantHeaders -Body $body -TimeoutSec 15

        if ($void.status -eq "voided") {
            Pass "Payment voided"
            Write-Host "    Void Reference : $($void.void_reference)" -ForegroundColor White
        }
        if ($void.status -ne "voided") { Fail "Unexpected void status: $($void.status)" }
    } catch { Fail "Void failed" "$_" }
}
if (-not $VOID_ID) { Fail "Void skipped - no auth payment" }

# ============================================================================
# TEST 9: IMMEDIATE CAPTURE (capture=true)
# ============================================================================
Write-Header "TEST 9: IMMEDIATE CAPTURE (capture=true)"

Write-Host "`n  Creating payment with auto-capture..." -ForegroundColor Yellow
try {
    $h9 = $merchantHeaders.Clone()
    $h9["Idempotency-Key"] = New-IdempotencyKey

    $body = @{
        amount   = 12000
        currency = "usd"
        customer = @{ email="auto@example.com"; name="Auto Capture" }
        card     = @{ number="4242424242424242"; exp_month=12; exp_year=2026; cvc="123" }
        capture  = $true
    } | ConvertTo-Json

    $immediate = Invoke-RestMethod -Uri "$API_GATEWAY/v1/merchant/payment_intents" `
        -Method POST -Headers $h9 -Body $body -TimeoutSec 15

    if ($immediate.payment_id) {
        Pass "Auto-capture payment created"
        Write-Host "    Payment ID : $($immediate.payment_id)" -ForegroundColor White
        Write-Host "    Status     : $($immediate.status)" -ForegroundColor White
        Write-Host "    Captured   : `$$($immediate.amount_captured/100)" -ForegroundColor White
    }
    if (-not $immediate.payment_id) { Fail "Auto-capture payment ID missing" }
} catch { Fail "Auto-capture failed" "$_" }

# ============================================================================
# TEST 10: IDEMPOTENCY
# ============================================================================
Write-Header "TEST 10: IDEMPOTENCY"

Write-Host "`n  Sending same request twice with same idempotency key..." -ForegroundColor Yellow
try {
    $iKey = "idem_$(Get-Date -Format 'yyyyMMddHHmmss')"
    $iHeaders = $merchantHeaders.Clone()
    $iHeaders["Idempotency-Key"] = $iKey

    $iBody = @{
        amount   = 3000
        currency = "usd"
        customer = @{ email="idem@example.com"; name="Idem Test" }
        card     = @{ number="5555555555554444"; exp_month=12; exp_year=2026; cvc="123" }
        capture  = $false
    } | ConvertTo-Json

    $first  = Invoke-RestMethod -Uri "$API_GATEWAY/v1/merchant/payment_intents" `
        -Method POST -Headers $iHeaders -Body $iBody -TimeoutSec 15
    Start-Sleep -Seconds 1
    $second = Invoke-RestMethod -Uri "$API_GATEWAY/v1/merchant/payment_intents" `
        -Method POST -Headers $iHeaders -Body $iBody -TimeoutSec 15

    if ($first.payment_id -eq $second.payment_id) {
        Pass "Idempotency working - same payment ID returned both times"
        Write-Host "    Payment ID : $($first.payment_id)" -ForegroundColor White
    }
    if ($first.payment_id -ne $second.payment_id) {
        Fail "Idempotency broken - different payment IDs returned"
        Write-Host "    First  : $($first.payment_id)" -ForegroundColor DarkRed
        Write-Host "    Second : $($second.payment_id)" -ForegroundColor DarkRed
    }
} catch { Fail "Idempotency test failed" "$_" }

# ============================================================================
# TEST 11: ERROR HANDLING
# ============================================================================
Write-Header "TEST 11: ERROR HANDLING"

Write-Host "`n  Testing invalid secret key..." -ForegroundColor Yellow
try {
    Invoke-RestMethod -Uri "$API_GATEWAY/v1/merchant/payments/pi_test" `
        -Method GET -Headers @{ "Authorization"="Bearer sk_invalid_999" } -TimeoutSec 10
    Fail "Invalid key should have been rejected"
} catch {
    $code = 0
    if ($_.Exception.Response) { $code = [int]$_.Exception.Response.StatusCode }
    if ($code -eq 401) { Pass "Invalid key rejected (401)" }
    if ($code -ne 401 -and $code -gt 0) { Pass "Invalid key rejected (HTTP $code)" }
    if ($code -eq 0) { Pass "Invalid key rejected (no response)" }
}

Write-Host "`n  Testing double-capture on same payment..." -ForegroundColor Yellow
try {
    $body = @{ payment_id=$AUTH_PAYMENT_ID } | ConvertTo-Json
    Invoke-RestMethod -Uri "$API_GATEWAY/v1/merchant/captures" `
        -Method POST -Headers $merchantHeaders -Body $body -TimeoutSec 10
    Fail "Double-capture should have been rejected"
} catch { Pass "Double-capture rejected" }

Write-Host "`n  Testing void on already-captured payment..." -ForegroundColor Yellow
try {
    $body = @{ payment_id=$AUTH_PAYMENT_ID; reason="test void" } | ConvertTo-Json
    Invoke-RestMethod -Uri "$API_GATEWAY/v1/merchant/voids" `
        -Method POST -Headers $merchantHeaders -Body $body -TimeoutSec 10
    Fail "Void of captured payment should have been rejected"
} catch { Pass "Void of captured payment rejected" }

Write-Host "`n  Testing over-refund..." -ForegroundColor Yellow
try {
    $body = @{ payment_id=$AUTH_PAYMENT_ID; amount=999999 } | ConvertTo-Json
    Invoke-RestMethod -Uri "$API_GATEWAY/v1/merchant/refunds" `
        -Method POST -Headers $merchantHeaders -Body $body -TimeoutSec 10
    Fail "Over-refund should have been rejected"
} catch { Pass "Over-refund rejected" }

Write-Host "`n  Testing non-existent payment lookup..." -ForegroundColor Yellow
try {
    Invoke-RestMethod -Uri "$API_GATEWAY/v1/merchant/payments/pi_nonexistent_12345" `
        -Method GET -Headers $merchantHeaders -TimeoutSec 10
    Fail "Non-existent payment should have been rejected"
} catch {
    $code = 0
    if ($_.Exception.Response) { $code = [int]$_.Exception.Response.StatusCode }
    if ($code -eq 404) { Pass "Non-existent payment rejected (404)" }
    if ($code -ne 404 -and $code -gt 0) { Pass "Non-existent payment rejected (HTTP $code)" }
    if ($code -eq 0) { Pass "Non-existent payment rejected" }
}

# ============================================================================
# FINAL SUMMARY
# ============================================================================
Write-Host ""
Write-Host ("="*70) -ForegroundColor Cyan
Write-Host "  FINAL RESULTS" -ForegroundColor Cyan
Write-Host ("="*70) -ForegroundColor Cyan
Write-Host ""
Write-Host "  Total : $($pass + $fail)" -ForegroundColor White
Write-Host "  PASS  : $pass"             -ForegroundColor Green
Write-Host "  FAIL  : $fail"             -ForegroundColor Red
Write-Host ""
Write-Host "  Key IDs:" -ForegroundColor Cyan
Write-Host "    Auth Payment : $AUTH_PAYMENT_ID" -ForegroundColor White
Write-Host "    Void Payment : $VOID_ID"          -ForegroundColor White
Write-Host ""
if ($fail -eq 0) { Write-Host "  ALL MERCHANT TESTS PASSED" -ForegroundColor Green }
if ($fail -gt 0) { Write-Host "  SOME TESTS FAILED - review output above" -ForegroundColor Yellow }

Write-Host ""
Write-Host "Detailed Results:" -ForegroundColor Cyan
$results | Format-Table -AutoSize
