# Code Generated by Sidekick is for learning and experimentation purposes only.
$region = "us-east-2"
$namespace = "pdf-gen"
$rdsEndpoint = "prod-postgres.cveg4qam02d9.us-east-2.rds.amazonaws.com"
$rdsSecretArn = "arn:aws:secretsmanager:us-east-2:667383782466:secret:rds!db-b196e661-7df0-4000-ac74-a8c7950c1053-QxI6Zr"

$secretJson = aws secretsmanager get-secret-value `
  --secret-id $rdsSecretArn `
  --region $region `
  --query SecretString `
  --output text

$db = $secretJson | ConvertFrom-Json

$port = if ($db.port -and "$($db.port)".Trim() -ne "") { "$($db.port)" } else { "5432" }
$dbName = if ($db.dbname -and "$($db.dbname)".Trim() -ne "") { "$($db.dbname)" } else { "production_db" }
$encodedPassword = [System.Uri]::EscapeDataString($db.password)

$dbUrl = "postgresql://$($db.username):$encodedPassword@${rdsEndpoint}:$port/$dbName"

kubectl create namespace $namespace --dry-run=client -o yaml | kubectl apply -f -

kubectl -n $namespace delete secret pdf-generator-env --ignore-not-found

kubectl -n $namespace create secret generic pdf-generator-env `
  --from-literal=DATABASE_URL=$dbUrl `
  --from-literal=REDIS_HOST=cache `
  --from-literal=REDIS_PORT=6379 `
  --from-literal=BUCKET_NAME=pdf-generator-sandesh `
  --from-literal=AWS_DEFAULT_REGION=us-east-2 `
  --from-literal=RDS_SECRET_ARN=$rdsSecretArn
