# filename: app/schemas/event.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

from pydantic import BaseModel, UUID4, Field, ConfigDict
from datetime import datetime
from typing import Optional, List


class EventBase(BaseModel):
    event_name: str = Field(..., min_length=1, max_length=255)
    event_date: datetime
    venue: str = Field(..., min_length=1, max_length=255)
    total_seats: int = Field(..., gt=0)


class EventCreate(EventBase):
    pass


class EventUpdate(BaseModel):
    event_name: Optional[str] = Field(None, min_length=1, max_length=255)
    event_date: Optional[datetime] = None
    venue: Optional[str] = Field(None, min_length=1, max_length=255)
    total_seats: Optional[int] = Field(None, gt=0)


class EventResponse(EventBase):
    event_id: UUID4
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


class EventWithSeats(EventResponse):
    available_seats: int
    booked_seats: int
    reserved_seats: int


class EventListResponse(BaseModel):
    events: List[EventResponse]
    total: int
    page: int
    page_size: int
