# Code Generated by Sidekick is for learning and experimentation purposes only.

from datetime import datetime

from sqlalchemy import JSON, Boolean, Column, DateTime, Float, Integer, String, Text

# ✅ Import Base from db, not define it here
from fraud_service.app.db import Base


class FraudCheck(Base):
    __tablename__ = "fraud_checks"

    id = Column(String, primary_key=True)
    payment_id = Column(String, nullable=False, index=True)
    merchant_id = Column(String, nullable=False, index=True)
    amount = Column(Integer, nullable=False)
    currency = Column(String(10), nullable=False)

    # Card info
    card_last4 = Column(String(4))
    card_brand = Column(String(20))
    card_fingerprint = Column(String(64), index=True)
    card_exp_month = Column(Integer)
    card_exp_year = Column(Integer)

    # Customer info
    customer_id = Column(String, index=True)
    customer_email = Column(String, index=True)
    ip_address = Column(String(45), index=True)
    user_agent = Column(Text)

    # Results
    risk_score = Column(Integer, nullable=False)
    rules_score = Column(Integer, default=0)
    ml_score = Column(Float, default=0.0)
    risk_level = Column(String(10), nullable=False)
    allowed = Column(Boolean, nullable=False)
    block_reason = Column(Text, nullable=True)
    triggered_rules = Column(JSON, default=list)
    review_required = Column(Boolean, default=False)

    created_at = Column(DateTime, default=datetime.utcnow, index=True)


class Blocklist(Base):
    __tablename__ = "blocklist"

    id = Column(String, primary_key=True)
    type = Column(String(30), nullable=False, index=True)
    value = Column(String(255), nullable=False, index=True)
    reason = Column(String(255), nullable=False)
    added_by = Column(String(100), nullable=False)
    expires_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)


class MLTrainingSample(Base):
    __tablename__ = "ml_training_samples"

    id = Column(String, primary_key=True)
    fraud_check_id = Column(String, index=True)
    payment_id = Column(String, index=True)

    # Features
    amount = Column(Integer)
    hour_of_day = Column(Integer)
    day_of_week = Column(Integer)
    card_velocity_1h = Column(Integer, default=0)
    ip_velocity_1h = Column(Integer, default=0)
    customer_tx_count = Column(Integer, default=0)
    customer_failed_count = Column(Integer, default=0)
    is_first_card_use = Column(Boolean, default=True)
    is_round_amount = Column(Boolean, default=False)
    is_micro_amount = Column(Boolean, default=False)
    email_domain_risk = Column(Float, default=0.0)
    card_exp_months_remaining = Column(Integer, default=0)

    # Label
    is_fraud = Column(Boolean, nullable=True)
    confirmed_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
