# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: notification-service/endpoints.py

import secrets
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func

from database import get_db
from dispatcher import Dispatcher
from models import Notification, MerchantWebhook, WebhookDelivery
from schemas import (
    NotifyRequest, DispatchResult, NotificationResponse,
    WebhookRegisterRequest, WebhookResponse, WebhookUpdateRequest,
    WebhookDeliveryResponse, StatsResponse,
)

router = APIRouter()
_dispatcher = Dispatcher()


# ── Core dispatch ─────────────────────────────────────────────────────────────
@router.post("/notify", response_model=DispatchResult)
async def notify(req: NotifyRequest, db: AsyncSession = Depends(get_db)):
    return await _dispatcher.dispatch(req, db)


# ── Health & Stats ────────────────────────────────────────────────────────────
@router.get("/health")
async def health():
    return {"status": "ok", "service": "notification-service"}


@router.get("/stats", response_model=StatsResponse)
async def stats(db: AsyncSession = Depends(get_db)):
    total  = await db.scalar(select(func.count(Notification.id)))
    sent   = await db.scalar(select(func.count(Notification.id)).where(Notification.status == "sent"))
    failed = await db.scalar(select(func.count(Notification.id)).where(Notification.status == "failed"))
    pending= await db.scalar(select(func.count(Notification.id)).where(Notification.status == "pending"))

    total_wh  = await db.scalar(select(func.count(MerchantWebhook.id)))
    active_wh = await db.scalar(select(func.count(MerchantWebhook.id)).where(MerchantWebhook.is_active == True))  # noqa: E712
    total_del = await db.scalar(select(func.count(WebhookDelivery.id)))

    return StatsResponse(
        total_notifications=total or 0,
        sent=sent or 0,
        failed=failed or 0,
        pending=pending or 0,
        total_webhooks=total_wh or 0,
        active_webhooks=active_wh or 0,
        total_deliveries=total_del or 0,
    )


# ── Notifications lookup ──────────────────────────────────────────────────────
@router.get("/notifications/{notification_id}", response_model=NotificationResponse)
async def get_notification(notification_id: str, db: AsyncSession = Depends(get_db)):
    n = await db.get(Notification, notification_id)
    if not n:
        raise HTTPException(404, "Notification not found")
    return n


@router.get("/notifications/payment/{payment_id}", response_model=list[NotificationResponse])
async def get_payment_notifications(payment_id: str, db: AsyncSession = Depends(get_db)):
    result = await db.execute(
        select(Notification).where(Notification.payment_id == payment_id)
        .order_by(Notification.created_at.desc())
    )
    return result.scalars().all()


# ── Webhook management ────────────────────────────────────────────────────────
@router.post("/webhooks/register", response_model=WebhookResponse, status_code=201)
async def register_webhook(req: WebhookRegisterRequest, db: AsyncSession = Depends(get_db)):
    wh = MerchantWebhook(
        merchant_id = req.merchant_id,
        url         = req.url,
        description = req.description,
        events      = ",".join(req.events),
        secret      = secrets.token_hex(32),   # per-webhook secret for HMAC signing
    )
    db.add(wh)
    await db.commit()
    await db.refresh(wh)
    return wh


@router.get("/webhooks/{merchant_id}", response_model=list[WebhookResponse])
async def list_webhooks(merchant_id: str, db: AsyncSession = Depends(get_db)):
    result = await db.execute(
        select(MerchantWebhook).where(MerchantWebhook.merchant_id == merchant_id)
        .order_by(MerchantWebhook.created_at.desc())
    )
    return result.scalars().all()


@router.patch("/webhooks/{webhook_id}", response_model=WebhookResponse)
async def update_webhook(
    webhook_id: str, req: WebhookUpdateRequest, db: AsyncSession = Depends(get_db)
):
    wh = await db.get(MerchantWebhook, webhook_id)
    if not wh:
        raise HTTPException(404, "Webhook not found")
    if req.url is not None:         wh.url = req.url
    if req.description is not None: wh.description = req.description
    if req.events is not None:      wh.events = ",".join(req.events)
    if req.is_active is not None:   wh.is_active = req.is_active
    await db.commit()
    await db.refresh(wh)
    return wh


@router.delete("/webhooks/{webhook_id}", status_code=204)
async def delete_webhook(webhook_id: str, db: AsyncSession = Depends(get_db)):
    wh = await db.get(MerchantWebhook, webhook_id)
    if not wh:
        raise HTTPException(404, "Webhook not found")
    await db.delete(wh)
    await db.commit()


@router.post("/webhooks/{webhook_id}/rotate-secret", response_model=WebhookResponse)
async def rotate_webhook_secret(webhook_id: str, db: AsyncSession = Depends(get_db)):
    wh = await db.get(MerchantWebhook, webhook_id)
    if not wh:
        raise HTTPException(404, "Webhook not found")
    wh.secret = secrets.token_hex(32)
    await db.commit()
    await db.refresh(wh)
    return wh


# ── Webhook delivery history ──────────────────────────────────────────────────
@router.get("/webhooks/{webhook_id}/deliveries", response_model=list[WebhookDeliveryResponse])
async def get_webhook_deliveries(
    webhook_id: str,
    limit: int = 50,
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(WebhookDelivery)
        .where(WebhookDelivery.webhook_id == webhook_id)
        .order_by(WebhookDelivery.created_at.desc())
        .limit(limit)
    )
    return result.scalars().all()
