# Code Generated by Sidekick is for learning and experimentation purposes only.

import enum
import uuid
from datetime import UTC, datetime

from database import Base
from sqlalchemy import JSON, Boolean, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship


def utcnow():
    return datetime.now(UTC)

def new_id(prefix: str) -> str:
    return f"{prefix}_{uuid.uuid4().hex[:16]}"


class ChannelType(enum.StrEnum):
    EMAIL   = "email"
    SMS     = "sms"
    WEBHOOK = "webhook"


class DeliveryStatus(enum.StrEnum):
    PENDING   = "pending"
    SENT      = "sent"
    FAILED    = "failed"
    RETRYING  = "retrying"


class NotificationEvent(enum.StrEnum):
    PAYMENT_AUTHORIZED = "payment.authorized"
    PAYMENT_CAPTURED   = "payment.captured"
    PAYMENT_FAILED     = "payment.failed"
    PAYMENT_REFUNDED   = "payment.refunded"
    PAYMENT_VOIDED     = "payment.voided"
    FRAUD_DETECTED     = "fraud.detected"


class Notification(Base):
    __tablename__ = "notifications"

    id: Mapped[str] = mapped_column(String(40), primary_key=True,
                                    default=lambda: new_id("notif"))
    payment_id:  Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    merchant_id: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    event:       Mapped[str] = mapped_column(String(50),  nullable=False)
    channel:     Mapped[str] = mapped_column(String(20),  nullable=False)
    recipient:   Mapped[str] = mapped_column(String(200), nullable=False)

    status:      Mapped[str] = mapped_column(String(20),
                                             default=DeliveryStatus.PENDING)
    attempts:    Mapped[int] = mapped_column(Integer, default=0)
    max_attempts:Mapped[int] = mapped_column(Integer, default=3)

    subject:     Mapped[str | None] = mapped_column(String(300), nullable=True)
    body:        Mapped[str | None] = mapped_column(Text, nullable=True)
    metadata_:   Mapped[dict | None] = mapped_column("metadata", JSON, nullable=True)

    error:       Mapped[str | None] = mapped_column(Text, nullable=True)
    sent_at:     Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at:  Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    updated_at:  Mapped[datetime] = mapped_column(DateTime(timezone=True),
                                                  default=utcnow, onupdate=utcnow)


class MerchantWebhook(Base):
    __tablename__ = "merchant_webhooks"

    id:          Mapped[str] = mapped_column(String(40), primary_key=True,
                                             default=lambda: new_id("wh"))
    merchant_id: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    url:         Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str | None] = mapped_column(String(200), nullable=True)

    # Comma-separated list of subscribed events, e.g. "payment.captured,payment.refunded"
    events:      Mapped[str] = mapped_column(Text, default="*")
    secret:      Mapped[str] = mapped_column(String(100), nullable=False)   # per-webhook HMAC secret
    is_active:   Mapped[bool] = mapped_column(Boolean, default=True)

    total_deliveries: Mapped[int] = mapped_column(Integer, default=0)
    failed_deliveries: Mapped[int] = mapped_column(Integer, default=0)

    created_at:  Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    updated_at:  Mapped[datetime] = mapped_column(DateTime(timezone=True),
                                                  default=utcnow, onupdate=utcnow)

    deliveries: Mapped[list["WebhookDelivery"]] = relationship(
        back_populates="webhook", cascade="all, delete-orphan",
    )


class WebhookDelivery(Base):
    __tablename__ = "webhook_deliveries"

    id:          Mapped[str] = mapped_column(String(40), primary_key=True,
                                             default=lambda: new_id("whdel"))
    webhook_id:  Mapped[str] = mapped_column(ForeignKey("merchant_webhooks.id"), index=True)
    payment_id:  Mapped[str] = mapped_column(String(100), nullable=False)
    event:       Mapped[str] = mapped_column(String(50),  nullable=False)

    status:          Mapped[str] = mapped_column(String(20), default=DeliveryStatus.PENDING)
    attempts:        Mapped[int] = mapped_column(Integer, default=0)
    http_status:     Mapped[int | None] = mapped_column(Integer, nullable=True)
    response_body:   Mapped[str | None] = mapped_column(Text, nullable=True)
    error:           Mapped[str | None] = mapped_column(Text, nullable=True)
    payload:         Mapped[dict | None] = mapped_column(JSON, nullable=True)

    delivered_at:    Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    next_retry_at:   Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at:      Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)

    webhook: Mapped["MerchantWebhook"] = relationship(back_populates="deliveries")
