# Code Generated by Sidekick is for learning and experimentation purposes only.

from datetime import UTC, datetime

from sqlalchemy.orm import Session

from fraud_service.app.models.fraud import Blocklist
from fraud_service.app.schemas.fraud import RuleResult


class BlocklistRules:

    def _query(self, db: Session, type_: str, value: str):
        return (
            db.query(Blocklist)
            .filter(Blocklist.type == type_, Blocklist.value == value.lower())
            .filter(
                (Blocklist.expires_at.is_(None)) |
                (Blocklist.expires_at > datetime.now(tz=UTC)),
            )
            .first()
        )

    def check_card(self, db: Session, fingerprint: str) -> RuleResult:
        entry = self._query(db, "card_fingerprint", fingerprint)
        if entry:
            return RuleResult(
                rule_name="card_blocklisted",
                triggered=True,
                score_impact=100,
                reason=f"Card blocklisted: {entry.reason}",
            )
        return RuleResult(rule_name="card_blocklist", triggered=False, score_impact=0)

    def check_ip(self, db: Session, ip: str) -> RuleResult:
        if not ip:
            return RuleResult(rule_name="ip_blocklist", triggered=False, score_impact=0)
        entry = self._query(db, "ip", ip)
        if entry:
            return RuleResult(
                rule_name="ip_blocklisted",
                triggered=True,
                score_impact=80,
                reason=f"IP blocklisted: {entry.reason}",
            )
        return RuleResult(rule_name="ip_blocklist", triggered=False, score_impact=0)

    def check_email(self, db: Session, email: str) -> RuleResult:
        entry = self._query(db, "email", email)
        if entry:
            return RuleResult(
                rule_name="email_blocklisted",
                triggered=True,
                score_impact=90,
                reason=f"Email blocklisted: {entry.reason}",
            )
        return RuleResult(rule_name="email_blocklist", triggered=False, score_impact=0)

    def check_customer(self, db: Session, customer_id: str) -> RuleResult:
        entry = self._query(db, "customer_id", customer_id)
        if entry:
            return RuleResult(
                rule_name="customer_blocklisted",
                triggered=True,
                score_impact=95,
                reason=f"Customer blocklisted: {entry.reason}",
            )
        return RuleResult(rule_name="customer_blocklist", triggered=False, score_impact=0)
