# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: Payment/main.py

import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI
from sqlalchemy import text

from Payment.api.endpoints import router as payment_router
from Payment.config.database import Base, DATABASE_URL, SessionLocal, engine
from Payment.models import payment  # noqa: F401

logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("Payment Service Starting...")

    try:
        db_host = DATABASE_URL.split("@")[1] if "@" in DATABASE_URL else "local"
        logger.info(f"Target Database Host: {db_host}")
    except Exception:
        logger.info("Target Database Host: Configured via environment string")

    try:
        db = SessionLocal()
        db.execute(text("SELECT 1"))
        db.close()
        logger.info("Database connection verification successful")
    except Exception as e:
        logger.critical(f"Database connection failed during startup: {str(e)}")
        raise e

    Base.metadata.create_all(bind=engine)
    logger.info("Database tables ensured")

    yield

    logger.info("Payment Service Shutting down...")


app = FastAPI(title="Payment Processing Service", version="1.0.0", lifespan=lifespan)


@app.get("/health")
async def health():
    return {"status": "ok"}


app.include_router(payment_router, prefix="/api/v1")
