# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: Payment/search.py

import asyncio
import logging
import os
from collections.abc import Mapping
from typing import Any

from elasticsearch import AsyncElasticsearch
from fastapi import FastAPI, HTTPException, Request

logger = logging.getLogger(__name__)

INDEX_PREFIX = os.getenv("ELASTICSEARCH_INDEX_PREFIX", "payment-gt")
PAYMENTS_INDEX = f"{INDEX_PREFIX}-payments-v1"

PAYMENT_MAPPINGS = {
    "dynamic": False,
    "properties": {
        "payment_id": {"type": "keyword"},
        "merchant_id": {"type": "keyword"},
        "customer_id": {"type": "keyword"},
        "order_id": {"type": "keyword"},
        "booking_id": {"type": "keyword"},
        "cart_id": {"type": "keyword"},
        "status": {"type": "keyword"},
        "currency": {"type": "keyword"},
        "risk_level": {"type": "keyword"},
        "fraud_decision": {"type": "keyword"},
        "failure_code": {"type": "keyword"},
        "amount_minor": {"type": "long"},
        "authorized_amount_minor": {"type": "long"},
        "captured_amount_minor": {"type": "long"},
        "refunded_amount_minor": {"type": "long"},
        "description": {"type": "text"},
        "authorized_at": {"type": "date"},
        "captured_at": {"type": "date"},
        "voided_at": {"type": "date"},
        "created_at": {"type": "date"},
        "updated_at": {"type": "date"},
    },
}


def _read(value: Any, key: str) -> Any:
    if isinstance(value, Mapping):
        return value.get(key)

    return getattr(value, key, None)


def _first(value: Any, *keys: str) -> Any:
    for key in keys:
        result = _read(value, key)

        if result is not None:
            return result

    return None


def _enum_value(value: Any) -> Any:
    return getattr(value, "value", value)


def _keyword(value: Any) -> str | None:
    value = _enum_value(value)

    if value is None:
        return None

    return str(value)


def _integer(value: Any) -> int | None:
    if value is None:
        return None

    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _iso(value: Any) -> str | None:
    if value is None:
        return None

    if hasattr(value, "isoformat"):
        return value.isoformat()

    return str(value)


def _response_body(response: Any) -> Mapping[str, Any]:
    body = getattr(response, "body", response)

    if isinstance(body, Mapping):
        return body

    return {}


def _refresh_value() -> bool | str:
    configured = os.getenv(
        "ELASTICSEARCH_REFRESH",
        "false",
    ).lower()

    if configured == "wait_for":
        return "wait_for"

    return configured in {"true", "1", "yes"}


def create_es_client() -> AsyncElasticsearch:
    url = os.getenv(
        "ELASTICSEARCH_URL",
        "http://localhost:9200",
    )

    return AsyncElasticsearch(
        url,
        request_timeout=5,
        max_retries=3,
        retry_on_timeout=True,
    )


async def wait_for_es(
    es: AsyncElasticsearch,
    attempts: int = 30,
) -> None:
    last_error: Exception | None = None

    for _ in range(attempts):
        try:
            if await es.ping():
                return
        except Exception as exc: # noqa: BLE001
            last_error = exc

        await asyncio.sleep(1)

    if last_error:
        raise RuntimeError(
            "Elasticsearch did not become ready"
        ) from last_error

    raise RuntimeError(
        "Elasticsearch did not become ready"
    )


async def ensure_payment_index(
    es: AsyncElasticsearch,
) -> None:
    exists_response = await es.indices.exists(
        index=PAYMENTS_INDEX,
    )

    if not bool(exists_response):
        await es.indices.create(
            index=PAYMENTS_INDEX,
            mappings=PAYMENT_MAPPINGS,
        )

        logger.info(
            "Created Elasticsearch index: %s",
            PAYMENTS_INDEX,
        )
        return

    # Adds newly introduced fields, such as order_id, to an
    # already-existing development index.
    await es.indices.put_mapping(
        index=PAYMENTS_INDEX,
        properties=PAYMENT_MAPPINGS["properties"],
    )

    logger.info(
        "Verified Elasticsearch index mapping: %s",
        PAYMENTS_INDEX,
    )


async def initialize_search(app: FastAPI) -> None:
    app.state.es = None
    es = create_es_client()

    try:
        await wait_for_es(es)
        await ensure_payment_index(es)

        app.state.es = es

        logger.info(
            "Elasticsearch is ready: %s",
            PAYMENTS_INDEX,
        )
    except Exception:
        await es.close()

        logger.exception(
            "Elasticsearch unavailable; payment service will "
            "continue without search indexing",
        )


async def shutdown_search(app: FastAPI) -> None:
    es = getattr(app.state, "es", None)

    if es is not None:
        await es.close()
        app.state.es = None


def get_es(request: Request) -> AsyncElasticsearch:
    es = getattr(request.app.state, "es", None)

    if es is None:
        raise HTTPException(
            status_code=503,
            detail=(
                "Elasticsearch search is temporarily unavailable"
            ),
        )

    return es


def payment_to_document(payment: Any) -> dict[str, Any]:
    payment_id = _first(
        payment,
        "payment_id",
        "id",
    )

    if payment_id is None:
        raise ValueError(
            "Payment does not contain payment_id or id",
        )

    amount = _first(
        payment,
        "amount_minor",
        "amount",
    )

    authorized_amount = _first(
        payment,
        "authorized_amount_minor",
        "authorized_amount",
    )

    captured_amount = _first(
        payment,
        "captured_amount_minor",
        "amount_captured",
        "captured_amount",
    )

    refunded_amount = _first(
        payment,
        "refunded_amount_minor",
        "amount_refunded",
        "refunded_amount",
    )

    document = {
        "payment_id": str(payment_id),
        "merchant_id": _keyword(
            _first(payment, "merchant_id"),
        ),
        "customer_id": _keyword(
            _first(payment, "customer_id"),
        ),
        "order_id": _keyword(
            _first(payment, "order_id"),
        ),
        "booking_id": _keyword(
            _first(payment, "booking_id"),
        ),
        "cart_id": _keyword(
            _first(payment, "cart_id"),
        ),
        "status": _keyword(
            _first(payment, "status"),
        ),
        "currency": _keyword(
            _first(payment, "currency"),
        ),
        "risk_level": _keyword(
            _first(payment, "risk_level"),
        ),
        "fraud_decision": _keyword(
            _first(payment, "fraud_decision"),
        ),
        "failure_code": _keyword(
            _first(payment, "failure_code"),
        ),
        "amount_minor": _integer(amount),
        "authorized_amount_minor": _integer(
            authorized_amount,
        ),
        "captured_amount_minor": _integer(
            captured_amount,
        ),
        "refunded_amount_minor": _integer(
            refunded_amount,
        ),
        "description": _first(
            payment,
            "description",
        ),
        "authorized_at": _iso(
            _first(payment, "authorized_at"),
        ),
        "captured_at": _iso(
            _first(payment, "captured_at"),
        ),
        "voided_at": _iso(
            _first(payment, "voided_at"),
        ),
        "created_at": _iso(
            _first(payment, "created_at"),
        ),
        "updated_at": _iso(
            _first(payment, "updated_at"),
        ),
    }

    return {
        key: value
        for key, value in document.items()
        if value is not None
    }


async def index_payment(
    es: AsyncElasticsearch,
    payment: Any,
) -> None:
    document = payment_to_document(payment)

    await es.index(
        index=PAYMENTS_INDEX,
        id=document["payment_id"],
        document=document,
        refresh=_refresh_value(),
    )


async def index_payment_safely(
    app: FastAPI,
    payment: Any,
) -> bool:
    es = getattr(app.state, "es", None)

    if es is None:
        logger.warning(
            "Payment was not indexed because Elasticsearch "
            "is unavailable",
        )
        return False

    payment_id = _first(
        payment,
        "payment_id",
        "id",
    )

    try:
        await index_payment(
            es=es,
            payment=payment,
        )

        logger.debug(
            "Payment indexed in Elasticsearch: %s",
            payment_id,
        )
        return True
    except Exception:
        logger.exception(
            "Payment committed but Elasticsearch indexing failed",
            extra={"payment_id": str(payment_id)},
        )
        return False


async def search_payments(
    es: AsyncElasticsearch,
    query_text: str | None,
    status: str | None,
    merchant_id: str | None,
    page: int,
    size: int,
) -> dict[str, Any]:
    if query_text:
        query_clause = {
            "bool": {
                "should": [
                    {
                        "term": {
                            "payment_id": {
                                "value": query_text,
                                "boost": 10,
                            }
                        }
                    },
                    {
                        "multi_match": {
                            "query": query_text,
                            "fields": [
                                "payment_id^5",
                                "order_id^4",
                                "booking_id^4",
                                "cart_id^3",
                                "customer_id^3",
                                "merchant_id^3",
                                "status^2",
                                "currency",
                                "description",
                            ],
                        }
                    },
                ],
                "minimum_should_match": 1,
            }
        }
    else:
        query_clause = {
            "match_all": {},
        }

    filters: list[dict[str, Any]] = []

    if status:
        filters.append(
            {
                "term": {
                    "status": status,
                }
            }
        )

    if merchant_id:
        filters.append(
            {
                "term": {
                    "merchant_id": merchant_id,
                }
            }
        )

    response = await es.search(
        index=PAYMENTS_INDEX,
        query={
            "bool": {
                "must": [query_clause],
                "filter": filters,
            }
        },
        from_=(page - 1) * size,
        size=size,
        sort=[
            {
                "updated_at": {
                    "order": "desc",
                    "missing": "_last",
                }
            }
        ],
    )

    body = _response_body(response)
    hits = body.get("hits", {})
    total = hits.get("total", 0)

    if isinstance(total, Mapping):
        total = total.get("value", 0)

    items = []

    for hit in hits.get("hits", []):
        source = hit.get("_source", {})

        items.append(
            {
                "id": hit.get("_id"),
                **source,
            }
        )

    return {
        "index": PAYMENTS_INDEX,
        "total": int(total),
        "page": page,
        "size": size,
        "items": items,
    }
