# filename: app/config.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    DATABASE_URL: str = "postgresql://booking_user:secure_password@postgres:5432/bookingdb"
    REDIS_URL: str = "redis://:redis_password@redis:6379/0"
    DEBUG: bool = True

    class Config:
        env_file = ".env"


settings = Settings()
