# filename: app/dependencies.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

from fastapi import Depends, HTTPException, Request, status
from sqlalchemy.orm import Session
from redis.asyncio import Redis
from typing import Optional
import time

from app.database import get_db
from app.services.booking_service import BookingService
from app.services.reservation_service import ReservationService
from app.services.lock_service import DistributedLock
from app.services.event_publisher import EventPublisher
from app.core.exceptions import RateLimitExceededError
from app.core.metrics import rate_limit_counter
from app.config import settings

# Global instances
_redis_client: Optional[Redis] = None
_event_publisher: Optional[EventPublisher] = None


async def get_redis_client() -> Redis:
    """Get Redis client instance"""
    global _redis_client
    if _redis_client is None:
        _redis_client = Redis.from_url(
            str(settings.REDIS_URL),
            max_connections=settings.REDIS_MAX_CONNECTIONS,
            socket_timeout=settings.REDIS_SOCKET_TIMEOUT,
            socket_connect_timeout=settings.REDIS_SOCKET_CONNECT_TIMEOUT,
            decode_responses=False
        )
    return _redis_client


async def get_event_publisher() -> EventPublisher:
    """Get event publisher instance"""
    global _event_publisher
    if _event_publisher is None:
        _event_publisher = EventPublisher()
        await _event_publisher.connect()
    return _event_publisher


async def get_lock_service(
        redis: Redis = Depends(get_redis_client)
) -> DistributedLock:
    """Get lock service instance"""
    return DistributedLock(redis)


async def get_booking_service(
        db: Session = Depends(get_db),
        lock_service: DistributedLock = Depends(get_lock_service),
        event_publisher: EventPublisher = Depends(get_event_publisher)
) -> BookingService:
    """Get booking service instance"""
    return BookingService(db, lock_service, event_publisher)


async def get_reservation_service(
        db: Session = Depends(get_db),
        lock_service: DistributedLock = Depends(get_lock_service),
        redis: Redis = Depends(get_redis_client)
) -> ReservationService:
    """Get reservation service instance"""
    return ReservationService(db, lock_service, redis)


# Rate limiting
rate_limit_cache = {}


async def rate_limit_check(request: Request):
    """
    Rate limiting middleware
    """
    if not settings.RATE_LIMIT_ENABLED:
        return

    # Get user identifier (you might want to use authentication instead)
    user_id = request.headers.get("X-User-ID", request.client.host)

    current_time = int(time.time())
    minute_key = f"{user_id}:{current_time // 60}"

    # Clean old entries
    old_keys = [k for k in rate_limit_cache.keys() if k.split(':')[1] != str(current_time // 60)]
    for old_key in old_keys:
        rate_limit_cache.pop(old_key, None)

    # Check rate limit
    count = rate_limit_cache.get(minute_key, 0)

    if count >= settings.RATE_LIMIT_PER_MINUTE:
        rate_limit_counter.inc()
        raise HTTPException(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            detail="Too many requests. Please try again later."
        )

    rate_limit_cache[minute_key] = count + 1
