# filename: app/lock_service.py
# Code Generated by Sidekick is for learning and experimentation purposes only.
import time
import uuid
from contextlib import contextmanager

import redis

from app.config import settings
from app.observability.metrics import (
    REDIS_LOCK_ACQUISITION_FAILURE_TOTAL,
    REDIS_LOCK_ACQUISITION_SECONDS,
    REDIS_LOCK_CONTENTION_SECONDS,
    normalize_lock_name,
)

redis_client = redis.from_url(settings.redis_url, decode_responses=True)


@contextmanager
def acquire_lock(resource: str, timeout: int = 10, retry_interval: float = 0.05):
    """Acquire a distributed lock using Redis with timing metrics."""
    lock_key = f"lock:{resource}"
    lock_value = str(uuid.uuid4())
    metric_lock_name = normalize_lock_name(resource)

    started = time.perf_counter()
    contention_started = None

    while True:
        acquired = redis_client.set(lock_key, lock_value, nx=True, ex=timeout)
        if acquired:
            acquired_in = time.perf_counter() - started
            REDIS_LOCK_ACQUISITION_SECONDS.labels(
                lock_name=metric_lock_name
            ).observe(acquired_in)

            if contention_started is not None:
                REDIS_LOCK_CONTENTION_SECONDS.labels(
                    lock_name=metric_lock_name
                ).observe(time.perf_counter() - contention_started)

            break

        if contention_started is None:
            contention_started = time.perf_counter()

        elapsed = time.perf_counter() - started
        if elapsed >= timeout:
            REDIS_LOCK_ACQUISITION_FAILURE_TOTAL.labels(
                lock_name=metric_lock_name
            ).inc()

            if contention_started is not None:
                REDIS_LOCK_CONTENTION_SECONDS.labels(
                    lock_name=metric_lock_name
                ).observe(time.perf_counter() - contention_started)

            raise Exception(f"Could not acquire lock for {resource}")

        time.sleep(retry_interval)

    try:
        yield lock_value
    finally:
        script = """
        if redis.call("get", KEYS[1]) == ARGV[1] then
            return redis.call("del", KEYS[1])
        else
            return 0
        end
        """
        redis_client.eval(script, 1, lock_key, lock_value)
