# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: app/main.py

import logging
from typing import List, Optional

from fastapi import Depends, FastAPI, HTTPException, Query, WebSocket, WebSocketDisconnect
from fastapi.responses import HTMLResponse
from sqlalchemy import text
from sqlalchemy.orm import Session

from app.database import Base, engine, get_db
from app.hold import HoldService
from app.lock_service import acquire_lock
from app.schemas import (
    BookingResponse,
    BookingWithPaymentCreate,
    EventCreate,
    EventResponse,
    HoldCreate,
    HoldResponse,
    RefundRequest,
    RefundResponse,
    SeatCreate,
    SeatResponse,
)
from app.websocket_manager import manager
from models.models import Booking, Event, Payment, Seat
from payment.payment_service import PaymentService

Base.metadata.create_all(bind=engine)

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="Booking System with Payment",
    version="4.0.0",
    description="Production-style booking with Redis holds, payment integration, and realtime updates",
)

REALTIME_HTML = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>Realtime Seat Booking</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 24px; }
        .row { margin-bottom: 16px; }
        .seats { display: flex; flex-wrap: wrap; gap: 10px; margin-top: 16px; }
        .seat {
            width: 100px; height: 68px; border: 1px solid #ccc; border-radius: 8px;
            display: flex; flex-direction: column; align-items: center; justify-content: center;
            font-size: 12px; font-weight: 600;
        }
        .available { background: #d4f7d4; }
        .held { background: #ffe9a8; }
        .booked { background: #ffc7c7; }
        .log {
            margin-top: 20px; border: 1px solid #ddd; padding: 12px; height: 240px; overflow-y: auto;
            background: #fafafa; font-size: 13px;
        }
        input, button { padding: 8px 10px; }
        .muted { color: #666; font-size: 13px; }
    </style>
</head>
<body>
    <h2>Realtime Seat Updates</h2>

    <div class="row">
        <input id="eventIdInput" placeholder="Enter event_id" style="width: 360px;" />
        <button onclick="startRealtime()">Connect</button>
    </div>

    <div class="muted">
        Open with: <b>/realtime?event_id=YOUR_EVENT_ID</b>
    </div>

    <div class="row">
        <strong>Connection:</strong> <span id="connectionStatus">Not connected</span>
    </div>

    <div class="row">
        <strong>Watching event:</strong> <span id="activeEvent">-</span>
    </div>

    <div id="seats" class="seats"></div>
    <div id="log" class="log"></div>

    <script>
        let socket = null;
        let seats = [];

        function log(message) {
            const box = document.getElementById("log");
            const line = document.createElement("div");
            line.textContent = `[${new Date().toLocaleTimeString()}] ${message}`;
            box.prepend(line);
        }

        function renderSeats() {
            const container = document.getElementById("seats");
            container.innerHTML = "";

            seats.forEach((seat) => {
                const card = document.createElement("div");
                const status = String(seat.status).toLowerCase();
                card.className = `seat ${status}`;
                card.innerHTML = `
                    <div>${seat.seat_number}</div>
                    <div>${status}</div>
                    <div>$${seat.price}</div>
                `;
                container.appendChild(card);
            });
        }

        async function loadSeats(eventId) {
            const res = await fetch(`/events/${eventId}/seats`);
            if (!res.ok) {
                throw new Error(`Seat fetch failed: ${res.status}`);
            }
            seats = await res.json();
            renderSeats();
        }

        function updateSeatStatus(seatId, status) {
            const index = seats.findIndex((seat) => String(seat.seat_id) === String(seatId));
            if (index >= 0) {
                seats[index].status = status;
                renderSeats();
            }
        }

        function closeSocket() {
            if (socket) {
                socket.close();
                socket = null;
            }
        }

        async function startRealtime() {
            const eventId = document.getElementById("eventIdInput").value.trim();
            if (!eventId) {
                alert("Enter event_id");
                return;
            }

            document.getElementById("activeEvent").textContent = eventId;
            document.getElementById("connectionStatus").textContent = "Connecting...";

            closeSocket();
            await loadSeats(eventId);

            const protocol = window.location.protocol === "https:" ? "wss" : "ws";
            socket = new WebSocket(`${protocol}://${window.location.host}/ws/events/${eventId}`);

            socket.onopen = () => {
                document.getElementById("connectionStatus").textContent = "Connected";
                log(`Connected to event ${eventId}`);
            };

            socket.onmessage = (event) => {
                const message = JSON.parse(event.data);
                log(JSON.stringify(message));

                if (message.type === "seat_update") {
                    if (message.action === "held" || message.action === "payment_processing") {
                        updateSeatStatus(message.seat_id, "held");
                    } else if (message.action === "booked") {
                        updateSeatStatus(message.seat_id, "booked");
                    } else if (message.action === "released" || message.action === "refunded") {
                        updateSeatStatus(message.seat_id, "available");
                    }
                }
            };

            socket.onclose = () => {
                document.getElementById("connectionStatus").textContent = "Disconnected";
                log("Socket disconnected");
            };

            socket.onerror = () => {
                document.getElementById("connectionStatus").textContent = "Error";
                log("Socket error");
            };
        }

        window.addEventListener("load", async () => {
            const params = new URLSearchParams(window.location.search);
            const eventId = params.get("event_id");

            if (eventId) {
                document.getElementById("eventIdInput").value = eventId;
                await startRealtime();
            }
        });
    </script>
</body>
</html>
"""


def normalize_payment_method(payment_method) -> str:
    if hasattr(payment_method, "value"):
        return payment_method.value
    return str(payment_method).strip().lower()


def serialize_payment(payment: Optional[Payment]):
    if not payment:
        return None

    return {
        "payment_id": payment.payment_id,
        "booking_id": payment.booking_id,
        "amount": payment.amount,
        "currency": payment.currency,
        "payment_method": payment.payment_method.value if hasattr(payment.payment_method, "value") else str(payment.payment_method),
        "status": payment.status.value if hasattr(payment.status, "value") else str(payment.status),
        "gateway_transaction_id": payment.gateway_transaction_id,
        "card_last4": payment.card_last4,
        "card_brand": payment.card_brand,
        "initiated_at": payment.initiated_at,
        "completed_at": payment.completed_at,
    }


def build_booking_response(booking: Booking) -> BookingResponse:
    return BookingResponse(
        booking_id=booking.booking_id,
        user_id=booking.user_id,
        event_id=booking.event_id,
        seat_id=booking.seat_id,
        status=booking.status.value if hasattr(booking.status, "value") else str(booking.status),
        total_amount=booking.total_amount,
        created_at=booking.created_at,
        payment=serialize_payment(booking.payment),
    )


@app.get("/")
async def root():
    return {
        "message": "Booking System with Payment Integration",
        "version": "4.0.0",
        "status": "running",
    }


@app.get("/realtime", response_class=HTMLResponse)
async def realtime_page():
    return HTMLResponse(REALTIME_HTML)


@app.get("/health")
async def health(db: Session = Depends(get_db)):
    try:
        db.execute(text("SELECT 1"))
        db_status = "healthy"
    except Exception as exc:
        db_status = f"unhealthy: {str(exc)}"

    try:
        from app.lock_service import redis_client
        redis_client.ping()
        redis_status = "healthy"
    except Exception as exc:
        redis_status = f"unhealthy: {str(exc)}"

    return {
        "status": "healthy",
        "database": db_status,
        "redis": redis_status,
    }


@app.post("/events", response_model=EventResponse, status_code=201)
async def create_event(event: EventCreate, db: Session = Depends(get_db)):
    db_event = Event(**event.model_dump())
    db.add(db_event)
    db.commit()
    db.refresh(db_event)
    return db_event


@app.get("/events", response_model=List[EventResponse])
async def list_events(db: Session = Depends(get_db)):
    return db.query(Event).order_by(Event.event_date).all()


@app.get("/events/{event_id}", response_model=EventResponse)
async def get_event(event_id: str, db: Session = Depends(get_db)):
    event = db.query(Event).filter(Event.event_id == event_id).first()
    if not event:
        raise HTTPException(status_code=404, detail="Event not found")
    return event


@app.post("/events/{event_id}/seats", response_model=SeatResponse, status_code=201)
async def create_seat(event_id: str, seat: SeatCreate, db: Session = Depends(get_db)):
    event = db.query(Event).filter(Event.event_id == event_id).first()
    if not event:
        raise HTTPException(status_code=404, detail="Event not found")

    db_seat = Seat(event_id=event_id, seat_number=seat.seat_number, price=seat.price)
    db.add(db_seat)
    db.commit()
    db.refresh(db_seat)
    return db_seat


@app.get("/events/{event_id}/seats", response_model=List[SeatResponse])
async def list_seats(event_id: str, status: Optional[str] = None, db: Session = Depends(get_db)):
    query = db.query(Seat).filter(Seat.event_id == event_id)
    if status:
        query = query.filter(Seat.status == status)
    return query.order_by(Seat.seat_number).all()


@app.get("/events/{event_id}/seats/{seat_id}", response_model=SeatResponse)
async def get_seat(event_id: str, seat_id: str, db: Session = Depends(get_db)):
    seat = db.query(Seat).filter(Seat.event_id == event_id, Seat.seat_id == seat_id).first()
    if not seat:
        raise HTTPException(status_code=404, detail="Seat not found")
    return seat


@app.post("/holds", response_model=HoldResponse, status_code=201)
async def create_hold(request: HoldCreate, db: Session = Depends(get_db)):
    lock_resource = f"seat-hold:{request.event_id}:{request.seat_id}"

    try:
        with acquire_lock(lock_resource, timeout=5):
            seat = (
                db.query(Seat)
                .filter(
                    Seat.event_id == request.event_id,
                    Seat.seat_id == request.seat_id,
                )
                .first()
            )

            if not seat:
                raise HTTPException(status_code=404, detail="Seat not found")

            seat_status = seat.status.value if hasattr(seat.status, "value") else str(seat.status)
            if str(seat_status).lower() == "booked":
                raise HTTPException(status_code=409, detail="Seat already booked")

            created, hold = HoldService.create_hold(
                user_id=str(request.user_id),
                event_id=str(request.event_id),
                seat_id=str(request.seat_id),
                ttl_seconds=request.ttl_seconds,
            )

            if not created:
                raise HTTPException(status_code=409, detail="Seat already held")

        await manager.broadcast_to_event(
            event_id=str(request.event_id),
            message={
                "type": "seat_update",
                "action": "held",
                "event_id": str(request.event_id),
                "seat_id": str(request.seat_id),
                "seat_number": seat.seat_number,
                "status": "held",
                "held_by": str(request.user_id),
                "expires_at": hold["expires_at"],
            },
        )

        return HoldResponse(**hold)

    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Hold creation failed: {str(exc)}")


@app.delete("/holds/{hold_token}")
async def release_hold(hold_token: str):
    hold = HoldService.release_hold(hold_token)
    if not hold:
        raise HTTPException(status_code=404, detail="Hold not found")

    await manager.broadcast_to_event(
        event_id=str(hold["event_id"]),
        message={
            "type": "seat_update",
            "action": "released",
            "event_id": str(hold["event_id"]),
            "seat_id": str(hold["seat_id"]),
            "status": "available",
        },
    )

    return {"message": "Hold released"}


@app.post("/bookings", response_model=BookingResponse, status_code=201)
async def create_booking_with_payment(
    booking_request: BookingWithPaymentCreate,
    db: Session = Depends(get_db),
):
    payment_method = normalize_payment_method(booking_request.payment_method)
    payment_details = {}

    if payment_method in {"credit_card", "debit_card"}:
        if not booking_request.card_details:
            raise HTTPException(status_code=400, detail="Card details required")
        payment_details = {
            "card_number": booking_request.card_details.card_number,
            "card_holder_name": booking_request.card_details.card_holder_name,
            "expiry_month": booking_request.card_details.expiry_month,
            "expiry_year": booking_request.card_details.expiry_year,
            "cvv": booking_request.card_details.cvv,
        }
    elif payment_method == "upi":
        if not booking_request.upi_details:
            raise HTTPException(status_code=400, detail="UPI details required")
        payment_details = {"upi_id": booking_request.upi_details.upi_id}
    elif payment_method == "net_banking":
        if not booking_request.netbanking_details:
            raise HTTPException(status_code=400, detail="Net banking details required")
        payment_details = {"bank_code": booking_request.netbanking_details.bank_code}
    elif payment_method == "wallet":
        if not booking_request.wallet_details:
            raise HTTPException(status_code=400, detail="Wallet details required")
        payment_details = {
            "wallet_id": booking_request.wallet_details.wallet_id,
            "wallet_provider": booking_request.wallet_details.wallet_provider,
        }
    else:
        raise HTTPException(status_code=400, detail=f"Unsupported payment method: {payment_method}")

    booking, payment, result = PaymentService.create_booking_with_payment(
        db=db,
        user_id=str(booking_request.user_id),
        event_id=str(booking_request.event_id),
        seat_id=str(booking_request.seat_id),
        payment_method=payment_method,
        payment_details=payment_details,
        hold_token=booking_request.hold_token,
        idempotency_key=booking_request.idempotency_key,
    )

    logger.info(
        "Booking created | result=%s booking_id=%s payment_id=%s",
        result,
        getattr(booking, "booking_id", None),
        getattr(payment, "payment_id", None) if payment else None,
    )

    if payment and not getattr(booking, "payment", None):
        booking.payment = payment

    return build_booking_response(booking)


@app.get("/bookings/{booking_id}", response_model=BookingResponse)
async def get_booking(booking_id: str, db: Session = Depends(get_db)):
    booking = db.query(Booking).filter(Booking.booking_id == booking_id).first()
    if not booking:
        raise HTTPException(status_code=404, detail="Booking not found")
    return build_booking_response(booking)


@app.get("/users/{user_id}/bookings", response_model=List[BookingResponse])
async def list_user_bookings(user_id: str, db: Session = Depends(get_db)):
    bookings = (
        db.query(Booking)
        .filter(Booking.user_id == user_id)
        .order_by(Booking.created_at.desc())
        .all()
    )
    return [build_booking_response(booking) for booking in bookings]


@app.post("/refunds", response_model=RefundResponse, status_code=200)
async def request_refund(
    refund_request: RefundRequest,
    user_id: str = Query(..., description="User ID requesting the refund"),
    db: Session = Depends(get_db),
):
    result = await PaymentService.process_refund(
        db=db,
        booking_id=str(refund_request.booking_id),
        user_id=user_id,
        reason=refund_request.reason,
    )
    return RefundResponse(**result)


@app.websocket("/ws/events/{event_id}")
async def websocket_endpoint(websocket: WebSocket, event_id: str):
    await manager.connect(websocket, event_id)

    try:
        while True:
            data = await websocket.receive_text()
            if data == "ping":
                await websocket.send_text("pong")
            else:
                await manager.send_personal_message(
                    {"type": "echo", "message": data},
                    websocket,
                )
    except WebSocketDisconnect:
        manager.disconnect(websocket, event_id)
        logger.info("WebSocket disconnected for event %s", event_id)
    except Exception as exc:
        logger.error("WebSocket error for event %s: %s", event_id, exc)
        manager.disconnect(websocket, event_id)


@app.get("/ws/stats")
async def websocket_stats():
    return {
        "total_connections": manager.get_total_connections(),
        "connections_by_event": {
            event_id: manager.get_connection_count(event_id)
            for event_id in manager.active_connections.keys()
        },
    }


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
