# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: app/main.py

from datetime import datetime
import logging
from typing import List, Optional

from fastapi import FastAPI, Depends, HTTPException, Query, WebSocket, WebSocketDisconnect
from sqlalchemy import text
from sqlalchemy.orm import Session

from app.database import get_db, engine, Base
from app.schemas import (
    EventCreate,
    EventResponse,
    SeatCreate,
    SeatResponse,
    BookingWithPaymentCreate,
    BookingResponse,
    RefundRequest,
    RefundResponse,
)
from app.websocket_manager import manager
from models.models import Booking, Event, Payment, Seat
from payment.payment_service import PaymentService

Base.metadata.create_all(bind=engine)

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="Booking System with Payment",
    version="3.0.1",
    description="Production-grade booking with payment integration",
)


def normalize_payment_method(payment_method) -> str:
    if hasattr(payment_method, "value"):
        return payment_method.value
    return str(payment_method).strip().lower()


def serialize_payment(payment: Optional[Payment]):
    if not payment:
        return None

    return {
        "payment_id": payment.payment_id,
        "booking_id": payment.booking_id,
        "amount": payment.amount,
        "currency": payment.currency,
        "payment_method": payment.payment_method.value if hasattr(payment.payment_method, "value") else str(payment.payment_method),
        "status": payment.status.value if hasattr(payment.status, "value") else str(payment.status),
        "gateway_transaction_id": payment.gateway_transaction_id,
        "card_last4": payment.card_last4,
        "card_brand": payment.card_brand,
        "initiated_at": payment.initiated_at,
        "completed_at": payment.completed_at,
    }


def build_booking_response(booking: Booking) -> BookingResponse:
    return BookingResponse(
        booking_id=booking.booking_id,
        user_id=booking.user_id,
        event_id=booking.event_id,
        seat_id=booking.seat_id,
        status=booking.status.value if hasattr(booking.status, "value") else str(booking.status),
        total_amount=booking.total_amount,
        created_at=booking.created_at,
        payment=serialize_payment(booking.payment),
    )


@app.get("/")
async def root():
    return {
        "message": "Booking System with Payment Integration",
        "version": "3.0.1",
        "status": "running",
    }


@app.get("/health")
async def health(db: Session = Depends(get_db)):
    try:
        db.execute(text("SELECT 1"))
        db_status = "healthy"
    except Exception as exc:
        db_status = f"unhealthy: {str(exc)}"

    try:
        from app.lock_service import redis_client

        redis_client.ping()
        redis_status = "healthy"
    except Exception as exc:
        redis_status = f"unhealthy: {str(exc)}"

    return {
        "status": "healthy",
        "database": db_status,
        "redis": redis_status,
    }


@app.post("/events", response_model=EventResponse, status_code=201)
async def create_event(event: EventCreate, db: Session = Depends(get_db)):
    db_event = Event(**event.model_dump())
    db.add(db_event)
    db.commit()
    db.refresh(db_event)
    return db_event


@app.get("/events", response_model=List[EventResponse])
async def list_events(db: Session = Depends(get_db)):
    return db.query(Event).order_by(Event.event_date).all()


@app.get("/events/{event_id}", response_model=EventResponse)
async def get_event(event_id: str, db: Session = Depends(get_db)):
    event = db.query(Event).filter(Event.event_id == event_id).first()
    if not event:
        raise HTTPException(status_code=404, detail="Event not found")
    return event


@app.post("/events/{event_id}/seats", response_model=SeatResponse, status_code=201)
async def create_seat(event_id: str, seat: SeatCreate, db: Session = Depends(get_db)):
    event = db.query(Event).filter(Event.event_id == event_id).first()
    if not event:
        raise HTTPException(status_code=404, detail="Event not found")

    db_seat = Seat(event_id=event_id, seat_number=seat.seat_number, price=seat.price)
    db.add(db_seat)
    db.commit()
    db.refresh(db_seat)
    return db_seat


@app.get("/events/{event_id}/seats", response_model=List[SeatResponse])
async def list_seats(event_id: str, status: Optional[str] = None, db: Session = Depends(get_db)):
    query = db.query(Seat).filter(Seat.event_id == event_id)
    if status:
        query = query.filter(Seat.status == status)
    return query.order_by(Seat.seat_number).all()


@app.get("/events/{event_id}/seats/{seat_id}", response_model=SeatResponse)
async def get_seat(event_id: str, seat_id: str, db: Session = Depends(get_db)):
    seat = db.query(Seat).filter(Seat.event_id == event_id, Seat.seat_id == seat_id).first()
    if not seat:
        raise HTTPException(status_code=404, detail="Seat not found")
    return seat


@app.post("/bookings", response_model=BookingResponse, status_code=201)
async def create_booking_with_payment(
    booking_request: BookingWithPaymentCreate,
    db: Session = Depends(get_db),
):
    payment_method = normalize_payment_method(booking_request.payment_method)
    payment_details = {}

    if payment_method in {"credit_card", "debit_card"}:
        if not booking_request.card_details:
            raise HTTPException(status_code=400, detail="Card details required")
        payment_details = {
            "card_number": booking_request.card_details.card_number,
            "card_holder_name": booking_request.card_details.card_holder_name,
            "expiry_month": booking_request.card_details.expiry_month,
            "expiry_year": booking_request.card_details.expiry_year,
            "cvv": booking_request.card_details.cvv,
        }
    elif payment_method == "upi":
        if not booking_request.upi_details:
            raise HTTPException(status_code=400, detail="UPI details required")
        payment_details = {"upi_id": booking_request.upi_details.upi_id}
    elif payment_method == "net_banking":
        if not booking_request.netbanking_details:
            raise HTTPException(status_code=400, detail="Net banking details required")
        payment_details = {"bank_code": booking_request.netbanking_details.bank_code}
    elif payment_method == "wallet":
        if not booking_request.wallet_details:
            raise HTTPException(status_code=400, detail="Wallet details required")
        payment_details = {
            "wallet_id": booking_request.wallet_details.wallet_id,
            "wallet_provider": booking_request.wallet_details.wallet_provider,
        }
    else:
        raise HTTPException(
            status_code=400,
            detail=f"Unsupported payment method: {payment_method}",
        )

    logger.info(
        "Booking request received | user_id=%s event_id=%s seat_id=%s payment_method=%s idempotency_key=%s",
        booking_request.user_id,
        booking_request.event_id,
        booking_request.seat_id,
        payment_method,
        booking_request.idempotency_key,
    )

    try:
        booking, payment, result = PaymentService.create_booking_with_payment(
            db=db,
            user_id=str(booking_request.user_id),
            event_id=str(booking_request.event_id),
            seat_id=str(booking_request.seat_id),
            payment_method=payment_method,
            payment_details=payment_details,
            idempotency_key=booking_request.idempotency_key,
        )

        logger.info(
            "Booking service returned | result=%s booking_id=%s payment_id=%s booking_status=%s",
            result,
            getattr(booking, "booking_id", None),
            getattr(payment, "payment_id", None) if payment else None,
            getattr(booking.status, "value", booking.status) if booking else None,
        )

        if not booking:
            raise HTTPException(status_code=400, detail="Booking failed")

        if payment and not getattr(booking, "payment", None):
            booking.payment = payment

        response = build_booking_response(booking)

        logger.info(
            "Booking response built successfully | booking_id=%s",
            response.booking_id,
        )

        return response

    except HTTPException as exc:
        logger.exception("Booking HTTPException raised: %s", exc.detail)
        raise
    except Exception as exc:
        logger.exception("Unexpected booking error")
        raise HTTPException(status_code=500, detail=f"Unexpected booking error: {str(exc)}")


@app.get("/bookings/{booking_id}", response_model=BookingResponse)
async def get_booking(booking_id: str, db: Session = Depends(get_db)):
    booking = db.query(Booking).filter(Booking.booking_id == booking_id).first()
    if not booking:
        raise HTTPException(status_code=404, detail="Booking not found")
    return build_booking_response(booking)


@app.get("/users/{user_id}/bookings", response_model=List[BookingResponse])
async def list_user_bookings(user_id: str, db: Session = Depends(get_db)):
    bookings = (
        db.query(Booking)
        .filter(Booking.user_id == user_id)
        .order_by(Booking.created_at.desc())
        .all()
    )
    return [build_booking_response(booking) for booking in bookings]


@app.post("/refunds", response_model=RefundResponse, status_code=200)
async def request_refund(
    refund_request: RefundRequest,
    user_id: str = Query(..., description="User ID requesting the refund"),
    db: Session = Depends(get_db),
):
    try:
        result = await PaymentService.process_refund(
            db=db,
            booking_id=str(refund_request.booking_id),
            user_id=user_id,
            reason=refund_request.reason,
        )
        return RefundResponse(**result)
    except HTTPException:
        raise
    except Exception as exc:
        logger.exception("Unexpected refund error")
        raise HTTPException(status_code=500, detail=f"Unexpected refund error: {str(exc)}")


@app.websocket("/ws/events/{event_id}")
async def websocket_endpoint(websocket: WebSocket, event_id: str):
    await manager.connect(websocket, event_id)

    try:
        while True:
            data = await websocket.receive_text()
            if data == "ping":
                await websocket.send_text("pong")
            else:
                await manager.send_personal_message(
                    {"type": "echo", "message": data},
                    websocket,
                )
    except WebSocketDisconnect:
        manager.disconnect(websocket, event_id)
        logger.info("WebSocket disconnected for event %s", event_id)
    except Exception as exc:
        logger.error("WebSocket error for event %s: %s", event_id, exc)
        manager.disconnect(websocket, event_id)


@app.get("/ws/stats")
async def websocket_stats():
    return {
        "total_connections": manager.get_total_connections(),
        "connections_by_event": {
            event_id: manager.get_connection_count(event_id)
            for event_id in manager.active_connections.keys()
        },
    }


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
