# filename: app/schemas.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

from pydantic import BaseModel, UUID4, ConfigDict, Field
from datetime import datetime
from decimal import Decimal
from typing import Optional
from enum import Enum


class EventCreate(BaseModel):
    event_name: str
    event_date: datetime
    venue: str
    total_seats: int


class EventResponse(BaseModel):
    event_id: UUID4
    event_name: str
    event_date: datetime
    venue: str
    total_seats: int
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class SeatCreate(BaseModel):
    seat_number: str
    price: Decimal


class SeatResponse(BaseModel):
    seat_id: UUID4
    event_id: UUID4
    seat_number: str
    price: Decimal
    status: str
    booked_by: Optional[UUID4] = None
    booked_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)


class PaymentMethodEnum(str, Enum):
    CREDIT_CARD = "credit_card"
    DEBIT_CARD = "debit_card"
    UPI = "upi"
    NET_BANKING = "net_banking"
    WALLET = "wallet"


class CardDetails(BaseModel):
    card_number: str = Field(..., min_length=13, max_length=19)
    card_holder_name: str
    expiry_month: int = Field(..., ge=1, le=12)
    expiry_year: int = Field(..., ge=2024)
    cvv: str = Field(..., min_length=3, max_length=4)


class UPIDetails(BaseModel):
    upi_id: str


class NetBankingDetails(BaseModel):
    bank_code: str


class WalletDetails(BaseModel):
    wallet_id: str
    wallet_provider: str


class BookingWithPaymentCreate(BaseModel):
    user_id: UUID4
    event_id: UUID4
    seat_id: UUID4
    payment_method: PaymentMethodEnum
    card_details: Optional[CardDetails] = None
    upi_details: Optional[UPIDetails] = None
    netbanking_details: Optional[NetBankingDetails] = None
    wallet_details: Optional[WalletDetails] = None
    idempotency_key: Optional[str] = None


class PaymentResponse(BaseModel):
    payment_id: UUID4
    booking_id: UUID4
    amount: Decimal
    currency: str
    payment_method: str
    status: str
    gateway_transaction_id: Optional[str] = None
    card_last4: Optional[str] = None
    card_brand: Optional[str] = None
    initiated_at: datetime
    completed_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)


class BookingResponse(BaseModel):
    booking_id: UUID4
    user_id: UUID4
    event_id: UUID4
    seat_id: UUID4
    status: str
    total_amount: Decimal
    created_at: datetime
    payment: Optional[PaymentResponse] = None

    model_config = ConfigDict(from_attributes=True)


class RefundRequest(BaseModel):
    """Refund request schema"""
    booking_id: UUID4
    reason: Optional[str] = Field(None, max_length=500, description="Reason for refund")

    class Config:
        json_schema_extra = {
            "example": {
                "booking_id": "550e8400-e29b-41d4-a716-446655440000",
                "reason": "User cancelled the booking"
            }
        }


class RefundResponse(BaseModel):
    """Refund response schema"""
    booking_id: str
    payment_id: str
    refund_amount: float
    status: str
    refund_transaction_id: Optional[str] = None
    seat_released: bool
    message: str

    class Config:
        json_schema_extra = {
            "example": {
                "booking_id": "550e8400-e29b-41d4-a716-446655440000",
                "payment_id": "650e8400-e29b-41d4-a716-446655440001",
                "refund_amount": 100.00,
                "status": "refunded",
                "refund_transaction_id": "refund_abc123",
                "seat_released": True,
                "message": "Refund processed successfully and seat has been released"
            }
        }