# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: app/websocket_manager.py

import logging
from typing import Dict, List, Set

from fastapi import WebSocket

logger = logging.getLogger(__name__)


class ConnectionManager:
    def __init__(self):
        self.active_connections: Dict[str, List[WebSocket]] = {}
        self.all_connections: Set[WebSocket] = set()

    async def connect(self, websocket: WebSocket, event_id: str):
        await websocket.accept()

        if event_id not in self.active_connections:
            self.active_connections[event_id] = []

        self.active_connections[event_id].append(websocket)
        self.all_connections.add(websocket)

        await websocket.send_json(
            {
                "type": "connected",
                "event_id": event_id,
                "message": f"Connected to event {event_id}",
            }
        )

    def disconnect(self, websocket: WebSocket, event_id: str):
        if event_id in self.active_connections and websocket in self.active_connections[event_id]:
            self.active_connections[event_id].remove(websocket)
            if not self.active_connections[event_id]:
                del self.active_connections[event_id]

        self.all_connections.discard(websocket)

    async def broadcast_to_event(self, event_id: str, message: dict):
        if event_id not in self.active_connections:
            return

        disconnected: List[WebSocket] = []

        for connection in self.active_connections[event_id]:
            try:
                await connection.send_json(message)
            except Exception as exc:
                logger.error("Broadcast failed | event_id=%s error=%s", event_id, exc)
                disconnected.append(connection)

        for connection in disconnected:
            self.disconnect(connection, event_id)

    async def send_personal_message(self, message: dict, websocket: WebSocket):
        await websocket.send_json(message)

    def get_connection_count(self, event_id: str) -> int:
        return len(self.active_connections.get(event_id, []))

    def get_total_connections(self) -> int:
        return len(self.all_connections)


manager = ConnectionManager()
