# Code Generated by Sidekick is for learning and experimentation purposes only.
# services/analytics_worker/worker.py (UPDATED VERSION)

import pika
import json
import psycopg2
from datetime import datetime
from analytics import AnalyticsService
import sys

sys.path.append('../..')
from config import Config


def get_db_connection():
    """Connect to PostgreSQL Primary for writing analytics"""
    return psycopg2.connect(
        host=Config.DB_PRIMARY_HOST,
        port=Config.DB_PRIMARY_PORT,
        database=Config.DB_NAME,
        user=Config.DB_USER,
        password=Config.DB_PASSWORD
    )


def get_country_from_ip(ip_address: str) -> str:
    """
    Determine country from IP address.

    In production, use a services like:
    - MaxMind GeoIP2
    - IP2Location
    - ipapi.co

    For now, returning 'Unknown' as placeholder.
    """
    # TODO: Implement actual IP geolocation
    # Example with ipapi:
    # import requests
    # response = requests.get(f'https://ipapi.co/{ip_address}/country_name/')
    # return response.text

    return 'Unknown'


def process_click_event(click_data: dict):
    """
    Process a single click event:
    1. Determine country from IP (geo-location)
    2. Insert into click_events table with full details
    3. Update clicks counter in urls table
    4. Update last_accessed timestamp
    """
    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        # Get country from IP address
        country = get_country_from_ip(click_data.get('ip_address'))

        # Insert detailed click event
        cursor.execute("""
            INSERT INTO click_events 
            (short_url, clicked_at, user_agent, ip_address, referrer, country)
            VALUES (%s, %s, %s, %s, %s, %s)
        """, (
            click_data['short_url'],
            click_data['clicked_at'],
            click_data.get('user_agent'),
            click_data.get('ip_address'),
            click_data.get('referrer'),
            country
        ))

        # Update URL statistics
        cursor.execute("""
            UPDATE urls
            SET clicks = clicks + 1,
                last_accessed = %s
            WHERE short_url = %s
        """, (click_data['clicked_at'], click_data['short_url']))

        conn.commit()
        print(f"✓ Processed click for {click_data['short_url']} from {country}")

    except Exception as e:
        print(f"✗ Error processing click: {e}")
        conn.rollback()
    finally:
        cursor.close()
        conn.close()


def callback(ch, method, properties, body):
    """RabbitMQ message handler"""
    try:
        click_data = json.loads(body)
        process_click_event(click_data)

        # Acknowledge message processing
        ch.basic_ack(delivery_tag=method.delivery_tag)

    except Exception as e:
        print(f"✗ Error in callback: {e}")
        # Reject and requeue message for retry
        ch.basic_nack(delivery_tag=method.delivery_tag, requeue=True)


def start_worker():
    """
    Start consuming messages from RabbitMQ.
    This runs continuously as a background worker.
    """
    credentials = pika.PlainCredentials(
        Config.RABBITMQ_USER,
        Config.RABBITMQ_PASSWORD
    )

    parameters = pika.ConnectionParameters(
        host=Config.RABBITMQ_HOST,
        port=Config.RABBITMQ_PORT,
        credentials=credentials,
        heartbeat=600,
        blocked_connection_timeout=300
    )

    connection = pika.BlockingConnection(parameters)
    channel = connection.channel()

    # Declare queue (ensure it exists)
    channel.queue_declare(queue=Config.RABBITMQ_QUEUE, durable=True)

    # Fair dispatch - only send 1 message at a time to each worker
    channel.basic_qos(prefetch_count=1)

    # Start consuming
    channel.basic_consume(
        queue=Config.RABBITMQ_QUEUE,
        on_message_callback=callback
    )

    print('⚙️  Analytics Worker Started. Waiting for messages...')
    print(f'   Queue: {Config.RABBITMQ_QUEUE}')
    print(f'   Database: {Config.DB_PRIMARY_HOST}')

    try:
        channel.start_consuming()
    except KeyboardInterrupt:
        print('\n⏹️  Stopping worker...')
        channel.stop_consuming()
    finally:
        connection.close()


if __name__ == '__main__':
    start_worker()
