# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: app/payment_gateway.py

import random
import time
import uuid
from datetime import datetime
from typing import Any, Dict, Tuple


class MockPaymentGateway:
    """
    Mock payment gateway simulating real payment processors.
    Includes realistic success/failure scenarios.
    """

    MIN_PROCESSING_TIME = 0.5
    MAX_PROCESSING_TIME = 2.0
    SUCCESS_RATE = 0.90

    TEST_CARDS = {
        "4242424242424242": {"success": True, "brand": "Visa"},
        "4000000000000002": {"success": False, "brand": "Visa", "error": "Card declined"},
        "4000000000009995": {"success": False, "brand": "Visa", "error": "Insufficient funds"},
        "5555555555554444": {"success": True, "brand": "Mastercard"},
        "2223003122003222": {"success": True, "brand": "Mastercard"},
        "378282246310005": {"success": True, "brand": "Amex"},
    }

    @staticmethod
    def _normalize_payment_method(payment_method) -> str:
        if hasattr(payment_method, "value"):
            return payment_method.value
        return str(payment_method).strip().lower()

    @classmethod
    def process_payment(
        cls,
        amount: float,
        currency: str,
        payment_method: str,
        payment_details: Dict[str, Any],
    ) -> Tuple[bool, Dict[str, Any]]:
        time.sleep(random.uniform(cls.MIN_PROCESSING_TIME, cls.MAX_PROCESSING_TIME))
        transaction_id = f"txn_{uuid.uuid4().hex[:16]}"
        method = cls._normalize_payment_method(payment_method)

        if method in {"credit_card", "debit_card"}:
            return cls._process_card_payment(amount, currency, payment_details, transaction_id)
        if method == "upi":
            return cls._process_upi_payment(amount, currency, payment_details, transaction_id)
        if method == "net_banking":
            return cls._process_netbanking_payment(amount, currency, payment_details, transaction_id)
        if method == "wallet":
            return cls._process_wallet_payment(amount, currency, payment_details, transaction_id)

        return False, {
            "error": "Invalid payment method",
            "error_code": "invalid_payment_method",
            "transaction_id": transaction_id,
            "status": "failed",
            "processed_at": datetime.utcnow().isoformat(),
        }

    @classmethod
    def _process_card_payment(
        cls,
        amount: float,
        currency: str,
        details: Dict[str, Any],
        transaction_id: str,
    ) -> Tuple[bool, Dict[str, Any]]:
        card_number = str(details.get("card_number", "")).strip()
        if not card_number:
            return False, {
                "transaction_id": transaction_id,
                "status": "failed",
                "error": "Card number is required",
                "error_code": "missing_card_number",
                "processed_at": datetime.utcnow().isoformat(),
            }

        if card_number in cls.TEST_CARDS:
            test_card = cls.TEST_CARDS[card_number]
            if test_card["success"]:
                return True, {
                    "transaction_id": transaction_id,
                    "status": "completed",
                    "amount": amount,
                    "currency": currency,
                    "card_brand": test_card["brand"],
                    "card_last4": card_number[-4:],
                    "authorization_code": f"AUTH_{random.randint(100000, 999999)}",
                    "processed_at": datetime.utcnow().isoformat(),
                    "message": "Payment successful",
                }

            return False, {
                "transaction_id": transaction_id,
                "status": "failed",
                "error": test_card["error"],
                "error_code": "card_declined",
                "card_last4": card_number[-4:],
                "processed_at": datetime.utcnow().isoformat(),
            }

        if random.random() < cls.SUCCESS_RATE:
            return True, {
                "transaction_id": transaction_id,
                "status": "completed",
                "amount": amount,
                "currency": currency,
                "card_brand": random.choice(["Visa", "Mastercard", "Amex", "Discover"]),
                "card_last4": card_number[-4:],
                "authorization_code": f"AUTH_{random.randint(100000, 999999)}",
                "processed_at": datetime.utcnow().isoformat(),
                "message": "Payment successful",
            }

        error_code, error_message = random.choice(
            [
                ("card_declined", "Card was declined"),
                ("insufficient_funds", "Insufficient funds"),
                ("expired_card", "Card has expired"),
                ("invalid_cvv", "Invalid CVV"),
                ("processing_error", "Payment processing error"),
            ]
        )

        return False, {
            "transaction_id": transaction_id,
            "status": "failed",
            "error": error_message,
            "error_code": error_code,
            "card_last4": card_number[-4:],
            "processed_at": datetime.utcnow().isoformat(),
        }

    @classmethod
    def _process_upi_payment(
        cls,
        amount: float,
        currency: str,
        details: Dict[str, Any],
        transaction_id: str,
    ) -> Tuple[bool, Dict[str, Any]]:
        upi_id = str(details.get("upi_id", "")).strip()
        if not upi_id:
            return False, {
                "transaction_id": transaction_id,
                "status": "failed",
                "error": "UPI ID is required",
                "error_code": "missing_upi_id",
                "processed_at": datetime.utcnow().isoformat(),
            }

        if random.random() < cls.SUCCESS_RATE:
            return True, {
                "transaction_id": transaction_id,
                "status": "completed",
                "amount": amount,
                "currency": currency,
                "upi_id": upi_id,
                "upi_transaction_ref": f"UPI{random.randint(100000000000, 999999999999)}",
                "processed_at": datetime.utcnow().isoformat(),
                "message": "UPI payment successful",
            }

        error_code, error_message = random.choice(
            [
                ("upi_declined", "UPI payment declined"),
                ("insufficient_balance", "Insufficient balance in account"),
                ("bank_error", "Bank server error"),
                ("timeout", "Transaction timeout"),
            ]
        )

        return False, {
            "transaction_id": transaction_id,
            "status": "failed",
            "error": error_message,
            "error_code": error_code,
            "processed_at": datetime.utcnow().isoformat(),
        }

    @classmethod
    def _process_netbanking_payment(
        cls,
        amount: float,
        currency: str,
        details: Dict[str, Any],
        transaction_id: str,
    ) -> Tuple[bool, Dict[str, Any]]:
        bank_code = str(details.get("bank_code", "")).strip()
        if not bank_code:
            return False, {
                "transaction_id": transaction_id,
                "status": "failed",
                "error": "Bank code is required",
                "error_code": "missing_bank_code",
                "processed_at": datetime.utcnow().isoformat(),
            }

        if random.random() < cls.SUCCESS_RATE:
            return True, {
                "transaction_id": transaction_id,
                "status": "completed",
                "amount": amount,
                "currency": currency,
                "bank_code": bank_code,
                "bank_reference": f"BNK{random.randint(1000000000, 9999999999)}",
                "processed_at": datetime.utcnow().isoformat(),
                "message": "Net banking payment successful",
            }

        return False, {
            "transaction_id": transaction_id,
            "status": "failed",
            "error": "Bank transaction failed",
            "error_code": "bank_error",
            "processed_at": datetime.utcnow().isoformat(),
        }

    @classmethod
    def _process_wallet_payment(
        cls,
        amount: float,
        currency: str,
        details: Dict[str, Any],
        transaction_id: str,
    ) -> Tuple[bool, Dict[str, Any]]:
        wallet_id = str(details.get("wallet_id", "")).strip()
        wallet_provider = str(details.get("wallet_provider", "")).strip()

        if not wallet_id or not wallet_provider:
            return False, {
                "transaction_id": transaction_id,
                "status": "failed",
                "error": "Wallet ID and provider are required",
                "error_code": "missing_wallet_details",
                "processed_at": datetime.utcnow().isoformat(),
            }

        if random.random() < cls.SUCCESS_RATE:
            return True, {
                "transaction_id": transaction_id,
                "status": "completed",
                "amount": amount,
                "currency": currency,
                "wallet_provider": wallet_provider,
                "wallet_transaction_id": f"WLT{random.randint(100000000, 999999999)}",
                "processed_at": datetime.utcnow().isoformat(),
                "message": f"{wallet_provider} payment successful",
            }

        return False, {
            "transaction_id": transaction_id,
            "status": "failed",
            "error": "Wallet payment failed",
            "error_code": "wallet_insufficient_balance",
            "processed_at": datetime.utcnow().isoformat(),
        }

    @classmethod
    def process_refund(
        cls,
        transaction_id: str,
        amount: float,
        reason: str,
    ) -> Tuple[bool, Dict[str, Any]]:
        time.sleep(random.uniform(0.3, 1.0))
        refund_id = f"refund_{uuid.uuid4().hex[:16]}"

        if random.random() < 0.95:
            return True, {
                "refund_id": refund_id,
                "original_transaction_id": transaction_id,
                "status": "refunded",
                "amount": amount,
                "reason": reason,
                "processed_at": datetime.utcnow().isoformat(),
                "message": "Refund processed successfully",
            }

        return False, {
            "refund_id": refund_id,
            "original_transaction_id": transaction_id,
            "status": "failed",
            "error": "Refund processing failed",
            "processed_at": datetime.utcnow().isoformat(),
        }

    @classmethod
    def verify_payment(cls, transaction_id: str) -> Dict[str, Any]:
        return {
            "transaction_id": transaction_id,
            "verified": True,
            "status": "completed",
            "verified_at": datetime.utcnow().isoformat(),
        }
