# filename: app/payment_gateway.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

import random
import time
import uuid
from datetime import datetime
from typing import Dict, Any, Tuple
import json


class MockPaymentGateway:
    """
    Mock payment gateway simulating real payment processors (Stripe, PayPal, Razorpay)
    Includes realistic success/failure scenarios
    """

    # Simulate network latency
    MIN_PROCESSING_TIME = 0.5  # seconds
    MAX_PROCESSING_TIME = 2.0

    # Success rate configuration
    SUCCESS_RATE = 0.90  # 90% success rate

    # Test card numbers (like Stripe test cards)
    TEST_CARDS = {
        "4242424242424242": {"success": True, "brand": "Visa"},
        "4000000000000002": {"success": False, "brand": "Visa", "error": "Card declined"},
        "4000000000009995": {"success": False, "brand": "Visa", "error": "Insufficient funds"},
        "5555555555554444": {"success": True, "brand": "Mastercard"},
        "2223003122003222": {"success": True, "brand": "Mastercard"},
        "378282246310005": {"success": True, "brand": "Amex"},
    }

    @classmethod
    def process_payment(
            cls,
            amount: float,
            currency: str,
            payment_method: str,
            payment_details: Dict[str, Any]
    ) -> Tuple[bool, Dict[str, Any]]:
        """
        Process payment and return success status with transaction details

        Returns:
            (success: bool, response: dict)
        """
        # Simulate network delay
        time.sleep(random.uniform(cls.MIN_PROCESSING_TIME, cls.MAX_PROCESSING_TIME))

        # Generate transaction ID
        transaction_id = f"txn_{uuid.uuid4().hex[:16]}"

        # Process based on payment method
        if payment_method == "credit_card" or payment_method == "debit_card":
            return cls._process_card_payment(
                amount, currency, payment_details, transaction_id
            )
        elif payment_method == "upi":
            return cls._process_upi_payment(
                amount, currency, payment_details, transaction_id
            )
        elif payment_method == "net_banking":
            return cls._process_netbanking_payment(
                amount, currency, payment_details, transaction_id
            )
        elif payment_method == "wallet":
            return cls._process_wallet_payment(
                amount, currency, payment_details, transaction_id
            )
        else:
            return False, {
                "error": "Invalid payment method",
                "transaction_id": transaction_id
            }

    @classmethod
    def _process_card_payment(
            cls,
            amount: float,
            currency: str,
            details: Dict[str, Any],
            transaction_id: str
    ) -> Tuple[bool, Dict[str, Any]]:
        """Process card payment"""
        card_number = details.get("card_number", "")

        # Check if it's a test card
        if card_number in cls.TEST_CARDS:
            test_card = cls.TEST_CARDS[card_number]

            if test_card["success"]:
                return True, {
                    "transaction_id": transaction_id,
                    "status": "completed",
                    "amount": amount,
                    "currency": currency,
                    "card_brand": test_card["brand"],
                    "card_last4": card_number[-4:],
                    "authorization_code": f"AUTH_{random.randint(100000, 999999)}",
                    "processed_at": datetime.utcnow().isoformat(),
                    "message": "Payment successful"
                }
            else:
                return False, {
                    "transaction_id": transaction_id,
                    "status": "failed",
                    "error": test_card["error"],
                    "error_code": "card_declined",
                    "card_last4": card_number[-4:],
                    "processed_at": datetime.utcnow().isoformat()
                }

        # For non-test cards, simulate random success/failure
        if random.random() < cls.SUCCESS_RATE:
            # Success
            card_brands = ["Visa", "Mastercard", "Amex", "Discover"]
            return True, {
                "transaction_id": transaction_id,
                "status": "completed",
                "amount": amount,
                "currency": currency,
                "card_brand": random.choice(card_brands),
                "card_last4": card_number[-4:],
                "authorization_code": f"AUTH_{random.randint(100000, 999999)}",
                "processed_at": datetime.utcnow().isoformat(),
                "message": "Payment successful"
            }
        else:
            # Failure
            errors = [
                ("card_declined", "Card was declined"),
                ("insufficient_funds", "Insufficient funds"),
                ("expired_card", "Card has expired"),
                ("invalid_cvv", "Invalid CVV"),
                ("processing_error", "Payment processing error")
            ]
            error_code, error_message = random.choice(errors)

            return False, {
                "transaction_id": transaction_id,
                "status": "failed",
                "error": error_message,
                "error_code": error_code,
                "card_last4": card_number[-4:],
                "processed_at": datetime.utcnow().isoformat()
            }

    @classmethod
    def _process_upi_payment(
            cls,
            amount: float,
            currency: str,
            details: Dict[str, Any],
            transaction_id: str
    ) -> Tuple[bool, Dict[str, Any]]:
        """Process UPI payment"""
        upi_id = details.get("upi_id", "")

        # Simulate UPI transaction
        if random.random() < cls.SUCCESS_RATE:
            return True, {
                "transaction_id": transaction_id,
                "status": "completed",
                "amount": amount,
                "currency": currency,
                "upi_id": upi_id,
                "upi_transaction_ref": f"UPI{random.randint(100000000000, 999999999999)}",
                "processed_at": datetime.utcnow().isoformat(),
                "message": "UPI payment successful"
            }
        else:
            errors = [
                ("upi_declined", "UPI payment declined"),
                ("insufficient_balance", "Insufficient balance in account"),
                ("bank_error", "Bank server error"),
                ("timeout", "Transaction timeout")
            ]
            error_code, error_message = random.choice(errors)

            return False, {
                "transaction_id": transaction_id,
                "status": "failed",
                "error": error_message,
                "error_code": error_code,
                "processed_at": datetime.utcnow().isoformat()
            }

    @classmethod
    def _process_netbanking_payment(
            cls,
            amount: float,
            currency: str,
            details: Dict[str, Any],
            transaction_id: str
    ) -> Tuple[bool, Dict[str, Any]]:
        """Process net banking payment"""
        bank_code = details.get("bank_code", "")

        if random.random() < cls.SUCCESS_RATE:
            return True, {
                "transaction_id": transaction_id,
                "status": "completed",
                "amount": amount,
                "currency": currency,
                "bank_code": bank_code,
                "bank_reference": f"BNK{random.randint(1000000000, 9999999999)}",
                "processed_at": datetime.utcnow().isoformat(),
                "message": "Net banking payment successful"
            }
        else:
            return False, {
                "transaction_id": transaction_id,
                "status": "failed",
                "error": "Bank transaction failed",
                "error_code": "bank_error",
                "processed_at": datetime.utcnow().isoformat()
            }

    @classmethod
    def _process_wallet_payment(
            cls,
            amount: float,
            currency: str,
            details: Dict[str, Any],
            transaction_id: str
    ) -> Tuple[bool, Dict[str, Any]]:
        """Process wallet payment"""
        wallet_id = details.get("wallet_id", "")
        wallet_provider = details.get("wallet_provider", "")

        if random.random() < cls.SUCCESS_RATE:
            return True, {
                "transaction_id": transaction_id,
                "status": "completed",
                "amount": amount,
                "currency": currency,
                "wallet_provider": wallet_provider,
                "wallet_transaction_id": f"WLT{random.randint(100000000, 999999999)}",
                "processed_at": datetime.utcnow().isoformat(),
                "message": f"{wallet_provider} payment successful"
            }
        else:
            return False, {
                "transaction_id": transaction_id,
                "status": "failed",
                "error": "Wallet payment failed",
                "error_code": "wallet_insufficient_balance",
                "processed_at": datetime.utcnow().isoformat()
            }

    @classmethod
    def process_refund(
            cls,
            transaction_id: str,
            amount: float,
            reason: str
    ) -> Tuple[bool, Dict[str, Any]]:
        """Process refund"""
        time.sleep(random.uniform(0.3, 1.0))

        refund_id = f"refund_{uuid.uuid4().hex[:16]}"

        # Refunds are usually more reliable
        if random.random() < 0.95:
            return True, {
                "refund_id": refund_id,
                "original_transaction_id": transaction_id,
                "status": "refunded",
                "amount": amount,
                "reason": reason,
                "processed_at": datetime.utcnow().isoformat(),
                "message": "Refund processed successfully"
            }
        else:
            return False, {
                "refund_id": refund_id,
                "original_transaction_id": transaction_id,
                "status": "failed",
                "error": "Refund processing failed",
                "processed_at": datetime.utcnow().isoformat()
            }

    @classmethod
    def verify_payment(cls, transaction_id: str) -> Dict[str, Any]:
        """Verify payment status (webhook simulation)"""
        # In production, this would query the actual payment gateway
        return {
            "transaction_id": transaction_id,
            "verified": True,
            "status": "completed",
            "verified_at": datetime.utcnow().isoformat()
        }
