# filename: payment/payment_service.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

from sqlalchemy.orm import Session
from sqlalchemy import and_
from datetime import datetime
from fastapi import HTTPException
import json
import uuid
import asyncio

from models.models import (
    Booking, Payment, Seat, PaymentAuditLog, Event,
    BookingStatus, PaymentStatus, SeatStatus, PaymentMethod
)
from payment.payment_gateway import MockPaymentGateway
from app.lock_service import acquire_lock
from app.websocket_manager import manager


class PaymentService:
    """Service to handle payment processing with transaction safety"""

    @staticmethod
    def create_booking_with_payment(
            db: Session,
            user_id: str,
            event_id: str,
            seat_id: str,
            payment_method: str,
            payment_details: dict,
            idempotency_key: str = None
    ):
        """
        Create booking and process payment atomically

        Flow:
        1. Check idempotency (prevent duplicate requests)
        2. Acquire distributed lock on seat
        3. Verify seat availability
        4. Create booking record (pending)
        5. Create payment record (pending)
        6. Process payment with gateway
        7. Update booking/payment/seat based on result
        8. Broadcast WebSocket update
        9. Commit transaction
        """
        lock_key = f"booking:{event_id}:{seat_id}"

        try:
            # ==========================================
            # STEP 1: Check for duplicate request (idempotency)
            # ==========================================
            if idempotency_key:
                existing_booking = db.query(Booking).filter(
                    Booking.idempotency_key == idempotency_key
                ).first()

                if existing_booking:
                    return existing_booking, existing_booking.payment, "duplicate"

            # ==========================================
            # STEP 2-5: Acquire lock and create records
            # ==========================================
            with acquire_lock(lock_key, timeout=15):

                # Verify seat availability
                seat = db.query(Seat).filter(
                    and_(
                        Seat.seat_id == seat_id,
                        Seat.event_id == event_id
                    )
                ).with_for_update().first()

                if not seat:
                    raise HTTPException(status_code=404, detail="Seat not found")

                if seat.status == SeatStatus.BOOKED:
                    raise HTTPException(status_code=409, detail="Seat is already booked")

                # Get event for validation
                event = db.query(Event).filter(Event.event_id == event_id).first()
                if not event:
                    raise HTTPException(status_code=404, detail="Event not found")

                # Create booking (pending payment)
                booking = Booking(
                    user_id=user_id,
                    event_id=event_id,
                    seat_id=seat_id,
                    total_amount=seat.price,
                    status=BookingStatus.PENDING_PAYMENT,
                    idempotency_key=idempotency_key
                )
                db.add(booking)
                db.flush()

                # Create payment record
                payment = Payment(
                    booking_id=booking.booking_id,
                    user_id=user_id,
                    amount=seat.price,
                    currency="USD",
                    payment_method=PaymentMethod(payment_method),
                    status=PaymentStatus.PENDING
                )
                db.add(payment)
                db.flush()

                # Log payment initiation
                audit_log = PaymentAuditLog(
                    payment_id=payment.payment_id,
                    event_type="initiated",
                    old_status=None,
                    new_status="pending",
                    details="Payment initiated"
                )
                db.add(audit_log)

                # Update to processing
                booking.status = BookingStatus.PAYMENT_PROCESSING
                payment.status = PaymentStatus.PROCESSING
                db.flush()

                # ==========================================
                # STEP 6: Process payment with gateway
                # ==========================================
                success, gateway_response = MockPaymentGateway.process_payment(
                    amount=float(seat.price),
                    currency="USD",
                    payment_method=payment_method,
                    payment_details=payment_details
                )

                # ==========================================
                # STEP 7-9: Update based on result
                # ==========================================
                if success:
                    # ✅ PAYMENT SUCCESSFUL
                    payment.status = PaymentStatus.COMPLETED
                    payment.gateway_transaction_id = gateway_response.get("transaction_id")
                    payment.gateway_response = json.dumps(gateway_response)
                    payment.completed_at = datetime.utcnow()

                    # Store card details if applicable
                    if payment_method in ["credit_card", "debit_card"]:
                        payment.card_last4 = gateway_response.get("card_last4")
                        payment.card_brand = gateway_response.get("card_brand")

                    booking.status = BookingStatus.CONFIRMED

                    # Mark seat as booked
                    seat.status = SeatStatus.BOOKED
                    seat.booked_by = user_id
                    seat.booked_at = datetime.utcnow()

                    # Log success
                    audit_log = PaymentAuditLog(
                        payment_id=payment.payment_id,
                        event_type="completed",
                        old_status="processing",
                        new_status="completed",
                        details=f"Payment successful: {gateway_response.get('transaction_id')}"
                    )
                    db.add(audit_log)

                    # Commit transaction
                    db.commit()
                    db.refresh(booking)
                    db.refresh(payment)

                    # ✅ BROADCAST WEBSOCKET UPDATE
                    try:
                        asyncio.create_task(
                            manager.broadcast_to_event(
                                event_id=event_id,
                                message={
                                    "type": "seat_update",
                                    "action": "booked",
                                    "event_id": event_id,
                                    "seat_id": seat_id,
                                    "seat_number": seat.seat_number,
                                    "status": "booked",
                                    "booked_by": user_id,
                                    "booking_id": str(booking.booking_id),
                                    "timestamp": datetime.utcnow().isoformat()
                                }
                            )
                        )
                    except Exception as ws_error:
                        # Don't fail the booking if WebSocket fails
                        print(f"WebSocket broadcast failed: {ws_error}")

                    return booking, payment, "success"

                else:
                    # ❌ PAYMENT FAILED
                    payment.status = PaymentStatus.FAILED
                    payment.gateway_response = json.dumps(gateway_response)
                    payment.failed_at = datetime.utcnow()
                    payment.failure_reason = gateway_response.get("error", "Payment failed")

                    booking.status = BookingStatus.FAILED

                    # Log failure
                    audit_log = PaymentAuditLog(
                        payment_id=payment.payment_id,
                        event_type="failed",
                        old_status="processing",
                        new_status="failed",
                        details=f"Payment failed: {gateway_response.get('error')}"
                    )
                    db.add(audit_log)

                    db.commit()
                    db.refresh(booking)
                    db.refresh(payment)

                    raise HTTPException(
                        status_code=402,
                        detail={
                            "message": "Payment failed",
                            "error": gateway_response.get("error"),
                            "error_code": gateway_response.get("error_code"),
                            "booking_id": str(booking.booking_id),
                            "payment_id": str(payment.payment_id)
                        }
                    )

        except HTTPException:
            db.rollback()
            raise
        except Exception as e:
            db.rollback()
            raise HTTPException(status_code=500, detail=f"Booking failed: {str(e)}")

    @staticmethod
    async def process_refund(db: Session, booking_id: str, user_id: str, reason: str):
        """
        Process refund for a booking

        Flow:
        1. Validate booking exists and belongs to user
        2. Verify booking is refundable (status = confirmed)
        3. Process refund with payment gateway
        4. Update booking status to REFUNDED
        5. Update payment status to REFUNDED
        6. Release seat (status = AVAILABLE)
        7. Broadcast WebSocket update
        8. Commit transaction
        """
        try:
            # ==========================================
            # STEP 1-2: Validate booking
            # ==========================================
            booking = db.query(Booking).filter(Booking.booking_id == booking_id).first()

            if not booking:
                raise HTTPException(status_code=404, detail="Booking not found")

            if str(booking.user_id) != user_id:
                raise HTTPException(status_code=403, detail="Not your booking")

            if booking.status != BookingStatus.CONFIRMED:
                raise HTTPException(
                    status_code=400,
                    detail=f"Cannot refund booking in {booking.status.value} status"
                )

            payment = booking.payment
            if not payment or payment.status != PaymentStatus.COMPLETED:
                raise HTTPException(status_code=400, detail="No completed payment found")

            # ==========================================
            # STEP 3: Process refund with gateway
            # ==========================================
            success, refund_response = MockPaymentGateway.process_refund(
                transaction_id=payment.gateway_transaction_id,
                amount=float(payment.amount),
                reason=reason
            )

            if not success:
                raise HTTPException(
                    status_code=500,
                    detail=f"Refund processing failed: {refund_response.get('error')}"
                )

            # ==========================================
            # STEP 4-6: Update records and release seat
            # ==========================================
            payment.status = PaymentStatus.REFUNDED
            payment.refunded_at = datetime.utcnow()
            payment.refund_reason = reason
            payment.refund_transaction_id = refund_response.get("refund_id")

            booking.status = BookingStatus.REFUNDED
            booking.updated_at = datetime.utcnow()

            # Release seat
            seat = db.query(Seat).filter(Seat.seat_id == booking.seat_id).first()
            seat_number = None
            if seat:
                seat_number = seat.seat_number
                seat.status = SeatStatus.AVAILABLE
                seat.booked_by = None
                seat.booked_at = None

            # Log refund
            audit_log = PaymentAuditLog(
                payment_id=payment.payment_id,
                event_type="refunded",
                old_status="completed",
                new_status="refunded",
                details=f"Refund processed: {reason}"
            )
            db.add(audit_log)

            # Commit transaction
            db.commit()
            db.refresh(booking)
            db.refresh(payment)

            # ==========================================
            # STEP 7: Broadcast WebSocket update
            # ==========================================
            try:
                await manager.broadcast_to_event(
                    event_id=str(booking.event_id),
                    message={
                        "type": "seat_update",
                        "action": "released",
                        "event_id": str(booking.event_id),
                        "seat_id": str(booking.seat_id),
                        "seat_number": seat_number,
                        "status": "available",
                        "refund_id": payment.refund_transaction_id,
                        "timestamp": datetime.utcnow().isoformat()
                    }
                )
            except Exception as ws_error:
                # Don't fail the refund if WebSocket fails
                print(f"WebSocket broadcast failed: {ws_error}")

            return {
                "booking_id": str(booking_id),
                "payment_id": str(payment.payment_id),
                "refund_amount": float(payment.amount),
                "status": "refunded",
                "refund_transaction_id": payment.refund_transaction_id,
                "seat_released": True,
                "message": "Refund processed successfully and seat has been released"
            }

        except HTTPException:
            db.rollback()
            raise
        except Exception as e:
            db.rollback()
            raise HTTPException(status_code=500, detail=f"Refund failed: {str(e)}")
