# Code Generated by Sidekick is for learning and experimentation purposes only.

import datetime
import hashlib
import hmac
import json
import logging
from typing import Any

import httpx

logger = logging.getLogger(__name__)


async def send_webhook(
        merchant_webhook_url: str,
        merchant_webhook_secret: str,
        event_type: str,
        payload: dict[str, Any],
):
    """Send webhook to merchant with signature verification"""

    payload_with_event = {
        "event": event_type,
        "data": payload,
        "timestamp": datetime.now(tz=datetime.UTC).isoformat(),
    }

    payload_json = json.dumps(payload_with_event)

    signature = hmac.new(
        merchant_webhook_secret.encode(),
        payload_json.encode(),
        hashlib.sha256,
    ).hexdigest()

    headers = {
        "Content-Type": "application/json",
        "X-Webhook-Signature": signature,
        "X-Event-Type": event_type,
    }

    async with httpx.AsyncClient() as client:
        try:
            response = await client.post(
                merchant_webhook_url,
                content=payload_json,
                headers=headers,
                timeout=10.0,
            )
            return response.status_code == 200
        except Exception as e:
            logger.exception(f"Webhook delivery failed: {e}")
            return False
