# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: gateway/app/rate_limit.py
import time
import uuid
from fastapi import HTTPException
LUA = """
redis.call('ZREMRANGEBYSCORE', KEYS[1], 0, ARGV[1]-ARGV[2])
redis.call('ZADD', KEYS[1], ARGV[1], ARGV[4])
redis.call('EXPIRE', KEYS[1], math.ceil(ARGV[2]/1000)+1)
return redis.call('ZCARD', KEYS[1])
"""

async def enforce(redis, key: str, limit: int, window_seconds: int = 60):
    now = int(time.time() * 1000)
    count = await redis.eval(LUA, 1, f"rl:{key}", now, window_seconds * 1000, limit, f"{now}:{uuid.uuid4().hex}")
    if int(count) > limit:
        raise HTTPException(status_code=429, detail="Rate limit exceeded", headers={"Retry-After": str(window_seconds)})
