# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: RECON-02-ManualTrigger.ps1

$url = "http://localhost:8009/reconcile/run"

# ✏ Adjust limit or add specific payment_ids to narrow scope
$body = @{
    limit = 20
    # payment_ids = @("pi_abc123", "pi_def456")   # optional: specific IDs only
    # from_date   = "2025-07-01"                  # optional: date range
    # to_date     = "2025-07-16"
} | ConvertTo-Json

Write-Host "`n► POST $url  (MANUAL trigger)" -ForegroundColor Yellow
try {
    $r = Invoke-RestMethod -Uri $url -Method POST -Body $body -ContentType "application/json"
    Write-Host "✓ Manual reconciliation started" -ForegroundColor Green
    Write-Host "  Run ID  : $($r.run_id)"  -ForegroundColor Cyan
    Write-Host "  Trigger : $($r.trigger)" -ForegroundColor White
    Write-Host "  Status  : $($r.status)"  -ForegroundColor White
    Write-Host "  Message : $($r.message)" -ForegroundColor White

    $r.run_id | Set-Content "$PSScriptRoot/recon_run_id.txt"
    Write-Host "  ✔ Run ID saved to recon_run_id.txt" -ForegroundColor Cyan

    Write-Host "`n  Waiting 6s for completion..." -ForegroundColor Yellow
    Start-Sleep -Seconds 6

    $result = Invoke-RestMethod -Uri "http://localhost:8009/reconcile/results/$($r.run_id)" -Method GET
    $color  = if ($result.discrepancies_found -eq 0) { "Green" } else { "Red" }

    Write-Host "`n── RESULT ──────────────────────────────────────" -ForegroundColor Cyan
    Write-Host "  Status        : $($result.status)"               -ForegroundColor White
    Write-Host "  Trigger       : $($result.trigger)"              -ForegroundColor White
    Write-Host "  Total         : $($result.total_payments)"       -ForegroundColor White
    Write-Host "  Reconciled    : $($result.reconciled)"           -ForegroundColor Green
    Write-Host "  Discrepancies : $($result.discrepancies_found)"  -ForegroundColor $color
    Write-Host "  Completed At  : $($result.completed_at)"         -ForegroundColor White
    $result.summary | ConvertTo-Json
} catch {
    Write-Host "✗ Failed: $($_.ErrorDetails.Message)" -ForegroundColor Red
}
