# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: RECON-08-Discrepancies.ps1

$BASE = "http://localhost:8009/reconcile/discrepancies"

foreach ($filter in @("", "?severity=CRITICAL", "?severity=HIGH", "?layer=LEDGER", "?layer=BANK")) {
    $label = if ($filter) { $filter } else { "(all)" }
    Write-Host "`n► GET $BASE$filter  $label" -ForegroundColor Yellow
    try {
        $r   = Invoke-RestMethod -Uri "$BASE$filter" -Method GET
        $col = if ($r.Count -eq 0) { "Green" } else { "Red" }
        Write-Host "  Count: $($r.Count)" -ForegroundColor $col
        foreach ($d in $r) {
            Write-Host "  [$($d.layer)][$($d.severity)] $($d.payment_id) — $($d.message)" -ForegroundColor Red
        }
    } catch { Write-Host "  ✗ Failed: $_" -ForegroundColor Red }
}
