# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: RECON-03-ScheduleStatus.ps1

$url = "http://localhost:8009/reconcile/schedule"

Write-Host "`n► GET $url" -ForegroundColor Yellow
try {
    $r    = Invoke-RestMethod -Uri $url -Method GET
    $col  = if ($r.enabled) { "Green" } else { "Yellow" }
    Write-Host "✓ Schedule status retrieved" -ForegroundColor Green
    Write-Host "`n── EOD SCHEDULE ───────────────────────────────" -ForegroundColor Cyan
    Write-Host "  Enabled         : $($r.enabled)"                -ForegroundColor $col
    Write-Host "  Time            : $($r.hour):$("{0:D2}" -f $r.minute) $($r.timezone)" -ForegroundColor White
    Write-Host "  Next Run        : $($r.next_run)"               -ForegroundColor White
    Write-Host "  Last Run        : $($r.last_run)"               -ForegroundColor White
    Write-Host "  Last Run ID     : $($r.last_run_id)"            -ForegroundColor White
    Write-Host "  Last Run Status : $($r.last_run_status)"        -ForegroundColor White
    Write-Host "  Total Scheduled : $($r.total_scheduled_runs)"   -ForegroundColor White
    $r | ConvertTo-Json
} catch {
    Write-Host "✗ Failed: $_" -ForegroundColor Red
}
