# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: bank_connector/app/services/idempotency.py

import logging
from sqlalchemy.orm import Session
from bank_connector.app.models.transaction import ProcessorTransaction

logger = logging.getLogger(__name__)


def get_existing_transaction(
    db: Session, idempotency_key: str, payment_id: str, operation: str
) -> ProcessorTransaction | None:
    """
    Check if we already processed this request.
    Prevents double-charging if payment service retries.
    """
    if not idempotency_key:
        return None

    existing = (
        db.query(ProcessorTransaction)
        .filter(
            ProcessorTransaction.idempotency_key == idempotency_key,
            ProcessorTransaction.payment_id == payment_id,
            ProcessorTransaction.operation == operation,
            ProcessorTransaction.success == True,
        )
        .first()
    )

    if existing:
        logger.info(
            f"Idempotent hit: payment={payment_id} "
            f"operation={operation} key={idempotency_key}"
        )

    return existing
