# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: Payment/api/endpoints.py

from uuid import uuid4

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.orm import Session

from Payment.config.database import get_db
from Payment.models.enums import PaymentStatus
from Payment.models.payment import Payment

router = APIRouter()


class PaymentEngineIntentIn(BaseModel):
    amount: int
    currency: str
    order_id: str | None = None
    merchant_id: str


@router.post("/payment_intents")
async def store_payment_intent(
    payload: PaymentEngineIntentIn,
    db: Session = Depends(get_db),
):
    payment_id = f"pi_{uuid4().hex[:18]}"

    new_payment = Payment(
        id=payment_id,
        merchant_id=payload.merchant_id,
        customer_id=f"cust_{uuid4().hex[:10]}",
        order_id=payload.order_id,
        amount=payload.amount,
        currency=payload.currency,
        status=PaymentStatus.PENDING.value,
    )

    try:
        db.add(new_payment)
        db.commit()
        db.refresh(new_payment)
        return {
            "payment_id": new_payment.id,
            "status": new_payment.status,
        }
    except Exception as e:
        db.rollback()
        raise HTTPException(
            status_code=500,
            detail=f"Database write abort: {str(e)}",
        )
