# filename: payment/api/endpoints.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

import logging
from datetime import UTC, datetime, timedelta
from typing import Annotated
from uuid import uuid4

from elasticsearch import AsyncElasticsearch
from fastapi import (
    APIRouter,
    BackgroundTasks,
    Depends,
    Header,
    HTTPException,
    Query,
    Request,
    status,
)
from sqlalchemy.orm import Session

from fraud_service.app.services.fraud_client import check_fraud
from payment.config.database import get_db
from payment.models.enums import PaymentStatus, TransactionType
from payment.models.payment import Payment, Refund
from payment.schemas.payment import (
    CaptureRequest,
    CreatePaymentRequest,
    RefundRequest,
    VoidRequest,
)
from payment.search import (                          # ✅ was Payment.search
    get_es,
    index_payment_safely,
    search_payments,
)
from payment.services.bank_connector_client import (  # ✅ was Payment.services
    call_bank_authorize,
    call_bank_capture,
    call_bank_refund,
    call_bank_void,
)
from payment.services.ledger_client import (          # ✅ was Payment.services
    notify_authorization,
    notify_capture,
    notify_refund,
    notify_void,
)
from payment.services.capture_service import auto_capture        # ✅ was Payment.services.payment_service
from payment.services.transaction_service import log_transaction # ✅ was Payment.services
from payment.utils.cards import generate_card_fingerprint, get_card_brand  # ✅ was Payment.utils

logger = logging.getLogger(__name__)
router = APIRouter()


def build_payment_response(payment: Payment) -> dict:
    return {
        "payment_id":         payment.id,
        "merchant_id":        payment.merchant_id,
        "customer_id":        payment.customer_id,
        "order_id":           payment.order_id,
        "amount":             payment.amount,
        "currency":           payment.currency,
        "status":             payment.status,
        "authorization_code": payment.authorization_code,
        "authorized_at":      payment.authorized_at,
        "captured_at":        payment.captured_at,
        "voided_at":          payment.voided_at,
        "amount_captured":    payment.amount_captured,
        "amount_refunded":    payment.amount_refunded,
        "failure_code":       payment.failure_code,
        "failure_message":    payment.failure_message,
        "card_last4":         payment.card_last4,
        "card_brand":         payment.card_brand,
        "description":        payment.description,
        "metadata":           payment.metadata_json,
        "created_at":         payment.created_at,
        "updated_at":         payment.updated_at,
    }


# ─────────────────────────────────────────────────────────────────────────────
# CREATE PAYMENT INTENT
# ─────────────────────────────────────────────────────────────────────────────

@router.post("/payment_intents")
async def create_payment_intent(
    payload: CreatePaymentRequest,
    background_tasks: BackgroundTasks,
    request: Request,
    x_merchant_id: Annotated[str | None, Header(alias="X-Merchant-Id")] = None,
    idempotency_key: Annotated[str | None, Header(alias="Idempotency-Key")] = None,
    db: Session = Depends(get_db),
):
    merchant_id      = x_merchant_id or "m_123"
    temp_payment_id  = f"pi_pending_{uuid4().hex[:8]}"
    temp_customer_id = f"cust_{uuid4().hex[:8]}"

    fraud_result = await check_fraud(
        payment_id=temp_payment_id,
        merchant_id=merchant_id,
        amount=payload.amount,
        currency=payload.currency,
        card=payload.card,
        customer_id=temp_customer_id,
        customer_email=payload.customer.email,
        ip_address=(
            request.headers.get("x-forwarded-for") or request.client.host
        ),
        user_agent=request.headers.get("user-agent"),
    )

    if not fraud_result.get("allowed", True):
        logger.warning(
            "Payment blocked by fraud service: score=%s reason=%s",
            fraud_result.get("risk_score"),
            fraud_result.get("block_reason"),
        )
        raise HTTPException(
            status_code=status.HTTP_402_PAYMENT_REQUIRED,
            detail={
                "error":      "transaction_blocked",
                "code":       "fraud_detected",
                "message":    fraud_result.get("block_reason", "Transaction blocked"),
                "risk_score": fraud_result.get("risk_score"),
            },
        )

    if idempotency_key:
        existing = (
            db.query(Payment)
            .filter(
                Payment.idempotency_key == idempotency_key,
                Payment.merchant_id == merchant_id,
            )
            .first()
        )
        if existing:
            logger.info("Idempotent request: %s", idempotency_key)
            await index_payment_safely(app=request.app, payment=existing)
            return build_payment_response(existing)

    payment_id  = f"pi_{uuid4().hex[:18]}"
    card_number = payload.card.number
    card_brand  = get_card_brand(card_number)
    fingerprint = generate_card_fingerprint(card_number)

    payment = Payment(
        id=payment_id,
        merchant_id=merchant_id,
        customer_id=payload.customer.id or temp_customer_id,
        customer_email=payload.customer.email,
        customer_name=payload.customer.name,
        order_id=payload.order_id or f"ord_{uuid4().hex[:8]}",
        amount=payload.amount,
        currency=payload.currency,
        status=PaymentStatus.PENDING.value,
        description=payload.description,
        metadata_json=payload.metadata or {},
        card_last4=card_number[-4:],
        card_brand=card_brand,
        card_exp_month=payload.card.exp_month,
        card_exp_year=payload.card.exp_year,
        card_fingerprint=fingerprint,
        idempotency_key=idempotency_key,
        created_at=datetime.now(tz=UTC),
        updated_at=datetime.now(tz=UTC),
    )

    try:
        db.add(payment)
        db.commit()
        db.refresh(payment)
        await index_payment_safely(app=request.app, payment=payment)
        logger.info("Payment created: %s", payment_id)

        auth = await call_bank_authorize(
            payment.id,
            payload.amount,
            payload.card,
            merchant_id=merchant_id,
            idempotency_key=idempotency_key,
            currency=payload.currency,
            description=payload.description,
            metadata=payload.metadata,
        )

        if not auth["success"]:
            payment.status          = PaymentStatus.FAILED.value
            payment.failure_code    = auth.get("decline_code")
            payment.failure_message = auth.get("message")
            payment.updated_at      = datetime.now(tz=UTC)

            log_transaction(
                db=db,
                payment_id=payment.id,
                transaction_type=TransactionType.AUTHORIZATION,
                amount=payload.amount,
                currency=payload.currency,
                status="failed",
                failure_code=auth.get("decline_code"),
                failure_message=auth.get("message"),
                metadata=payload.metadata or {},
            )

            db.commit()
            db.refresh(payment)
            await index_payment_safely(app=request.app, payment=payment)

            raise HTTPException(
                status_code=status.HTTP_402_PAYMENT_REQUIRED,
                detail={
                    "error":   "payment_failed",
                    "code":    auth.get("decline_code"),
                    "message": auth.get("message"),
                },
            )

        payment.status                   = PaymentStatus.AUTHORIZED.value
        payment.authorization_code       = auth["authorization_code"]
        payment.authorized_at            = datetime.now(tz=UTC)
        payment.authorized_amount        = payload.amount
        payment.authorization_expires_at = datetime.now(tz=UTC) + timedelta(days=7)
        payment.updated_at               = datetime.now(tz=UTC)

        log_transaction(
            db=db,
            payment_id=payment.id,
            transaction_type=TransactionType.AUTHORIZATION,
            amount=payload.amount,
            currency=payload.currency,
            status="succeeded",
            bank_reference=auth["authorization_code"],
            metadata=payload.metadata or {},
        )

        db.commit()
        db.refresh(payment)
        await index_payment_safely(app=request.app, payment=payment)

        background_tasks.add_task(
            notify_authorization,
            payment_id=payment.id,
            merchant_id=merchant_id,
            amount=payload.amount,
            currency=payload.currency,
        )

        if payload.capture:
            background_tasks.add_task(auto_capture, payment.id, payload.amount, merchant_id)

        return build_payment_response(payment)

    except HTTPException:
        raise
    except Exception as exc:
        db.rollback()
        logger.exception("Payment intent failed")
        raise HTTPException(status_code=500, detail=f"Payment intent failed: {exc!s}") from exc


# ─────────────────────────────────────────────────────────────────────────────
# CAPTURE
# ─────────────────────────────────────────────────────────────────────────────

@router.post("/payments/{payment_id}/capture")
async def capture_payment(
    payment_id: str,
    payload: CaptureRequest,
    request: Request,
    background_tasks: BackgroundTasks,
    x_merchant_id: Annotated[str | None, Header(alias="X-Merchant-Id")] = None,
    db: Session = Depends(get_db),
):
    query = db.query(Payment).filter(Payment.id == payment_id)
    if x_merchant_id:
        query = query.filter(Payment.merchant_id == x_merchant_id)
    payment = query.first()

    if not payment:
        raise HTTPException(status_code=404, detail="Payment not found")

    if payment.status not in [
        PaymentStatus.AUTHORIZED.value,
        PaymentStatus.PARTIALLY_CAPTURED.value,
    ]:
        raise HTTPException(status_code=400, detail="Payment is not authorized")

    capture_amount = payload.amount or payment.authorized_amount or payment.amount
    if capture_amount <= 0:
        raise HTTPException(status_code=400, detail="Invalid capture amount")

    available = (payment.authorized_amount or payment.amount) - (payment.amount_captured or 0)
    if capture_amount > available:
        raise HTTPException(status_code=400, detail="Capture amount exceeds authorized amount")

    try:
        capture = await call_bank_capture(
            payment.id,
            payment.authorization_code,
            capture_amount,
            merchant_id=payment.merchant_id,
        )

        if not capture["success"]:
            payment.failure_message = capture.get("message")
            payment.updated_at = datetime.now(tz=UTC)
            db.commit()
            db.refresh(payment)
            await index_payment_safely(app=request.app, payment=payment)
            raise HTTPException(status_code=502, detail="Capture failed")

        payment.amount_captured = (payment.amount_captured or 0) + capture_amount
        payment.captured_at     = datetime.now(tz=UTC)
        payment.updated_at      = datetime.now(tz=UTC)
        payment.status = (
            PaymentStatus.CAPTURED.value
            if payment.amount_captured >= (payment.authorized_amount or payment.amount)
            else PaymentStatus.PARTIALLY_CAPTURED.value
        )

        log_transaction(
            db=db,
            payment_id=payment.id,
            transaction_type=TransactionType.CAPTURE,
            amount=capture_amount,
            currency=payment.currency,
            status="succeeded",
            bank_reference=capture["capture_reference"],
        )

        db.commit()
        db.refresh(payment)
        await index_payment_safely(app=request.app, payment=payment)

        background_tasks.add_task(
            notify_capture,
            payment_id=payment.id,
            merchant_id=payment.merchant_id,
            amount=capture_amount,
            currency=payment.currency,
        )

        return {
            "payment_id":        payment.id,
            "status":            payment.status,
            "captured_amount":   payment.amount_captured,
            "capture_reference": capture["capture_reference"],
        }

    except HTTPException:
        raise
    except Exception as exc:
        db.rollback()
        logger.exception("Capture failed for payment %s", payment_id)
        raise HTTPException(status_code=500, detail=f"Capture failed: {exc!s}") from exc


# ─────────────────────────────────────────────────────────────────────────────
# VOID
# ─────────────────────────────────────────────────────────────────────────────

@router.post("/payments/{payment_id}/void")
async def void_payment(
    payment_id: str,
    payload: VoidRequest,
    request: Request,
    background_tasks: BackgroundTasks,
    x_merchant_id: Annotated[str | None, Header(alias="X-Merchant-Id")] = None,
    db: Session = Depends(get_db),
):
    query = db.query(Payment).filter(Payment.id == payment_id)
    if x_merchant_id:
        query = query.filter(Payment.merchant_id == x_merchant_id)
    payment = query.first()

    if not payment:
        raise HTTPException(status_code=404, detail="Payment not found")

    if payment.status != PaymentStatus.AUTHORIZED.value:
        raise HTTPException(status_code=400, detail="Only authorized payments can be voided")

    try:
        result = await call_bank_void(
            payment.id,
            payment.authorization_code,
            merchant_id=payment.merchant_id,
        )

        if not result["success"]:
            raise HTTPException(status_code=502, detail="Void failed")

        payment.status      = PaymentStatus.VOIDED.value
        payment.voided_at   = datetime.now(tz=UTC)
        payment.void_reason = payload.reason
        payment.updated_at  = datetime.now(tz=UTC)

        log_transaction(
            db=db,
            payment_id=payment.id,
            transaction_type=TransactionType.VOID,
            amount=payment.authorized_amount or payment.amount,
            currency=payment.currency,
            status="succeeded",
            bank_reference=result["void_reference"],
            metadata={"reason": payload.reason} if payload.reason else {},
        )

        db.commit()
        db.refresh(payment)
        await index_payment_safely(app=request.app, payment=payment)

        background_tasks.add_task(
            notify_void,
            payment_id=payment.id,
            merchant_id=payment.merchant_id,
            amount=payment.authorized_amount or payment.amount,
            currency=payment.currency,
        )

        return {
            "payment_id":     payment.id,
            "status":         payment.status,
            "void_reference": result["void_reference"],
        }

    except HTTPException:
        raise
    except Exception as exc:
        db.rollback()
        logger.exception("Void failed for payment %s", payment_id)
        raise HTTPException(status_code=500, detail=f"Void failed: {exc!s}") from exc


# ─────────────────────────────────────────────────────────────────────────────
# REFUND
# ─────────────────────────────────────────────────────────────────────────────

@router.post("/payments/{payment_id}/refund")
async def refund_payment(
    payment_id: str,
    payload: RefundRequest,
    request: Request,
    background_tasks: BackgroundTasks,
    x_merchant_id: Annotated[str | None, Header(alias="X-Merchant-Id")] = None,
    db: Session = Depends(get_db),
):
    query = db.query(Payment).filter(Payment.id == payment_id)
    if x_merchant_id:
        query = query.filter(Payment.merchant_id == x_merchant_id)
    payment = query.first()

    if not payment:
        raise HTTPException(status_code=404, detail={"error": "payment_not_found"})

    if payment.status not in [
        PaymentStatus.CAPTURED.value,
        PaymentStatus.PARTIALLY_CAPTURED.value,
        PaymentStatus.PARTIALLY_REFUNDED.value,
    ]:
        raise HTTPException(
            status_code=400,
            detail={
                "error":          "invalid_state",
                "message":        f"Cannot refund payment in status: {payment.status}",
                "current_status": payment.status,
            },
        )

    available_to_refund = (payment.amount_captured or 0) - (payment.amount_refunded or 0)
    refund_amount = payload.amount or available_to_refund

    if refund_amount <= 0:
        raise HTTPException(
            status_code=400,
            detail={"error": "invalid_refund_amount", "message": "Refund amount must be greater than zero"},
        )

    if refund_amount > available_to_refund:
        raise HTTPException(
            status_code=400,
            detail={
                "error":   "amount_exceeds_refundable",
                "message": f"Requested: ${refund_amount / 100}, Available: ${available_to_refund / 100}",
            },
        )

    refund = Refund(
        id=f"re_{uuid4().hex}",
        payment_id=payment_id,
        merchant_id=payment.merchant_id,
        amount=refund_amount,
        currency=payment.currency,
        status="pending",
        reason=payload.reason,
        metadata_json=payload.metadata or {},
        created_at=datetime.now(tz=UTC),
    )
    db.add(refund)
    db.flush()

    try:
        refund_response = await call_bank_refund(
            payment.id,
            refund_amount,
            processor_id=payment.authorization_code,
            merchant_id=payment.merchant_id,
            reason=payload.reason,
        )

        if not refund_response["success"]:
            refund.status         = "failed"
            refund.failure_reason = refund_response.get("message")
            log_transaction(
                db, payment.id, TransactionType.REFUND, refund_amount,
                payment.currency, "failed", None, "refund_failed",
                refund_response.get("message"),
            )
            db.commit()
            raise HTTPException(
                status_code=500,
                detail={"error": "refund_failed", "message": refund_response.get("message")},
            )

        refund.status         = "succeeded"
        refund.succeeded_at   = datetime.now(tz=UTC)
        refund.bank_reference = refund_response["refund_reference"]

        payment.amount_refunded = (payment.amount_refunded or 0) + refund_amount
        payment.updated_at      = datetime.now(tz=UTC)
        payment.status = (
            PaymentStatus.REFUNDED.value
            if payment.amount_refunded >= (payment.amount_captured or 0)
            else PaymentStatus.PARTIALLY_REFUNDED.value
        )

        log_transaction(
            db, payment.id, TransactionType.REFUND, refund_amount,
            payment.currency, "success", refund_response["refund_reference"],
        )

        db.commit()
        db.refresh(payment)
        await index_payment_safely(app=request.app, payment=payment)

        background_tasks.add_task(
            notify_refund,
            payment_id=payment.id,
            merchant_id=payment.merchant_id,
            amount=refund_amount,
            currency=payment.currency,
            reason=payload.reason,
        )

        return {
            "id":           refund.id,
            "payment_id":   payment_id,
            "amount":       refund_amount,
            "currency":     payment.currency,
            "status":       "succeeded",
            "created":      refund.created_at.isoformat(),
            "succeeded_at": refund.succeeded_at.isoformat(),
        }

    except HTTPException:
        raise
    except Exception as exc:
        db.rollback()
        logger.exception("Refund failed for payment %s", payment_id)
        raise HTTPException(status_code=500, detail=f"Refund failed: {exc!s}") from exc


# ─────────────────────────────────────────────────────────────────────────────
# SEARCH  (must stay above /payments/{payment_id})
# ─────────────────────────────────────────────────────────────────────────────

@router.get("/payments/search")
async def search_payment_records(
    q: Annotated[str | None, Query(min_length=1)] = None,
    payment_status: Annotated[str | None, Query(alias="status", min_length=1)] = None,
    x_merchant_id: Annotated[str | None, Header(alias="X-Merchant-Id")] = None,
    page: Annotated[int, Query(ge=1)] = 1,
    size: Annotated[int, Query(ge=1, le=100)] = 25,
    es: AsyncElasticsearch = Depends(get_es),
):
    return await search_payments(
        es=es,
        query_text=q,
        status=payment_status,
        merchant_id=x_merchant_id,
        page=page,
        size=size,
    )


# ─────────────────────────────────────────────────────────────────────────────
# GET PAYMENT
# ─────────────────────────────────────────────────────────────────────────────

@router.get("/payments/{payment_id}")
async def get_payment(
    payment_id: str,
    x_merchant_id: Annotated[str | None, Header(alias="X-Merchant-Id")] = None,
    db: Session = Depends(get_db),
):
    query = db.query(Payment).filter(Payment.id == payment_id)
    if x_merchant_id:
        query = query.filter(Payment.merchant_id == x_merchant_id)
    payment = query.first()

    if not payment:
        raise HTTPException(status_code=404, detail="Payment not found")

    return build_payment_response(payment)


# ─────────────────────────────────────────────────────────────────────────────
# LIST PAYMENTS
# ─────────────────────────────────────────────────────────────────────────────

@router.get("/payments")
async def list_payments(
    x_merchant_id: Annotated[str | None, Header(alias="X-Merchant-Id")] = None,
    status: str | None = None,
    limit: Annotated[int, Query(ge=1, le=100)] = 10,
    offset: Annotated[int, Query(ge=0)] = 0,
    db: Session = Depends(get_db),
):
    query = db.query(Payment)
    if x_merchant_id:
        query = query.filter(Payment.merchant_id == x_merchant_id)
    if status:
        query = query.filter(Payment.status == status)

    total    = query.count()
    payments = query.order_by(Payment.created_at.desc()).limit(limit).offset(offset).all()

    return {
        "data":     [build_payment_response(p) for p in payments],
        "has_more": (offset + limit) < total,
        "total":    total,
    }
