# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: bank_connector/app/models/transaction.py

from datetime import datetime
from sqlalchemy import Boolean, Column, DateTime, Integer, JSON, String, Text, Float
from bank_connector.app.db import Base


class ProcessorTransaction(Base):
    """
    Records every call made to the bank/processor.
    Immutable audit log - never updated, only inserted.
    """
    __tablename__ = "processor_transactions"

    id = Column(String, primary_key=True)

    # Reference back to our system
    payment_id = Column(String, nullable=False, index=True)
    merchant_id = Column(String, nullable=False, index=True)
    idempotency_key = Column(String, nullable=True, index=True)

    # What we did
    operation = Column(String(20), nullable=False)  # authorize|capture|refund|void
    processor = Column(String(20), nullable=False)  # stripe|adyen|mock

    # What we sent
    amount = Column(Integer, nullable=False)
    currency = Column(String(10), nullable=False)
    card_last4 = Column(String(4), nullable=True)
    card_brand = Column(String(20), nullable=True)

    # What processor returned
    success = Column(Boolean, nullable=False)
    processor_id = Column(String(255), nullable=True)   # Stripe charge ID etc.
    processor_status = Column(String(50), nullable=True)
    authorization_code = Column(String(255), nullable=True)
    processor_response = Column(JSON, nullable=True)

    # Failure info
    failure_code = Column(String(100), nullable=True)
    failure_message = Column(Text, nullable=True)
    decline_code = Column(String(100), nullable=True)

    # Performance
    duration_ms = Column(Integer, nullable=True)
    retry_count = Column(Integer, default=0)

    created_at = Column(DateTime, default=datetime.utcnow, index=True)


class CircuitBreakerState(Base):
    """Persists circuit breaker state across restarts"""
    __tablename__ = "circuit_breaker_states"

    processor = Column(String(50), primary_key=True)
    state = Column(String(20), default="closed")  # closed|open|half_open
    failure_count = Column(Integer, default=0)
    last_failure_at = Column(DateTime, nullable=True)
    opened_at = Column(DateTime, nullable=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
