# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: fraud_service/app/services/fraud_client.py

import hashlib
import logging
import os

import httpx

logger = logging.getLogger(__name__)
FRAUD_SERVICE_URL = os.getenv("FRAUD_SERVICE_URL", "http://fraud-service:8004")


def get_card_fingerprint(card_number: str) -> str:
    return hashlib.sha256(card_number.encode()).hexdigest()


async def check_fraud(
    payment_id: str,
    merchant_id: str,
    amount: int,
    currency: str,
    card,
    customer_id: str,
    customer_email: str,
    ip_address: str | None = None,
    user_agent: str | None = None,
    http_client: httpx.AsyncClient = None,
) -> dict:
    """
    Call Fraud Service before bank authorization.
    Fail open: if fraud service is down, allow payment.
    """
    payload = {
        "payment_id": payment_id,
        "merchant_id": merchant_id,
        "amount": amount,
        "currency": currency,
        "card": {
            "number": card.number,
            "exp_month": card.exp_month,
            "exp_year": card.exp_year,
            "last4": card.number[-4:],
            "brand": "visa",
            "fingerprint": get_card_fingerprint(card.number),
        },
        "customer": {
            "id": customer_id,
            "email": customer_email,
            "ip_address": ip_address,
            "user_agent": user_agent,
        },
    }

    try:
        client = http_client or httpx.AsyncClient(timeout=5.0)
        response = await client.post(f"{FRAUD_SERVICE_URL}/check", json=payload)
        return response.json()
    except Exception as e: # noqa: BLE001
        logger.warning(f"Fraud service unavailable: {e} - failing open")
        return {"allowed": True, "risk_score": 0, "risk_level": "low", "block_reason": None}
