# Code Generated by Sidekick is for learning and experimentation purposes only.

import os


class Settings:
    service_name: str = os.getenv("SERVICE_NAME", "customer_service")

    # Use PostgreSQL, not SQLite
    database_url: str = os.getenv(
        "DATABASE_URL",
        "postgresql://payments:payments@postgres:5432/customer_db",
    )

    # ✅ FIXED: Point to Merchant Service instead of Payment Service
    merchant_service_url: str = os.getenv(
        "MERCHANT_SERVICE_URL",
        "http://merchant-service:8001",
    ).rstrip("/")

    checkout_session_ttl_minutes: int = int(
        os.getenv("CHECKOUT_SESSION_TTL_MINUTES", "30"),
    )
    payment_method_ttl_minutes: int = int(
        os.getenv("PAYMENT_METHOD_TTL_MINUTES", "15"),
    )


settings = Settings()
