# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: customer_service/app/main.py
from uuid import uuid4
from fastapi import FastAPI, Header
from pydantic import BaseModel

app = FastAPI(title="customer-service")

class PaymentSessionIn(BaseModel):
    cart_id: str
    amount: int
    currency: str

class TokenizeIn(BaseModel):
    card_number: str
    exp_month: int
    exp_year: int
    cvc: str

class ConfirmIn(BaseModel):
    payment_id: str
    payment_method_token: str

@app.get("/health")
async def health(): return {"status":"ok"}

@app.get("/config")
async def config(x_merchant_id: str = Header(...)):
    return {"merchant_id": x_merchant_id, "supported_methods": ["card"], "three_ds": True}

@app.post("/payment_sessions")
async def session(payload: PaymentSessionIn, x_merchant_id: str = Header(...), x_user_id: str = Header(...)):
    return {"session_id": f"ps_{uuid4().hex[:18]}", "merchant_id": x_merchant_id, "user_id": x_user_id, "cart_id": payload.cart_id, "amount": payload.amount, "currency": payload.currency, "status": "created"}

@app.post("/payment_methods/tokenize")
async def tokenize(payload: TokenizeIn, x_merchant_id: str = Header(...), x_user_id: str = Header(...)):
    return {"payment_method_token": f"pm_{uuid4().hex[:18]}", "merchant_id": x_merchant_id, "user_id": x_user_id, "last4": payload.card_number[-4:], "brand": "visa"}

@app.post("/payment_intents/confirm")
async def confirm(payload: ConfirmIn, x_merchant_id: str = Header(...), x_user_id: str = Header(...)):
    return {"payment_id": payload.payment_id, "payment_method_token": payload.payment_method_token, "merchant_id": x_merchant_id, "user_id": x_user_id, "status": "confirmed"}
