apiVersion: v1
kind: ServiceAccount
metadata:
  name: pdf-worker-sa
  namespace: pdf-gen
  annotations:
    ://amazonaws.com: arn:aws:iam::667383782466:role/pdf-generator-worker-role

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-secret-provider
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "prod/db/postgres-credentials-v"
        objectType: "secretsmanager"
        jmesPath:
          - path: "DATABASE_URL" 
            objectAlias: db_url
  secretObjects:
    - secretName: db-secrets-sync
      type: Opaque
      data:
        - objectName: db_url
          key: url
