apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-worker
  namespace: pdf-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-worker
  template:
    metadata:
      labels:
        app: pdf-worker
    spec:
      serviceAccountName: pdf-worker-sa
      
      # 🚀 KARPENTER TIP: Spread workers across different nodes/AZs
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: pdf-worker

      containers:
        - name: worker
          image: sandeshs/pdf-generator:fixed-v3
          imagePullPolicy: Always
          command: ["python", "-u", "worker.py"]
          
          # 🚀 KARPENTER TIP: Mandatory for scaling logic
          resources:
            requests:
              cpu: "250m"      # Reserved capacity on the node
              memory: "512Mi"
            limits:
              cpu: "500m"      # Hard cap
              memory: "1Gi"

          envFrom:
            - secretRef:
                name: pdf-generator-env
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: REDIS_HOST
              value: "cache-headless"

          livenessProbe:
            exec:
              command: ["pgrep", "-f", "worker.py"]
            initialDelaySeconds: 30
            periodSeconds: 60
