# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: Payment/schemas/payment.py

from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, EmailStr, Field, field_validator


class CardInfo(BaseModel):
    number: str = Field(..., min_length=13, max_length=19)
    exp_month: int = Field(..., ge=1, le=12)
    exp_year: int
    cvc: str = Field(..., min_length=3, max_length=4)

    @field_validator("number")
    @classmethod
    def validate_card(cls, v: str) -> str:
        v = v.replace(" ", "").replace("-", "")
        if not v.isdigit():
            raise ValueError("Card number must contain only digits")
        digits = [int(d) for d in v]
        checksum = sum(digits[-1::-2])
        for d in digits[-2::-2]:
            checksum += sum(int(x) for x in str(d * 2))
        if checksum % 10 != 0:
            raise ValueError("Invalid card number")
        return v

    @field_validator("exp_year")
    @classmethod
    def validate_exp_year(cls, v: int) -> int:
        if v < datetime.now(tz=timezone.utc).year:
            raise ValueError("Card expiration year is in the past")
        return v


class CustomerInfo(BaseModel):
    id: str | None = None          # ← ADDED: was missing, caused crash on payload.customer.id
    email: EmailStr
    name: str
    phone: str | None = None


class CreatePaymentRequest(BaseModel):
    amount: int = Field(..., gt=0, description="Amount in cents")
    currency: str = Field(default="usd", pattern="^[a-z]{3}$")
    customer: CustomerInfo
    card: CardInfo
    order_id: str | None = None
    description: str | None = None
    metadata: dict[str, Any] | None = None
    capture: bool = Field(default=False, description="Auto-capture if true")


class CaptureRequest(BaseModel):
    amount: int | None = Field(None, gt=0)


class VoidRequest(BaseModel):
    reason: str | None = None


class RefundRequest(BaseModel):
    amount: int | None = Field(None, gt=0)
    reason: str | None = None
    metadata: dict[str, Any] | None = None
