# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: Payment/schemas/payment.py

from datetime import datetime
from typing import Any, Dict, Optional

from pydantic import BaseModel, EmailStr, Field, field_validator


class CardInfo(BaseModel):
    number: str = Field(..., min_length=13, max_length=19)
    exp_month: int = Field(..., ge=1, le=12)
    exp_year: int
    cvc: str = Field(..., min_length=3, max_length=4)

    @field_validator("number")
    @classmethod
    def validate_card(cls, v: str) -> str:
        v = v.replace(" ", "").replace("-", "")
        if not v.isdigit():
            raise ValueError("Card number must contain only digits")

        digits = [int(d) for d in v]
        checksum = sum(digits[-1::-2])
        for d in digits[-2::-2]:
            checksum += sum(int(x) for x in str(d * 2))

        if checksum % 10 != 0:
            raise ValueError("Invalid card number")
        return v

    @field_validator("exp_year")
    @classmethod
    def validate_exp_year(cls, v: int) -> int:
        if v < datetime.utcnow().year:
            raise ValueError("Card expiration year is in the past")
        return v


class CustomerInfo(BaseModel):
    email: EmailStr
    name: str
    phone: Optional[str] = None


class CreatePaymentRequest(BaseModel):
    amount: int = Field(..., gt=0, description="Amount in cents")
    currency: str = Field(default="usd", pattern="^[a-z]{3}$")
    customer: CustomerInfo
    card: CardInfo
    order_id: Optional[str] = None
    description: Optional[str] = None
    metadata: Optional[Dict[str, Any]] = None
    capture: bool = Field(default=False, description="Auto-capture if true")


class CaptureRequest(BaseModel):
    amount: Optional[int] = Field(None, gt=0)


class VoidRequest(BaseModel):
    reason: Optional[str] = None


class RefundRequest(BaseModel):
    amount: Optional[int] = Field(None, gt=0)
    reason: Optional[str] = None
    metadata: Optional[Dict[str, Any]] = None
