apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: url-shortener

  # Infrastructure

  # Database

  # Application Services
resources:
- base-infra.yml
- configs.yaml
- cache-queue.yaml
- db-services.yaml
- postgres-primary.yaml
- postgres-replica.yaml
- write-service.yaml
- redirect-service.yaml
- analytics-workers.yaml
- nginx-cdn-deployment.yaml

# Images with commit SHA tags for full traceability
images:
- name: sandeshs/url-shortener-analytics-worker
  newName: sandeshs/url-shortener-analytics-worker
  newTag: 2d475710171b00f5ef775d9b58d349f92cef9f4d
- name: sandeshs/url-shortener-nginx-cdn
  newName: sandeshs/url-shortener-nginx-cdn
  newTag: 2d475710171b00f5ef775d9b58d349f92cef9f4d
- name: sandeshs/url-shortener-redirect-service
  newName: sandeshs/url-shortener-redirect-service
  newTag: 2d475710171b00f5ef775d9b58d349f92cef9f4d
- name: sandeshs/url-shortener-write-service
  newName: sandeshs/url-shortener-write-service
  newTag: 2d475710171b00f5ef775d9b58d349f92cef9f4d
