apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-cdn
  namespace: url-shortener
  labels:
    app: nginx-cdn
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx-cdn
  template:
    metadata:
      labels:
        app: nginx-cdn
    spec:
      containers:
        - name: nginx-cdn
          image: sandeshs/url-shortener-nginx-cdn:e2977650ccbdf7d67d1a58d7e5290d152de42ed3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
          livenessProbe:
            httpGet:
              path: /nginx-health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /nginx-health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

  # Strategy modified for fully automated execution
  strategy:
    canary:
      steps:
      - setWeight: 25           # Sends ~25% traffic to your new version
      - pause: { duration: 2m } # System waits exactly 2 minutes for sanity check
                                # Once 2m passes, it automatically jumps to 100%
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-cdn
  namespace: url-shortener
  labels:
    app: nginx-cdn
spec:
  type: LoadBalancer
  selector:
    app: nginx-cdn
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
