# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: app.py

from flask import Flask, redirect, request, jsonify, make_response
import logging
import os
import sys
from datetime import datetime

import psycopg2
import redis

from cache_manager import CacheManager
from click_tracker import ClickTracker
from analytics import AnalyticsService

# Add parent directory to path for config import
sys.path.append(os.path.join(os.path.dirname(__file__), "../.."))
from config import Config

from redirect_service_metrics import (
    track_request_metrics,
    track_db_query,
    track_redis_operation,
    metrics_endpoint,
    REDIRECTS_TOTAL,
    CACHE_HIT_COUNT,
    REDIRECT_ERRORS,
)

app = Flask(__name__)
app.add_url_rule("/metrics", "metrics", metrics_endpoint)

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def json_response(payload, status=200):
    return make_response(jsonify(payload), status)


# ============================
# Database Connection
# ============================

def get_db_connection():
    """Connect to PostgreSQL Replica (for reads)."""
    return psycopg2.connect(
        host=Config.DB_REPLICA_HOST,
        port=Config.DB_REPLICA_PORT,
        database=Config.DB_NAME,
        user=Config.DB_USER,
        password=Config.DB_PASSWORD,
    )


# ============================
# Initialize Services
# ============================

redis_client = redis.Redis(
    host=Config.REDIS_HOST,
    port=Config.REDIS_PORT,
    decode_responses=True,
)

cache_manager = CacheManager(redis_client)
click_tracker = ClickTracker()
analytics_service = AnalyticsService()


# ============================
# Metrics-wrapped helpers
# ============================

@track_redis_operation("get_url")
def get_cached_url(short_code):
    return cache_manager.get_url(short_code)


@track_redis_operation("set_url")
def set_cached_url(short_code, original_url):
    return cache_manager.set_url(short_code, original_url)


@track_db_query("healthcheck")
def check_database_health():
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        cursor.execute("SELECT 1")
        return cursor.fetchone()
    finally:
        cursor.close()
        conn.close()


@track_db_query("select_url_for_redirect")
def fetch_url_for_redirect(short_code):
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        cursor.execute(
            """
            SELECT url, status, expiration_time
            FROM urls
            WHERE short_url = %s
            """,
            (short_code,),
        )
        return cursor.fetchone()
    finally:
        cursor.close()
        conn.close()


@track_db_query("select_url_stats")
def fetch_url_stats(short_code):
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        cursor.execute(
            """
            SELECT url, clicks, created_at, last_accessed, status, created_by
            FROM urls
            WHERE short_url = %s
            """,
            (short_code,),
        )
        return cursor.fetchone()
    finally:
        cursor.close()
        conn.close()


@track_db_query("select_basic_analytics")
def fetch_basic_analytics(short_code):
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        cursor.execute(
            """
            SELECT short_url, url, status
            FROM urls
            WHERE short_url = %s
            """,
            (short_code,),
        )
        url_data = cursor.fetchone()

        if not url_data:
            return None, 0, []

        cursor.execute(
            "SELECT COUNT(*) FROM click_events WHERE short_url = %s",
            (short_code,),
        )
        total_result = cursor.fetchone()
        total_clicks = int(total_result[0]) if total_result and total_result[0] is not None else 0

        cursor.execute(
            """
            SELECT ip_address, clicked_at
            FROM click_events
            WHERE short_url = %s
            ORDER BY clicked_at DESC
            LIMIT 10
            """,
            (short_code,),
        )
        recent_clicks = cursor.fetchall()

        return url_data, total_clicks, recent_clicks
    finally:
        cursor.close()
        conn.close()


def get_client_ip():
    forwarded_for = request.headers.get("X-Forwarded-For")
    if forwarded_for:
        return forwarded_for.split(",")[0].strip()

    return (
        request.headers.get("X-Real-IP")
        or request.remote_addr
        or "Unknown"
    )


# ============================
# CORE ENDPOINTS
# ============================

@app.route("/", methods=["GET"])
@track_request_metrics
def index():
    return json_response(
        {
            "service": "URL Shortener - Redirect Service",
            "version": "1.0.0",
            "endpoints": {
                "redirect": "/<short_code>",
                "stats": "/stats/<short_code>",
                "health": "/health",
                "metrics": "/metrics",
                "analytics": {
                    "summary": "/analytics/<short_code>/summary",
                    "timeseries": "/analytics/<short_code>/timeseries",
                    "referrers": "/analytics/<short_code>/referrers",
                    "geography": "/analytics/<short_code>/geography",
                    "devices": "/analytics/<short_code>/devices",
                    "peak_hours": "/analytics/<short_code>/peak-hours",
                    "global": "/analytics/global",
                    "top_urls": "/analytics/top-urls",
                    "basic": "/analytics/<short_code>",
                },
            },
        },
        200,
    )


@app.route("/health", methods=["GET"])
@track_request_metrics
def health_check():
    health_status = {
        "status": "healthy",
        "service": "redirect-service",
        "timestamp": datetime.now().isoformat(),
        "checks": {},
    }

    overall_healthy = True

    try:
        check_database_health()
        health_status["checks"]["database"] = "connected"
    except Exception as exc:
        health_status["checks"]["database"] = f"failed: {str(exc)}"
        overall_healthy = False

    try:
        redis_client.ping()
        health_status["checks"]["redis"] = "connected"
    except Exception as exc:
        health_status["checks"]["redis"] = f"failed: {str(exc)}"
        overall_healthy = False

    try:
        channel = getattr(click_tracker, "channel", None)
        if channel is None or getattr(channel, "is_closed", False):
            raise RuntimeError("RabbitMQ channel unavailable")
        health_status["checks"]["rabbitmq"] = "connected"
    except Exception as exc:
        health_status["checks"]["rabbitmq"] = f"degraded: {str(exc)}"

    if not overall_healthy:
        health_status["status"] = "unhealthy"
        return json_response(health_status, 503)

    return json_response(health_status, 200)


@app.route("/<short_code>", methods=["GET"])
@track_request_metrics
def redirect_to_url(short_code):
    original_url = get_cached_url(short_code)

    if original_url:
        CACHE_HIT_COUNT.labels(status="hit").inc()
    else:
        CACHE_HIT_COUNT.labels(status="miss").inc()

        try:
            result = fetch_url_for_redirect(short_code)
        except Exception as exc:
            REDIRECT_ERRORS.labels(error_type="db_error").inc()
            return json_response(
                {
                    "error": "Database error",
                    "details": str(exc),
                },
                500,
            )

        if not result:
            REDIRECT_ERRORS.labels(error_type="not_found").inc()
            return json_response(
                {
                    "error": "URL not found",
                    "short_code": short_code,
                },
                404,
            )

        original_url, status, expiration_time = result

        if status != "active":
            REDIRECT_ERRORS.labels(error_type="inactive").inc()
            return json_response(
                {
                    "error": "URL is disabled",
                    "short_code": short_code,
                    "status": status,
                },
                410,
            )

        if expiration_time and datetime.now() > expiration_time:
            REDIRECT_ERRORS.labels(error_type="expired").inc()
            return json_response(
                {
                    "error": "URL has expired",
                    "short_code": short_code,
                    "expired_at": expiration_time.isoformat(),
                },
                410,
            )

        set_cached_url(short_code, original_url)

    try:
        click_data = {
            "short_url": short_code,
            "clicked_at": datetime.now().isoformat(),
            "user_agent": request.headers.get("User-Agent", "Unknown"),
            "ip_address": get_client_ip(),
            "referrer": request.headers.get("Referer"),
        }
        click_tracker.track_click(click_data)
    except Exception as exc:
        logger.warning("Failed to track click for %s: %s", short_code, exc)

    REDIRECTS_TOTAL.labels(short_code=short_code).inc()
    return redirect(original_url, code=301)


@app.route("/stats/<short_code>", methods=["GET"])
@track_request_metrics
def get_stats(short_code):
    try:
        result = fetch_url_stats(short_code)

        if not result:
            return json_response({"error": "URL not found"}, 404)

        url, clicks, created_at, last_accessed, status, created_by = result

        return json_response(
            {
                "short_url": f"{Config.BASE_URL}{short_code}",
                "original_url": url,
                "clicks": clicks,
                "created_at": created_at.isoformat() if created_at else None,
                "last_accessed": last_accessed.isoformat() if last_accessed else None,
                "status": status,
                "created_by": created_by,
            },
            200,
        )
    except Exception as exc:
        return json_response(
            {
                "error": "Failed to retrieve statistics",
                "details": str(exc),
            },
            500,
        )


# ============================
# ANALYTICS ENDPOINTS
# ============================

@app.route("/analytics/<short_code>/summary", methods=["GET"])
@track_request_metrics
def get_analytics_summary(short_code):
    try:
        summary = analytics_service.get_url_summary(short_code)
        if not summary:
            return json_response({"error": "URL not found"}, 404)
        return json_response(summary, 200)
    except Exception as exc:
        return json_response(
            {
                "error": "Failed to retrieve analytics summary",
                "details": str(exc),
            },
            500,
        )


@app.route("/analytics/<short_code>/timeseries", methods=["GET"])
@track_request_metrics
def get_timeseries(short_code):
    try:
        interval = request.args.get("interval", "day")
        days = int(request.args.get("days", 7))

        if interval not in ["hour", "day", "week"]:
            return json_response(
                {
                    "error": "Invalid interval",
                    "valid_values": ["hour", "day", "week"],
                },
                400,
            )

        if days < 1 or days > 365:
            return json_response({"error": "Days must be between 1 and 365"}, 400)

        data = analytics_service.get_clicks_over_time(short_code, interval, days)

        return json_response(
            {
                "short_url": short_code,
                "interval": interval,
                "days": days,
                "data_points": len(data),
                "data": data,
            },
            200,
        )
    except Exception as exc:
        return json_response(
            {
                "error": "Failed to retrieve time-series data",
                "details": str(exc),
            },
            500,
        )


@app.route("/analytics/<short_code>/referrers", methods=["GET"])
@track_request_metrics
def get_referrers(short_code):
    try:
        limit = int(request.args.get("limit", 10))

        if limit < 1 or limit > 100:
            return json_response({"error": "Limit must be between 1 and 100"}, 400)

        referrers = analytics_service.get_top_referrers(short_code, limit)

        return json_response(
            {
                "short_url": short_code,
                "limit": limit,
                "referrers": referrers,
            },
            200,
        )
    except Exception as exc:
        return json_response(
            {
                "error": "Failed to retrieve referrer data",
                "details": str(exc),
            },
            500,
        )


@app.route("/analytics/<short_code>/geography", methods=["GET"])
@track_request_metrics
def get_geography(short_code):
    try:
        geo_data = analytics_service.get_geographic_distribution(short_code)
        return json_response(
            {
                "short_url": short_code,
                "distribution": geo_data,
            },
            200,
        )
    except Exception as exc:
        return json_response(
            {
                "error": "Failed to retrieve geographic data",
                "details": str(exc),
            },
            500,
        )


@app.route("/analytics/<short_code>/devices", methods=["GET"])
@track_request_metrics
def get_devices(short_code):
    try:
        devices = analytics_service.get_device_breakdown(short_code)
        return json_response(
            {
                "short_url": short_code,
                "devices": devices,
            },
            200,
        )
    except Exception as exc:
        return json_response(
            {
                "error": "Failed to retrieve device data",
                "details": str(exc),
            },
            500,
        )


@app.route("/analytics/<short_code>/peak-hours", methods=["GET"])
@track_request_metrics
def get_peak_hours(short_code):
    try:
        peak_hours = analytics_service.get_peak_hours(short_code)
        return json_response(
            {
                "short_url": short_code,
                "hourly_distribution": peak_hours,
            },
            200,
        )
    except Exception as exc:
        return json_response(
            {
                "error": "Failed to retrieve peak hours data",
                "details": str(exc),
            },
            500,
        )


@app.route("/analytics/global", methods=["GET"])
@track_request_metrics
def get_global_stats():
    try:
        stats = analytics_service.get_global_statistics()
        return json_response(stats, 200)
    except Exception as exc:
        return json_response(
            {
                "error": "Failed to retrieve global statistics",
                "details": str(exc),
            },
            500,
        )


@app.route("/analytics/top-urls", methods=["GET"])
@track_request_metrics
def get_top_urls():
    try:
        limit = int(request.args.get("limit", 10))
        days = request.args.get("days")
        days = int(days) if days else None

        if limit < 1 or limit > 100:
            return json_response({"error": "Limit must be between 1 and 100"}, 400)

        if days and (days < 1 or days > 365):
            return json_response({"error": "Days must be between 1 and 365"}, 400)

        top_urls = analytics_service.get_top_urls(limit, days)

        return json_response(
            {
                "limit": limit,
                "days": days,
                "count": len(top_urls),
                "urls": top_urls,
            },
            200,
        )
    except Exception as exc:
        return json_response(
            {
                "error": "Failed to retrieve top URLs",
                "details": str(exc),
            },
            500,
        )


@app.route("/analytics/<short_code>", methods=["GET"])
@track_request_metrics
def get_analytics(short_code):
    try:
        url_data, total_clicks, recent_clicks = fetch_basic_analytics(short_code)

        if not url_data:
            return json_response({"error": "Short URL not found"}, 404)

        response = json_response(
            {
                "short_url": short_code,
                "original_url": url_data[1],
                "status": url_data[2],
                "total_clicks": total_clicks,
                "recent_clicks": [
                    {
                        "ip": click[0] if click[0] else "Unknown",
                        "timestamp": click[1].isoformat() if click[1] else None,
                    }
                    for click in recent_clicks
                ],
            },
            200,
        )
        response.headers.add("Access-Control-Allow-Origin", "*")
        return response
    except Exception as exc:
        logger.exception("Error fetching analytics for %s", short_code)
        return json_response(
            {
                "error": "Failed to fetch analytics",
                "details": str(exc),
            },
            500,
        )


# ============================
# ERROR HANDLERS
# ============================

@app.errorhandler(404)
def not_found(error):
    return json_response(
        {
            "error": "Endpoint not found",
            "status": 404,
        },
        404,
    )


@app.errorhandler(500)
def internal_error(error):
    return json_response(
        {
            "error": "Internal server error",
            "status": 500,
        },
        500,
    )


# ============================
# CLEANUP
# ============================

@app.teardown_appcontext
def cleanup(exception=None):
    if exception:
        logger.error("Error during request teardown: %s", exception)


# ============================
# MAIN
# ============================

if __name__ == "__main__":
    print("=" * 50)
    print("URL Shortener - Redirect Service")
    print("=" * 50)
    print("📍 Running on: http://0.0.0.0:5002")
    print("📊 Metrics endpoint: http://0.0.0.0:5002/metrics")
    print("📈 Analytics endpoints available at /analytics/*")
    print("🔍 Health check: http://0.0.0.0:5002/health")
    print("=" * 50)

    app.run(host="0.0.0.0", port=5002, debug=False)
