# Code Generated by Sidekick is for learning and experimentation purposes only.
# services/redirect_service/cache_manager.py

import redis
from config import Config


class CacheManager:
    """
    Manages Redis caching for URL lookups.
    Cache-aside pattern with TTL expiration.
    """

    def __init__(self, redis_client: redis.Redis):
        self.redis = redis_client

    def get_url(self, short_code: str) -> str | None:
        """
        Get original URL from cache.

        Returns:
            Original URL if cached, None if cache miss
        """
        key = f"url:{short_code}"
        return self.redis.get(key)

    def set_url(self, short_code: str, original_url: str) -> None:
        """
        Cache original URL with TTL.
        """
        key = f"url:{short_code}"
        self.redis.setex(key, Config.REDIS_TTL, original_url)

    def delete_url(self, short_code: str) -> None:
        """
        Invalidate cache entry.
        Used when URL is updated or deleted.
        """
        key = f"url:{short_code}"
        self.redis.delete(key)
