# Code Generated by Sidekick is for learning and experimentation purposes only.
# services/redirect_service/click_tracker.py

import pika
import json
import time
import sys
from config import Config


class ClickTracker:
    """
    Publishes click events to RabbitMQ for async processing.
    This prevents blocking the redirect response.
    """

    def __init__(self):
        self.connection = None
        self.channel = None
        self._connect()

    def _connect(self):
        """Establish RabbitMQ connection with retry logic"""
        max_retries = 10
        retry_delay = 3

        for attempt in range(max_retries):
            try:
                print(f"🔄 ClickTracker: Connecting to RabbitMQ (attempt {attempt + 1}/{max_retries})...")

                credentials = pika.PlainCredentials(
                    Config.RABBITMQ_USER,
                    Config.RABBITMQ_PASSWORD
                )

                parameters = pika.ConnectionParameters(
                    host=Config.RABBITMQ_HOST,
                    port=Config.RABBITMQ_PORT,
                    credentials=credentials,
                    heartbeat=600,  # Send heartbeat every 10 minutes
                    blocked_connection_timeout=300,  # Timeout after 5 minutes if blocked
                    connection_attempts=3,  # Retry 3 times on connection failure
                    retry_delay=2  # Wait 2 seconds between retries
                )

                self.connection = pika.BlockingConnection(parameters)
                self.channel = self.connection.channel()

                # Declare queue (idempotent - safe to call multiple times)
                self.channel.queue_declare(queue=Config.RABBITMQ_QUEUE, durable=True)

                print("✅ ClickTracker: Connected to RabbitMQ successfully!")
                return  # Success!

            except Exception as e:
                print(f"❌ ClickTracker: Connection attempt {attempt + 1} failed: {e}")
                if attempt < max_retries - 1:
                    print(f"⏳ Retrying in {retry_delay} seconds...")
                    time.sleep(retry_delay)
                else:
                    print("💥 ClickTracker: Max retries reached. Service will start but analytics may be degraded.")
                    # Don't crash the entire redirect service - just log the error
                    self.connection = None
                    self.channel = None
                    return

    def track_click(self, click_data: dict) -> None:
        """
        Send click event to RabbitMQ.

        Args:
            click_data: Dictionary with click information
        """
        # If connection never established, skip silently
        if not self.connection or not self.channel:
            print("⚠️ RabbitMQ not connected - click event skipped")
            return

        try:
            message = json.dumps(click_data)

            self.channel.basic_publish(
                exchange='',
                routing_key=Config.RABBITMQ_QUEUE,
                body=message,
                properties=pika.BasicProperties(
                    delivery_mode=2,  # Make message persistent
                )
            )
        except Exception as e:
            print(f"⚠️ Error publishing click event: {e}")
            # Try to reconnect and retry once
            try:
                print("🔄 Attempting to reconnect to RabbitMQ...")
                self._connect()

                # Retry the publish if reconnection succeeded
                if self.connection and self.channel:
                    self.channel.basic_publish(
                        exchange='',
                        routing_key=Config.RABBITMQ_QUEUE,
                        body=message,
                        properties=pika.BasicProperties(
                            delivery_mode=2,
                        )
                    )
                    print("✅ Click event published after reconnection")
                else:
                    print("❌ Reconnection failed - click event lost")
            except Exception as retry_error:
                print(f"❌ Retry failed: {retry_error}")

    def close(self):
        """Close RabbitMQ connection"""
        if self.connection and self.connection.is_open:
            self.connection.close()
            print("✅ ClickTracker: RabbitMQ connection closed")
11