# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: merchant_service/app/main.py
from uuid import uuid4
from fastapi import FastAPI, Header, HTTPException
from pydantic import BaseModel

app = FastAPI(title="merchant-service")
payments = {}

class PaymentIntentIn(BaseModel):
    amount: int
    currency: str
    order_id: str | None = None

class PaymentIdIn(BaseModel):
    payment_id: str
    amount: int | None = None

@app.get("/health")
async def health(): return {"status":"ok"}

@app.post("/payment_intents")
async def create_payment_intent(payload: PaymentIntentIn, x_merchant_id: str = Header(...)):
    pid = f"pi_{uuid4().hex[:18]}"
    payments[pid] = {"payment_id": pid, "merchant_id": x_merchant_id, "amount": payload.amount, "currency": payload.currency, "order_id": payload.order_id, "status": "requires_confirmation"}
    return payments[pid]

@app.post("/captures")
async def capture(payload: PaymentIdIn, x_merchant_id: str = Header(...)):
    p = payments.get(payload.payment_id)
    if not p or p["merchant_id"] != x_merchant_id: raise HTTPException(status_code=404, detail="Payment not found")
    p["status"] = "captured"; return p

@app.post("/refunds")
async def refund(payload: PaymentIdIn, x_merchant_id: str = Header(...)):
    p = payments.get(payload.payment_id)
    if not p or p["merchant_id"] != x_merchant_id: raise HTTPException(status_code=404, detail="Payment not found")
    return {"refund_id": f"re_{uuid4().hex[:18]}", "payment_id": payload.payment_id, "merchant_id": x_merchant_id, "amount": payload.amount, "status": "succeeded"}

@app.get("/payments/{payment_id}")
async def get_payment(payment_id: str, x_merchant_id: str = Header(...)):
    p = payments.get(payment_id)
    if not p or p["merchant_id"] != x_merchant_id: raise HTTPException(status_code=404, detail="Payment not found")
    return p

@app.get("/balance")
async def balance(x_merchant_id: str = Header(...)):
    total = sum(p["amount"] for p in payments.values() if p["merchant_id"] == x_merchant_id and p["status"] == "captured")
    return {"merchant_id": x_merchant_id, "available": total, "currency": "usd"}
