# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: bank_connector/app/schemas/connector.py

from pydantic import BaseModel
from typing import Optional


class CardDetails(BaseModel):
    number: str
    exp_month: int
    exp_year: int
    cvc: str


class AuthorizeRequest(BaseModel):
    payment_id: str
    merchant_id: str
    amount: int                          # cents
    currency: str
    card: CardDetails
    idempotency_key: Optional[str] = None
    description: Optional[str] = None
    metadata: Optional[dict] = None


class CaptureRequest(BaseModel):
    payment_id: str
    merchant_id: str
    processor_id: str                    # Stripe PaymentIntent ID
    authorization_code: str
    amount: int
    idempotency_key: Optional[str] = None


class RefundRequest(BaseModel):
    payment_id: str
    merchant_id: str
    processor_id: str                    # Stripe charge/payment_intent ID
    amount: Optional[int] = None         # None = full refund
    reason: Optional[str] = None
    idempotency_key: Optional[str] = None


class VoidRequest(BaseModel):
    payment_id: str
    merchant_id: str
    processor_id: str
    authorization_code: str
    idempotency_key: Optional[str] = None


class ProcessorResponse(BaseModel):
    success: bool
    processor: str
    processor_id: Optional[str] = None
    authorization_code: Optional[str] = None
    capture_reference: Optional[str] = None
    refund_reference: Optional[str] = None
    void_reference: Optional[str] = None
    amount: Optional[int] = None
    currency: Optional[str] = None
    card_last4: Optional[str] = None
    card_brand: Optional[str] = None
    failure_code: Optional[str] = None
    failure_message: Optional[str] = None
    decline_code: Optional[str] = None
    raw_response: Optional[dict] = None


class HealthResponse(BaseModel):
    status: str
    service: str
    stripe_connected: bool
    circuit_breakers: dict
