# Code Generated by Sidekick is for learning and experimentation purposes only.
output "cluster_name" {
  value = module.eks.cluster_name
}

output "rds_endpoint" {
  value = aws_db_instance.postgres.address
}

output "rds_secret_arn" {
  value = aws_db_instance.postgres.master_user_secret[0].secret_arn
}

output "irsa_role_arn" {
  value = module.worker_irsa.iam_role_arn
}
