# filename: Payment-gt/Deployments/generate-secrets.sh
# Code Generated by Sidekick is for learning and experimentation purposes only.
#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# Reads your .env file and creates ALL Kubernetes secrets imperatively.
# No base64 gymnastics. No secret values in YAML files.
# Run: chmod +x generate-secrets.sh && ./generate-secrets.sh
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

NS="payment-gt"
ENV_FILE=".env"

# ── Load .env into shell variables ───────────────────────────────────────────
set -o allexport
# shellcheck disable=SC1090
source "$ENV_FILE"
set +o allexport

echo "Creating secrets in namespace: $NS"

kubectl create secret generic postgres-secret \
  --namespace=payment-gt \
  --from-literal=POSTGRES_USER="payments" \
  --from-literal=POSTGRES_PASSWORD="PaySecure2026!" \
  --save-config --dry-run=client -o yaml | kubectl apply -f -

kubectl create secret generic redis-secret \
  --namespace=payment-gt \
  --from-literal=REDIS_PASSWORD="7kM9pX2vR4wB8zQ1nL6tJ3fG5sK2mN8b" \
  --save-config --dry-run=client -o yaml | kubectl apply -f -

# ── Verify both exist ─────────────────────────────────────────────────────────
kubectl get secrets -n payment-gt | grep -E "postgres|redis"

# ── Gateway ───────────────────────────────────────────────────────────────────
kubectl create secret generic gateway-secret \
  --namespace="$NS" \
  --from-literal=database-url="postgresql://payments:payments@postgres:5432/gateway_db" \
  --from-literal=key-hash-pepper="${KEY_HASH_PEPPER}" \
  --from-literal=seed-api-keys-json="${SEED_API_KEYS_JSON}" \
  --from-literal=internal-service-secret="${INTERNAL_SERVICE_SECRET}" \
  --from-literal=redis-url="${REDIS_URL}" \
  --save-config --dry-run=client -o yaml | kubectl apply -f -

# ── Auth Service ──────────────────────────────────────────────────────────────
kubectl create secret generic auth-service-secret \
  --namespace="$NS" \
  --from-literal=database-url="postgresql://payments:payments@postgres:5432/auth_db" \
  --from-literal=key-hash-pepper="${KEY_HASH_PEPPER}" \
  --save-config --dry-run=client -o yaml | kubectl apply -f -

# ── Customer Service ──────────────────────────────────────────────────────────
kubectl create secret generic customer-service-secret \
  --namespace="$NS" \
  --from-literal=database-url="postgresql://payments:payments@postgres:5432/customer_db" \
  --save-config --dry-run=client -o yaml | kubectl apply -f -

# ── Merchant Service ──────────────────────────────────────────────────────────
kubectl create secret generic merchant-service-secret \
  --namespace="$NS" \
  --from-literal=internal-service-secret="${INTERNAL_SERVICE_SECRET}" \
  --save-config --dry-run=client -o yaml | kubectl apply -f -

# ── Payment Service ───────────────────────────────────────────────────────────
kubectl create secret generic payment-service-secret \
  --namespace="$NS" \
  --from-literal=database-url="postgresql://payments:payments@postgres:5432/payment_db" \
  --save-config --dry-run=client -o yaml | kubectl apply -f -

# ── Fraud Service ─────────────────────────────────────────────────────────────
kubectl create secret generic fraud-service-secret \
  --namespace="$NS" \
  --from-literal=database-url="postgresql://payments:payments@postgres:5432/fraud_db" \
  --save-config --dry-run=client -o yaml | kubectl apply -f -

# ── Bank Connector ────────────────────────────────────────────────────────────
kubectl create secret generic bank-connector-secret \
  --namespace="$NS" \
  --from-literal=database-url="postgresql://payments:payments@postgres:5432/bank_connector_db" \
  --from-literal=stripe-secret-key="${STRIPE_SECRET_KEY}" \
  --from-literal=stripe-webhook-secret="${STRIPE_WEBHOOK_SECRET}" \
  --save-config --dry-run=client -o yaml | kubectl apply -f -

# ── Ledger Service ────────────────────────────────────────────────────────────
kubectl create secret generic ledger-service-secret \
  --namespace="$NS" \
  --from-literal=database-url="postgresql://payments:payments@postgres:5432/ledger_db" \
  --save-config --dry-run=client -o yaml | kubectl apply -f -

# ── Notification Service ──────────────────────────────────────────────────────
kubectl create secret generic notification-service-secret \
  --namespace="$NS" \
  --from-literal=database-url="postgresql://payments:payments@postgres:5432/notification_db" \
  --from-literal=webhook-signing-secret="${WEBHOOK_SIGNING_SECRET:-whsec_dev_secret_32_chars_minimum_x}" \
  --save-config --dry-run=client -o yaml | kubectl apply -f -

# ── Reconciliation Service ────────────────────────────────────────────────────
kubectl create secret generic reconciliation-service-secret \
  --namespace="$NS" \
  --from-literal=secret-key="${STRIPE_SECRET_KEY}" \
  --save-config --dry-run=client -o yaml | kubectl apply -f -

echo ""
echo "✅ All secrets created in namespace: $NS"
kubectl get secrets -n "$NS"
