# filename: Payment-gt/Deployments/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# ── Kubernetes manifest files for every service ──────────────────────────────
resources:
- gateway.yaml
- auth-service.yaml
- customer-service.yaml
- merchant-service.yaml
- payment-service.yaml
- fraud_service.yaml
- bank_connector.yaml
- ledger_service.yaml
- notification-service.yaml
- reconciliation-service.yaml

# ── Image tags — CI pipeline stamps newTag with ${{ github.sha }} ─────────────









images:
- name: sandeshs/payment-gt-auth-service
  newName: sandeshs/payment-gt-auth-service
  newTag: 1ba89b54e79aa990e7b7ab3ebd747da8a4d79d0e
- name: sandeshs/payment-gt-bank-connector
  newName: sandeshs/payment-gt-bank-connector
  newTag: 1ba89b54e79aa990e7b7ab3ebd747da8a4d79d0e
- name: sandeshs/payment-gt-bank_connector
  newName: sandeshs/payment-gt-bank_connector
  newTag: 5da143e3d5a7eb6fbddcb3b198338d404d1ef5e3
- name: sandeshs/payment-gt-customer-service
  newName: sandeshs/payment-gt-customer-service
  newTag: 1ba89b54e79aa990e7b7ab3ebd747da8a4d79d0e
- name: sandeshs/payment-gt-fraud-service
  newName: sandeshs/payment-gt-fraud-service
  newTag: 1ba89b54e79aa990e7b7ab3ebd747da8a4d79d0e
- name: sandeshs/payment-gt-fraud_service
  newName: sandeshs/payment-gt-fraud_service
  newTag: 5da143e3d5a7eb6fbddcb3b198338d404d1ef5e3
- name: sandeshs/payment-gt-gateway
  newName: sandeshs/payment-gt-gateway
  newTag: 1ba89b54e79aa990e7b7ab3ebd747da8a4d79d0e
- name: sandeshs/payment-gt-ledger-service
  newName: sandeshs/payment-gt-ledger-service
  newTag: 1ba89b54e79aa990e7b7ab3ebd747da8a4d79d0e
- name: sandeshs/payment-gt-ledger_service
  newName: sandeshs/payment-gt-ledger_service
  newTag: 5da143e3d5a7eb6fbddcb3b198338d404d1ef5e3
- name: sandeshs/payment-gt-merchant-service
  newName: sandeshs/payment-gt-merchant-service
  newTag: 1ba89b54e79aa990e7b7ab3ebd747da8a4d79d0e
- name: sandeshs/payment-gt-notification-service
  newName: sandeshs/payment-gt-notification-service
  newTag: 1ba89b54e79aa990e7b7ab3ebd747da8a4d79d0e
- name: sandeshs/payment-gt-payment-service
  newName: sandeshs/payment-gt-payment-service
  newTag: 1ba89b54e79aa990e7b7ab3ebd747da8a4d79d0e
- name: sandeshs/payment-gt-reconciliation-service
  newName: sandeshs/payment-gt-reconciliation-service
  newTag: 1ba89b54e79aa990e7b7ab3ebd747da8a4d79d0e
