# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: cluster-ready.tf

# Waits 30s after the EKS cluster and node group are fully Ready
# before Helm/kubectl providers attempt any API calls.
# This replaces the need for -target two-phase applies entirely.

resource "time_sleep" "wait_for_cluster" {
  create_duration = "30s"

  depends_on = [
    module.eks,
    aws_eks_access_entry.karpenter_node,
    aws_iam_role_policy_attachment.karpenter_node_policies,
    aws_iam_role_policy_attachment.karpenter_controller,
    aws_sqs_queue.karpenter_interruption
  ]
}

