#!/bin/bash
# filename: infra.sh
# Code Generated by Sidekick is for learning and experimentation purposes only.

set -euo pipefail

# ── Helm install check ────────────────────────────────────────────────────────
if ! command -v helm &> /dev/null; then
  echo "⚠️  Helm not found. Installing..."
  curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  echo "✅ Helm installed"
else
  echo "✅ Helm already installed: $(helm version --short)"
fi

# ── Pull ESO role ARN from Terraform ─────────────────────────────────────────
ESO_ROLE_ARN=$(terraform -chdir=. output -raw eso_role_arn)

if [ -z "$ESO_ROLE_ARN" ]; then
  echo "❌ Could not retrieve eso_role_arn. Run 'terraform apply' first."
  exit 1
fi

echo "✅ ESO Role ARN: $ESO_ROLE_ARN"

# ── Add correct Helm repo ─────────────────────────────────────────────────────
helm repo add external-secrets https://charts.external-secrets.io   # ✅ fixed
helm repo update

# ── Install / upgrade ESO ─────────────────────────────────────────────────────
helm upgrade --install external-secrets \
  external-secrets/external-secrets \
  --namespace external-secrets \
  --create-namespace \
  --set serviceAccount.name=external-secrets-sa \
  --set "serviceAccount.annotations.eks\.amazonaws\.com/role-arn=${ESO_ROLE_ARN}" \
  --set webhook.port=9443 \
  --wait                                        # ← blocks until pods are Ready

echo "✅ ESO deployed"

# ── Verify pods are running before continuing ─────────────────────────────────
echo "🔍 ESO pod status:"
kubectl get pods -n external-secrets

