# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: outputs.tf

# ─── EKS ────────────────────────────────────────────────────────────────────

output "cluster_name" {
  description = "EKS cluster name"
  value       = module.eks.cluster_name
}

output "cluster_endpoint" {
  description = "EKS cluster API endpoint"
  value       = module.eks.cluster_endpoint
}

output "oidc_provider_arn" {
  description = "OIDC provider ARN for IRSA"
  value       = module.eks.oidc_provider_arn
}

# ─── Karpenter ──────────────────────────────────────────────────────────────

output "karpenter_controller_role_arn" {
  description = "IAM role ARN for Karpenter controller"
  value       = aws_iam_role.karpenter_controller.arn
}

output "karpenter_node_role_arn" {
  description = "IAM role ARN for nodes Karpenter launches"
  value       = aws_iam_role.karpenter_node.arn
}

output "karpenter_interruption_queue_url" {
  description = "SQS queue URL for Karpenter spot interruption handling"
  value       = aws_sqs_queue.karpenter_interruption.url
}

# ─── OpenSearch ─────────────────────────────────────────────────────────────

output "opensearch_endpoint" {
  description = "OpenSearch domain endpoint"
  value       = aws_opensearch_domain.main.endpoint
}

output "opensearch_domain_name" {
  description = "OpenSearch domain name"
  value       = aws_opensearch_domain.main.domain_name
}

output "opensearch_secret_arn" {
  description = "Secrets Manager ARN for OpenSearch credentials"
  value       = aws_secretsmanager_secret.opensearch_secret.arn
}

# ─── Redis (ElastiCache) ────────────────────────────────────────────────────

output "redis_primary_endpoint" {
  description = "Redis primary endpoint address"
  value       = aws_elasticache_replication_group.redis.primary_endpoint_address
}

output "redis_reader_endpoint" {
  description = "Redis reader endpoint address"
  value       = aws_elasticache_replication_group.redis.reader_endpoint_address
}

output "redis_port" {
  description = "Redis port"
  value       = 6379
}

