# # Code Generated by Sidekick is for learning and experimentation purposes only.
# # filename: rds.tf
#
# # ── DB Subnet Group ───────────────────────────────────────────────────────────
# resource "aws_db_subnet_group" "postgres" {
#   name       = "${var.project}-db-subnet-group"
#   subnet_ids = aws_subnet.private[*].id
#   tags       = { Name = "${var.project}-db-subnet-group" }
# }
#
# # ── Parameter Group (PostgreSQL 16) ──────────────────────────────────────────
# resource "aws_db_parameter_group" "postgres16" {
#   name   = "${var.project}-postgres16"
#   family = "postgres16"
#
#   parameter {
#     name  = "log_connections"
#     value = "1"
#   }
#   parameter {
#     name  = "log_disconnections"
#     value = "1"
#   }
#   parameter {
#     name  = "log_min_duration_statement"
#     value = "1000"   # log queries > 1s
#   }
#
#   # REMOVED: shared_preload_libraries = "pg_stat_statements"
#   # This prevents the micro instance engine from encountering boot loops during creation.
#
#   tags = { Name = "${var.project}-pg16-params" }
# }
#
# # ── RDS Instance ──────────────────────────────────────────────────────────────
# resource "aws_db_instance" "postgres" {
#   identifier        = "${var.project}-postgres"
#   engine            = "postgres"
#   engine_version    = var.db_engine_version
#   instance_class    = var.db_instance_class
#
#   allocated_storage     = var.db_allocated_storage
#   max_allocated_storage = var.db_max_allocated_storage
#   storage_type          = "gp3"
#   storage_encrypted     = true
#
#   db_name  = "postgres"   # master DB; service databases created via rds_databases.tf
#   username = var.db_username
#   password = var.db_password
#
#   db_subnet_group_name   = aws_db_subnet_group.postgres.name
#   parameter_group_name   = aws_db_parameter_group.postgres16.name
#   vpc_security_group_ids = [aws_security_group.rds.id]
#
#   multi_az               = var.db_multi_az
#   publicly_accessible    = false
#   deletion_protection    = var.db_deletion_protection
#   skip_final_snapshot    = !var.db_deletion_protection
#   final_snapshot_identifier = var.db_deletion_protection ? "${var.project}-final-snapshot" : null
#
#   # OPTIMIZATION: Reduced from 7 to 1 day for storage footprint savings.
#   # Automated snapshots count against your total RDS backup storage allocations.
#   backup_retention_period   = 1
#   backup_window             = "03:00-04:00"
#   maintenance_window        = "mon:04:00-mon:05:00"
#   auto_minor_version_upgrade = true
#
#   # FIXED: Set to false to prevent un-allocatable Free Tier metrics billing
#   performance_insights_enabled          = false
#   performance_insights_retention_period = 0
#
#   # FIXED: Removed active CloudWatch streaming arrays to avoid metric ingestion charges
#   enabled_cloudwatch_logs_exports = []
#
#   tags = { Name = "${var.project}-postgres" }
# }
#
# # ── Secrets Manager — store DB credentials ────────────────────────────────────
# resource "aws_secretsmanager_secret" "db_credentials" {
#   name                    = "${var.project}/db/credentials"
#   recovery_window_in_days = 0 # Forces complete immediate deletion if destroyed during dev
# }
#
# resource "aws_secretsmanager_secret_version" "db_credentials" {
#   secret_id = aws_secretsmanager_secret.db_credentials.id
#   secret_string = jsonencode({
#     username = var.db_username
#     password = var.db_password
#     host     = aws_db_instance.postgres.address
#     port     = 5432
#     dbname   = "postgres"
#   })
# }
