# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: vpc.tf

locals {
  full_cluster_name = "${var.environment}-${var.cluster_name}"
  # Produces: "production-core-eks"
}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 5.0"

  name = "${local.full_cluster_name}-vpc"
  cidr = "10.0.0.0/16"  # matches VPC vpc-0f549fb7a878681d3

  # FIXED: 3 AZs to match 3 existing subnet pairs
  azs = [
    "${var.aws_region}a",
    "${var.aws_region}b",
    "${var.aws_region}c"
  ]

  # FIXED: exact /20 CIDRs from state — do not change these
  private_subnets = ["10.0.0.0/20", "10.0.16.0/20", "10.0.32.0/20"]
  public_subnets  = ["10.0.64.0/20", "10.0.80.0/20", "10.0.96.0/20"]

  enable_nat_gateway   = true
  single_nat_gateway   = true
  enable_dns_hostnames = true
  enable_dns_support   = true

  # Preserving map_public_ip_on_launch=false (matches current state)
  # Nodes use private subnets only — NAT gateway handles egress
  map_public_ip_on_launch = false

  public_subnet_tags = {
    "kubernetes.io/role/elb"                           = "1"
    "kubernetes.io/cluster/${local.full_cluster_name}" = "shared"
  }

  private_subnet_tags = {
    "kubernetes.io/role/internal-elb"                  = "1"
    "kubernetes.io/cluster/${local.full_cluster_name}" = "shared"
    "karpenter.sh/discovery"                           = local.full_cluster_name
  }

  tags = {
    Environment = var.environment
    Terraform   = "true"
  }
}

