version: '3.8'

services:
  # The FastAPI Application
  app:
    image: sandeshs/pdf-generator:latest
    container_name: fastapi_app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started

  worker:
    image: sandeshs/pdf-generator:latest
    container_name: pdf_worker
    command: python -u worker.py
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - BUCKET_NAME=pdf-generator-sandesh
      - AWS_DEFAULT_REGION=us-east-1
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis Queue
  cache:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
