version: '3.8'

services:
  # The FastAPI Application
  app:
    image: sandeshs/pdf-generator:latest
    container_name: fastapi_app
    ports:
      - "8080:8080"
    environment:
      # - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
      - DATABASE_URL=postgresql://dbadmin:CMI)E0(g]0Uc!FaMw9Oz@prod-postgres.cydmkoy6etoi.us-east-1.rds.amazonaws.com:5432/production_db
      - REDIS_HOST=master.pdf-gen-redis-public.dil7md.use1.cache.amazonaws.com
      - REDIS_PORT=6379
      - REDIS_PASS=f8t8k3JCKwVQPbYxZjzcIFpulPVaE0zK


  worker:
    image: sandeshs/pdf-generator:latest
    container_name: pdf_worker
    command: python -u worker.py
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=master.pdf-gen-redis-public.dil7md.use1.cache.amazonaws.com
      - REDIS_PORT=6379
      - REDIS_PASS=f8t8k3JCKwVQPbYxZjzcIFpulPVaE0zK
      - BUCKET_NAME=pdf-generator-sandesh
      - AWS_DEFAULT_REGION=us-east-1
      - DATABASE_URL=postgresql://dbadmin:CMI)E0(g]0Uc!FaMw9Oz@prod-postgres.cydmkoy6etoi.us-east-1.rds.amazonaws.com:5432/production_db

