# Code Generated by Sidekick is for learning and experimentation purposes only.
import json
import os
from io import BytesIO

import boto3
import psycopg2
import redis
from xhtml2pdf import pisa

REDIS_HOST = os.getenv("REDIS_HOST", "cache")
REDIS_PORT = int(os.getenv("REDIS_PORT", 6379))
REDIS_PASS = os.getenv("REDIS_PASS")

MAIN_QUEUE = "job_queue"
PROCESSING_QUEUE = "job_queue_processing"
DLQ_QUEUE = "job_queue_dlq"
DEFAULT_MAX_RETRIES = 3

REDIS_CONN = redis.Redis(
    host=REDIS_HOST,
    port=REDIS_PORT,
    db=0,
    password=REDIS_PASS or None,
    decode_responses=True
)

s3s = boto3.client(
    "s3",
    aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
    aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
    region_name=os.getenv("AWS_DEFAULT_REGION", "us-east-2")
)

BUCKET_NAME = "pdf-generator-sandeshs"
DB_CONFIG = os.getenv("DATABASE_URL", "postgresql://user:password@db:5432/mydatabase")

def update_job_status(job_id, status, download_url=None):
    try:
        conn = psycopg2.connect(DB_CONFIG)
        cur = conn.cursor()

        if download_url:
            cur.execute(
                "UPDATE jobs SET status = %s, download_url = %s WHERE job_id = %s",
                (status, download_url, job_id)
            )
        else:
            cur.execute(
                "UPDATE jobs SET status = %s WHERE job_id = %s",
                (status, job_id)
            )

        conn.commit()
        cur.close()
        conn.close()
    except Exception as e:
        print(f"❌ DB Update Failed: {e}")

def move_to_dlq(raw_job, job, err):
    job["retry_count"] = job.get("retry_count", 0) + 1
    job["last_error"] = str(err)

    REDIS_CONN.lrem(PROCESSING_QUEUE, 1, raw_job)
    REDIS_CONN.lpush(DLQ_QUEUE, json.dumps(job))
    update_job_status(job["job_id"], "failed")
    print(f"☠️ Job {job['job_id']} moved to DLQ")

def retry_job(raw_job, job, err):
    job["retry_count"] = job.get("retry_count", 0) + 1
    job["last_error"] = str(err)

    REDIS_CONN.lrem(PROCESSING_QUEUE, 1, raw_job)
    REDIS_CONN.lpush(MAIN_QUEUE, json.dumps(job))
    update_job_status(job["job_id"], "pending")
    print(f"🔁 Job {job['job_id']} requeued (retry {job['retry_count']})")

def process_worker():
    print(f"🚀 Worker ready. Watching {MAIN_QUEUE}...")

    while True:
        raw_job = REDIS_CONN.brpoplpush(MAIN_QUEUE, PROCESSING_QUEUE, timeout=0)
        if not raw_job:
            continue

        job = json.loads(raw_job)
        job_id = job["job_id"]
        retry_count = job.get("retry_count", 0)
        max_retries = job.get("max_retries", DEFAULT_MAX_RETRIES)

        print(f"📦 Processing job {job_id} (retry {retry_count}/{max_retries})")
        update_job_status(job_id, "processing")

        try:
            params = job["data"].get("params", {})

            html = f"<h1>Job {job_id}</h1><p>{json.dumps(params)}</p>"
            pdf_buffer = BytesIO()
            pisa.CreatePDF(html, dest=pdf_buffer)
            pdf_buffer.seek(0)

            s3_key = f"outputs/{job_id}.pdf"
            s3s.upload_fileobj(pdf_buffer, BUCKET_NAME, s3_key)

            presigned_url = s3s.generate_presigned_url(
                "get_object",
                Params={"Bucket": BUCKET_NAME, "Key": s3_key},
                ExpiresIn=3600
            )

            REDIS_CONN.lrem(PROCESSING_QUEUE, 1, raw_job)
            update_job_status(job_id, "completed", download_url=presigned_url)
            print(f"✅ Job {job_id} completed")

        except Exception as e:
            print(f"❌ Job {job_id} error: {e}")

            if retry_count + 1 >= max_retries:
                move_to_dlq(raw_job, job, e)
            else:
                retry_job(raw_job, job, e)

if __name__ == "__main__":
    process_worker()
