# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: reconciliation-service/models.py

from pydantic import BaseModel, Field
from typing import Optional, List, Dict
from datetime import datetime
from enum import Enum


# ── Enums ─────────────────────────────────────────────────────────────────────

class DiscrepancyType(str, Enum):
    MISSING_LEDGER_ENTRY     = "MISSING_LEDGER_ENTRY"
    LEDGER_AMOUNT_MISMATCH   = "LEDGER_AMOUNT_MISMATCH"
    MISSING_BANK_TRANSACTION = "MISSING_BANK_TRANSACTION"
    BANK_AMOUNT_MISMATCH     = "BANK_AMOUNT_MISMATCH"
    MISSING_MERCHANT_RECORD  = "MISSING_MERCHANT_RECORD"
    STATUS_MISMATCH          = "STATUS_MISMATCH"
    DOUBLE_ENTRY             = "DOUBLE_ENTRY"


class Severity(str, Enum):
    LOW      = "LOW"
    MEDIUM   = "MEDIUM"
    HIGH     = "HIGH"
    CRITICAL = "CRITICAL"


class TriggerType(str, Enum):
    MANUAL    = "MANUAL"
    SCHEDULED = "SCHEDULED"


# ── Core models ───────────────────────────────────────────────────────────────

class Discrepancy(BaseModel):
    payment_id  : str
    type        : DiscrepancyType
    severity    : Severity
    layer       : str
    expected    : Optional[str] = None
    actual      : Optional[str] = None
    message     : str
    detected_at : datetime = Field(default_factory=datetime.utcnow)


class PaymentRecord(BaseModel):
    payment_id      : str
    gateway_amount  : Optional[int] = None
    gateway_status  : Optional[str] = None
    ledger_amount   : Optional[int] = None
    ledger_entries  : int           = 0
    bank_amount     : Optional[int] = None
    bank_status     : Optional[str] = None
    merchant_amount : Optional[int] = None
    merchant_status : Optional[str] = None
    is_reconciled   : bool          = False
    discrepancies   : List[Discrepancy] = []


class ReconcileRequest(BaseModel):
    limit       : int                 = 500
    from_date   : Optional[str]       = None
    to_date     : Optional[str]       = None
    payment_ids : Optional[List[str]] = None


class ReconcileResult(BaseModel):
    run_id              : str
    trigger             : TriggerType = TriggerType.MANUAL
    status              : str
    started_at          : datetime
    completed_at        : Optional[datetime] = None
    total_payments      : int = 0
    reconciled          : int = 0
    discrepancies_found : int = 0
    payments            : List[PaymentRecord] = []
    summary             : Dict = {}


# ── Schedule models ───────────────────────────────────────────────────────────

class ScheduleConfig(BaseModel):
    enabled  : bool = True
    hour     : int  = 23        # 11 PM
    minute   : int  = 0
    timezone : str  = "America/New_York"
    limit    : int  = 500


class ScheduleStatus(BaseModel):
    enabled          : bool
    next_run         : Optional[str] = None
    last_run         : Optional[str] = None
    last_run_id      : Optional[str] = None
    last_run_status  : Optional[str] = None
    hour             : int
    minute           : int
    timezone         : str
    total_scheduled_runs : int = 0
