# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: reconciliation-service/reconciler.py

import asyncio
import logging
from datetime import datetime
from typing import Dict, List, Optional

import httpx

import config
from models import (
    Discrepancy, DiscrepancyType, Severity,
    PaymentRecord, ReconcileRequest, ReconcileResult, TriggerType
)

logger = logging.getLogger("reconciler")

GW_HEADERS = {"Authorization": f"Bearer {config.SECRET_KEY}", "Content-Type": "application/json"}
MR_HEADERS = {"Authorization": f"Bearer {config.SECRET_KEY}"}


class Reconciler:
    def __init__(self):
        self.results           : Dict[str, ReconcileResult] = {}
        self.all_discrepancies : List[Discrepancy]          = []

    # ── Public API ─────────────────────────────────────────────────────────────

    async def run(
        self,
        run_id  : str,
        req     : ReconcileRequest,
        trigger : TriggerType = TriggerType.MANUAL,
    ):
        result = ReconcileResult(
            run_id     = run_id,
            trigger    = trigger,
            status     = "running",
            started_at = datetime.utcnow(),
        )
        self.results[run_id] = result

        try:
            payments              = await self._fetch_payments(req)
            result.total_payments = len(payments)

            async with httpx.AsyncClient(timeout=10) as client:
                for p in payments:
                    record = await self._reconcile_payment(client, p)
                    result.payments.append(record)
                    if record.is_reconciled:
                        result.reconciled += 1
                    result.discrepancies_found += len(record.discrepancies)
                    self.all_discrepancies.extend(record.discrepancies)

            result.status       = "completed"
            result.completed_at = datetime.utcnow()
            result.summary      = self._build_summary(result)
            logger.info(
                f"Run {run_id} complete — trigger={trigger} "
                f"payments={result.total_payments} discrepancies={result.discrepancies_found}"
            )

        except Exception as e:
            logger.exception(f"Run {run_id} failed: {e}")
            result.status       = "failed"
            result.completed_at = datetime.utcnow()
            result.summary      = {"error": str(e)}

        self.results[run_id] = result

    def reconcile_single(self, payment_id: str) -> dict:
        return asyncio.run(self._single_sync(payment_id))

    def get_all_results(self) -> List[ReconcileResult]:
        return list(self.results.values())

    def get_result(self, run_id: str):
        return self.results.get(run_id, {"error": f"Run {run_id} not found"})

    def get_discrepancies(
        self,
        severity : Optional[str] = None,
        layer    : Optional[str] = None,
    ) -> List[Discrepancy]:
        out = self.all_discrepancies
        if severity:
            out = [d for d in out if d.severity.upper() == severity.upper()]
        if layer:
            out = [d for d in out if d.layer.upper() == layer.upper()]
        return out

    def get_stats(self) -> dict:
        by_layer, by_type, by_severity = {}, {}, {}
        for d in self.all_discrepancies:
            by_layer[d.layer]       = by_layer.get(d.layer, 0) + 1
            by_type[d.type]         = by_type.get(d.type, 0) + 1
            by_severity[d.severity] = by_severity.get(d.severity, 0) + 1
        completed = [r for r in self.results.values() if r.status == "completed"]
        return {
            "total_runs"                : len(self.results),
            "completed_runs"            : len(completed),
            "total_discrepancies"       : len(self.all_discrepancies),
            "discrepancies_by_layer"    : by_layer,
            "discrepancies_by_type"     : by_type,
            "discrepancies_by_severity" : by_severity,
        }

    # ── Payment fetching (with multi-endpoint discovery) ──────────────────────

    async def _fetch_payments(self, req: ReconcileRequest) -> List[dict]:
        """Entry point — routes to ID resolution or list fetch."""
        async with httpx.AsyncClient(timeout=10) as client:
            if req.payment_ids:
                return await self._resolve_ids(client, req.payment_ids)
            return await self._list_payments(client, req.limit)

    async def _list_payments(self, client: httpx.AsyncClient, limit: int) -> List[dict]:
        """
        Try each URL in config.PAYMENT_LIST_URLS until one returns data.
        Handles three shapes:
          • list of dicts  → use directly
          • list of strings → resolve each ID to a full object
          • dict envelope  → unwrap data/payments/items/results key
        """
        tried = []
        for base, path_tpl in config.PAYMENT_LIST_URLS:
            url = base + path_tpl.format(limit=limit)
            tried.append(url)
            try:
                r = await client.get(url, headers=GW_HEADERS)
                if r.status_code != 200:
                    logger.debug(f"List {url} → HTTP {r.status_code}, skipping")
                    continue

                data = r.json()

                # Unwrap envelope dicts
                if isinstance(data, dict):
                    items = (
                        data.get("data")
                        or data.get("payments")
                        or data.get("items")
                        or data.get("results")
                        or []
                    )
                else:
                    items = data  # raw list

                if not items:
                    logger.debug(f"List {url} → 200 but empty, skipping")
                    continue

                logger.info(f"Payment list resolved via {url} — {len(items)} item(s)")

                # Gateway returned IDs as plain strings
                if isinstance(items[0], str):
                    logger.info("Response is ID list — resolving to full objects")
                    return await self._resolve_ids(client, items[:limit])

                # Normalise: guarantee payment_id key
                out = []
                for p in items:
                    if isinstance(p, dict):
                        if "payment_id" not in p and "id" in p:
                            p["payment_id"] = p["id"]
                        out.append(p)
                return out

            except Exception as e:
                logger.debug(f"List {url} error: {e}, skipping")

        raise RuntimeError(
            f"Could not retrieve payment list — tried: {tried}. "
            "Check PAYMENT_LIST_URLS in config.py and confirm the service is healthy."
        )

    async def _resolve_ids(
        self, client: httpx.AsyncClient, ids: List[str]
    ) -> List[dict]:
        """Fetch full payment objects for a list of IDs via config.PAYMENT_DETAIL_URLS."""
        results = []
        for pid in ids:
            resolved = False
            for base, path_tpl in config.PAYMENT_DETAIL_URLS:
                url = base + path_tpl.format(id=pid)
                try:
                    r = await client.get(url, headers=GW_HEADERS)
                    if r.status_code == 200:
                        obj = r.json()
                        if isinstance(obj, dict):
                            if "payment_id" not in obj and "id" in obj:
                                obj["payment_id"] = obj["id"]
                            results.append(obj)
                            resolved = True
                            break
                except Exception:
                    continue
            if not resolved:
                logger.warning(f"Could not resolve payment {pid} from any detail endpoint")
        return results

    # ── Per-payment reconciliation ─────────────────────────────────────────────

    async def _reconcile_payment(self, client: httpx.AsyncClient, gw: dict) -> PaymentRecord:
        pid    = gw.get("payment_id") or gw.get("id")
        record = PaymentRecord(
            payment_id     = pid,
            gateway_amount = gw.get("amount"),
            gateway_status = gw.get("status"),
        )
        await self._check_ledger(client, record)
        await self._check_bank(client, record)
        await self._check_merchant(client, record)
        record.is_reconciled = len(record.discrepancies) == 0
        return record

    async def _check_ledger(self, client: httpx.AsyncClient, r: PaymentRecord):
        try:
            resp = await client.get(f"{config.LEDGER}/entries/payment/{r.payment_id}")
            if resp.status_code == 200:
                entries          = resp.json()
                r.ledger_entries = len(entries)
                if not entries:
                    r.discrepancies.append(self._disc(
                        r.payment_id, DiscrepancyType.MISSING_LEDGER_ENTRY, Severity.CRITICAL,
                        "LEDGER", str(r.gateway_amount), "NO_ENTRY",
                        f"No ledger entry for {r.payment_id}",
                    ))
                    return

                total = sum(
                    e.get("amount", 0) for e in entries
                    if e.get("entry_type") in ("debit", "capture", "credit")
                )
                r.ledger_amount = total

                if r.gateway_amount and abs(total - r.gateway_amount) > 1:
                    r.discrepancies.append(self._disc(
                        r.payment_id, DiscrepancyType.LEDGER_AMOUNT_MISMATCH, Severity.HIGH,
                        "LEDGER", str(r.gateway_amount), str(total),
                        f"Ledger total {total} ≠ Gateway {r.gateway_amount}",
                    ))

                ids = [e.get("entry_id") for e in entries if e.get("entry_id")]
                if len(ids) != len(set(ids)):
                    r.discrepancies.append(self._disc(
                        r.payment_id, DiscrepancyType.DOUBLE_ENTRY, Severity.CRITICAL,
                        "LEDGER", "unique", "duplicates",
                        f"Duplicate ledger entries for {r.payment_id}",
                    ))
            else:
                r.discrepancies.append(self._disc(
                    r.payment_id, DiscrepancyType.MISSING_LEDGER_ENTRY, Severity.CRITICAL,
                    "LEDGER", "HTTP 200", f"HTTP {resp.status_code}",
                    f"Ledger returned {resp.status_code} for {r.payment_id}",
                ))
        except Exception as e:
            r.discrepancies.append(self._disc(
                r.payment_id, DiscrepancyType.MISSING_LEDGER_ENTRY, Severity.HIGH,
                "LEDGER", "reachable", "ERROR", f"Ledger error: {e}",
            ))

    async def _check_bank(self, client: httpx.AsyncClient, r: PaymentRecord):
        try:
            resp = await client.get(f"{config.BANK}/transactions/{r.payment_id}")
            if resp.status_code == 200:
                tx            = resp.json()
                r.bank_amount = tx.get("amount")
                r.bank_status = tx.get("status")
                if r.gateway_amount and r.bank_amount and abs(r.bank_amount - r.gateway_amount) > 1:
                    r.discrepancies.append(self._disc(
                        r.payment_id, DiscrepancyType.BANK_AMOUNT_MISMATCH, Severity.CRITICAL,
                        "BANK", str(r.gateway_amount), str(r.bank_amount),
                        f"Bank charged {r.bank_amount}, Gateway shows {r.gateway_amount}",
                    ))
            elif resp.status_code == 404 and r.gateway_status in ("captured", "succeeded"):
                r.discrepancies.append(self._disc(
                    r.payment_id, DiscrepancyType.MISSING_BANK_TRANSACTION, Severity.CRITICAL,
                    "BANK", "bank_transaction", "NOT_FOUND",
                    f"Captured payment {r.payment_id} has no bank record",
                ))
        except Exception as e:
            logger.debug(f"Bank check skipped for {r.payment_id}: {e}")

    async def _check_merchant(self, client: httpx.AsyncClient, r: PaymentRecord):
        try:
            resp = await client.get(
                f"{config.MERCHANT}/payments/{r.payment_id}",
                headers=MR_HEADERS,
            )
            if resp.status_code == 200:
                mp                = resp.json()
                r.merchant_amount = mp.get("amount")
                r.merchant_status = mp.get("status")
                if r.gateway_status and r.merchant_status and r.gateway_status != r.merchant_status:
                    r.discrepancies.append(self._disc(
                        r.payment_id, DiscrepancyType.STATUS_MISMATCH, Severity.MEDIUM,
                        "MERCHANT", r.gateway_status, r.merchant_status,
                        f"Gateway={r.gateway_status} Merchant={r.merchant_status}",
                    ))
            elif resp.status_code == 404:
                r.discrepancies.append(self._disc(
                    r.payment_id, DiscrepancyType.MISSING_MERCHANT_RECORD, Severity.MEDIUM,
                    "MERCHANT", "merchant_record", "NOT_FOUND",
                    f"Payment {r.payment_id} not visible on merchant service",
                ))
        except Exception as e:
            logger.debug(f"Merchant check skipped for {r.payment_id}: {e}")

    async def _single_sync(self, payment_id: str) -> dict:
        async with httpx.AsyncClient(timeout=10) as client:
            ids = await self._resolve_ids(client, [payment_id])
            if not ids:
                return {"error": f"Payment {payment_id} not found on any detail endpoint"}
            record = await self._reconcile_payment(client, ids[0])
            return record.model_dump()

    # ── Helpers ────────────────────────────────────────────────────────────────

    @staticmethod
    def _disc(pid, dtype, severity, layer, expected, actual, message) -> Discrepancy:
        return Discrepancy(
            payment_id  = pid,
            type        = dtype,
            severity    = severity,
            layer       = layer,
            expected    = expected,
            actual      = actual,
            message     = message,
            detected_at = datetime.utcnow(),
        )

    @staticmethod
    def _build_summary(result: ReconcileResult) -> dict:
        all_d = [d for p in result.payments for d in p.discrepancies]
        by_type, by_severity, by_layer = {}, {}, {}
        for d in all_d:
            by_type[d.type]         = by_type.get(d.type, 0) + 1
            by_severity[d.severity] = by_severity.get(d.severity, 0) + 1
            by_layer[d.layer]       = by_layer.get(d.layer, 0) + 1
        return {
            "total_payments"            : result.total_payments,
            "reconciled"                : result.reconciled,
            "unreconciled"              : result.total_payments - result.reconciled,
            "discrepancies_by_type"     : by_type,
            "discrepancies_by_severity" : by_severity,
            "discrepancies_by_layer"    : by_layer,
        }
