# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: fraud_service/app/schemas/fraud.py

from datetime import datetime
from enum import Enum
from typing import Optional
from pydantic import BaseModel


class RiskLevel(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class CardData(BaseModel):
    number: str
    exp_month: int
    exp_year: int
    last4: str
    brand: str
    fingerprint: str


class CustomerData(BaseModel):
    id: str
    email: str
    ip_address: Optional[str] = None
    user_agent: Optional[str] = None


class FraudCheckRequest(BaseModel):
    payment_id: str
    merchant_id: str
    amount: int
    currency: str
    card: CardData
    customer: CustomerData
    metadata: Optional[dict] = None


class RuleResult(BaseModel):
    rule_name: str
    triggered: bool
    score_impact: int
    reason: Optional[str] = None


class FraudCheckResponse(BaseModel):
    payment_id: str
    allowed: bool
    risk_score: int
    risk_level: RiskLevel
    rules_score: int
    ml_score: float
    triggered_rules: list[RuleResult]
    recommendation: str
    review_required: bool
    block_reason: Optional[str] = None


class BlocklistAddRequest(BaseModel):
    type: str   # card_fingerprint | ip | email | customer_id
    value: str
    reason: str
    added_by: str
    expires_at: Optional[datetime] = None


class ConfirmFraudRequest(BaseModel):
    fraud_check_id: str
    is_fraud: bool
    confirmed_by: str
