# filename: scripts/seed_data.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

import requests
import time
from datetime import datetime, timedelta

BASE_URL = "http://localhost:8000"


def wait_for_api():
    """Wait for API to be ready"""
    print("⏳ Waiting for API to be ready...")
    for i in range(30):
        try:
            response = requests.get(f"{BASE_URL}/health", timeout=2)
            if response.status_code == 200:
                print("✅ API is ready!")
                return True
        except:
            pass
        time.sleep(1)
        if (i + 1) % 5 == 0:
            print(f"   Still waiting... ({i + 1}/30)")
    print("❌ API did not start in time")
    return False


def create_event(num_seats=10):
    """Create a test event"""
    print(f"\n📅 Creating event with {num_seats} seats...")
    event_data = {
        "event_name": "Rock Concert 2025",
        "event_date": (datetime.now() + timedelta(days=30)).isoformat(),
        "venue": "Madison Square Garden",
        "total_seats": num_seats  # Match actual seats to be created
    }

    response = requests.post(f"{BASE_URL}/events", json=event_data)
    if response.status_code == 201:
        event = response.json()
        print(f"✅ Event created: {event['event_name']}")
        print(f"   Event ID: {event['event_id']}")
        print(f"   Total Seats: {event['total_seats']}")
        return event['event_id']
    else:
        print(f"❌ Failed to create event: {response.text}")
        return None


def create_seats(event_id, count=10):
    """Create seats for the event"""
    print(f"\n🪑 Creating {count} seats...")
    seat_ids = []

    sections = ['A', 'B', 'C']
    seats_per_section = count // len(sections)
    remaining = count % len(sections)

    seat_count = 0

    for section_idx, section in enumerate(sections):
        # Add extra seat to first sections if there's a remainder
        section_seats = seats_per_section + (1 if section_idx < remaining else 0)

        for row in range(1, section_seats + 1):
            seat_data = {
                "seat_number": f"{section}{row}",
                "price": 100.00 + (ord(section) - ord('A')) * 20.00
            }

            response = requests.post(
                f"{BASE_URL}/events/{event_id}/seats",
                json=seat_data
            )

            if response.status_code == 201:
                seat = response.json()
                seat_ids.append(seat['seat_id'])
                print(f"   ✅ Seat {seat['seat_number']:<4} - ${float(seat['price']):.2f}")
                seat_count += 1
            else:
                print(f"   ❌ Failed to create seat: {response.text}")

            if seat_count >= count:
                break

        if seat_count >= count:
            break

    print(f"✅ Created {len(seat_ids)} seats")
    return seat_ids


def verify_data(event_id):
    """Verify the created data"""
    print(f"\n🔍 Verifying data...")

    # Get event
    event_response = requests.get(f"{BASE_URL}/events/{event_id}")
    event = event_response.json()

    # Get seats
    seats_response = requests.get(f"{BASE_URL}/events/{event_id}/seats")
    seats = seats_response.json()

    print(f"   Event total_seats: {event['total_seats']}")
    print(f"   Actual seats created: {len(seats)}")

    if event['total_seats'] == len(seats):
        print(f"   ✅ Counts match!")
        return True
    else:
        print(f"   ⚠️  Mismatch: {event['total_seats']} expected but {len(seats)} created")
        return False


def main():
    print("🚀 Starting data seeding...\n")

    # Wait for API
    if not wait_for_api():
        return

    # Create event with 10 seats
    num_seats = 10
    event_id = create_event(num_seats)
    if not event_id:
        return

    # Create seats
    seat_ids = create_seats(event_id, count=num_seats)

    # Verify
    verify_data(event_id)

    print("\n" + "=" * 60)
    print("✅ Data seeding complete!")
    print("=" * 60)
    print(f"\n📊 Summary:")
    print(f"   Event ID: {event_id}")
    print(f"   Seats created: {len(seat_ids)}")
    print(f"\n🔗 Quick Links:")
    print(f"   API Docs: {BASE_URL}/docs")
    print(f"   Health: {BASE_URL}/health")
    print(f"   Events: {BASE_URL}/events")
    print(f"   This Event: {BASE_URL}/events/{event_id}")
    print(f"   Event Seats: {BASE_URL}/events/{event_id}/seats")

    if seat_ids:
        print(f"\n💡 Test booking with:")
        print(f'   curl -X POST {BASE_URL}/bookings \\')
        print(f'     -H "Content-Type: application/json" \\')
        print(
            f'     -d \'{{"user_id": "550e8400-e29b-41d4-a716-446655440000", "event_id": "{event_id}", "seat_id": "{seat_ids[0]}"}}\'')

    print(f"\n💡 Test with different number of seats:")
    print(f"   python scripts/seed_data.py")


if __name__ == "__main__":
    main()
