# filename: scripts/test_concurrent.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

import requests
import concurrent.futures
import uuid
import sys

BASE_URL = "http://localhost:8000"


def book_seat(user_id, event_id, seat_id):
    """Attempt to book a seat"""
    try:
        response = requests.post(
            f"{BASE_URL}/bookings",
            json={
                "user_id": str(user_id),
                "event_id": event_id,
                "seat_id": seat_id
            },
            timeout=10
        )
        return response.status_code, response.json()
    except Exception as e:
        return 500, {"error": str(e)}


def test_concurrent_bookings(event_id, seat_id, num_users=20):
    """Test multiple users trying to book the same seat"""
    print(f"\n{'=' * 70}")
    print(f"🧪 CONCURRENT BOOKING TEST")
    print(f"{'=' * 70}")
    print(f"Event ID: {event_id}")
    print(f"Seat ID:  {seat_id}")
    print(f"Users:    {num_users} concurrent users")
    print(f"{'=' * 70}\n")

    print(f"🏁 Starting race condition test...")
    print(f"   All {num_users} users will try to book the SAME seat simultaneously\n")

    # Create multiple users trying to book simultaneously
    with concurrent.futures.ThreadPoolExecutor(max_workers=num_users) as executor:
        futures = [
            executor.submit(book_seat, uuid.uuid4(), event_id, seat_id)
            for _ in range(num_users)
        ]

        results = [f.result() for f in futures]

    # Analyze results
    successes = [r for r in results if r[0] == 201]
    conflicts = [r for r in results if r[0] == 409]
    errors = [r for r in results if r[0] not in [201, 409]]

    print("\n" + "=" * 70)
    print("📊 TEST RESULTS")
    print("=" * 70)
    print(f"✅ Successful bookings: {len(successes)}")
    print(f"❌ Conflicts (409):     {len(conflicts)}")
    print(f"⚠️  Other errors:       {len(errors)}")
    print("=" * 70)

    if len(successes) == 1:
        print("\n🎉 TEST PASSED!")
        print("   Only 1 booking succeeded - No double-booking!")
        print(f"   Winner booking ID: {successes[0][1].get('booking_id')}")
        success = True
    else:
        print(f"\n❌ TEST FAILED!")
        print(f"   {len(successes)} bookings succeeded - DOUBLE-BOOKING DETECTED!")
        success = False

    if conflicts:
        print(f"\n✅ {len(conflicts)} users correctly received 'Seat already booked' error")

    if errors:
        print("\n⚠️  Unexpected errors occurred:")
        for status, body in errors[:3]:  # Show first 3 errors
            print(f"   Status {status}: {body}")

    return success


def main():
    if len(sys.argv) != 3:
        print("Usage: python test_concurrent.py <event_id> <seat_id>")
        print("\nGet these IDs by running:")
        print("  1. curl http://localhost:8000/events")
        print("  2. curl http://localhost:8000/events/{event_id}/seats")
        sys.exit(1)

    event_id = sys.argv[1]
    seat_id = sys.argv[2]

    success = test_concurrent_bookings(event_id, seat_id, num_users=20)

    print("\n" + "=" * 70)
    if success:
        print("✅ SYSTEM CORRECTLY PREVENTS DOUBLE-BOOKING")
    else:
        print("❌ SYSTEM HAS DOUBLE-BOOKING VULNERABILITY")
    print("=" * 70 + "\n")

    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
